### ISSUE TITLE
Implement Auth Manager

### ISSUE THREAD

**Issue by arunoda** [kadirahq/flow-router#139]
This is not a direct flow router API. But, we need to show how to decouple auth logics from the router and move them to the template or lower layer.

**Comment by zimt28** [comment]
Do you mean login pages? I'm currently just using Tracker and it works great:

```coffee

### Client ###

Meteor.startup ->

  # Show Login when the user is not logged in
  Tracker.autorun ->

    FlowRouter.watchPathChange()

    loggedIn = !!Meteor.userId() or Meteor.loggingIn()

    return  if loggedIn

    FlowRouter.go '/login'
```

**Comment by arunoda** [comment]
Seems like we need a blog post. Not a package.

**Comment by peterchoo** [comment]
Hi there,  

Hopefully this isn't impertinent, would you be able to give an ETA on this blog post?  It's something I see people asking about regularly.  My current approach is using a  global tracker to redirect if the user logs out, but want to know if there's more to it than that from your perspective.

Many thanks for all your hard work!

**Comment by ianmartorell** [comment]
@peterchoo [this](https://kadira.io/academy/meteor-routing-guide/content/implementing-auth-logic-and-permissions) is probably helpful!
