### ISSUE TITLE
flow-router-ssr : call server method in route action from server : cannot find data in collection if not subscribed

### ISSUE THREAD

**Issue by fabien-h** [kadirahq/flow-router#205]
There are some collections that I do not wish to publish (like `Meteor.users`, or internal stats) and some datas I want to get in straight json and not as cursors (for pagination purpose mostly). So I want to get them from a `Meteor.call`. No subscription and no reactivity.

It works client side, but not server side.

To reproduce, clone the repo of the hello react meteor application : https://github.com/arunoda/hello-react-meteor. Then in the router.jsx, change that code :

```
action: function() {
  ReactLayout.render(BlogLayout, {
    content: <PostList />
  });
}
```

To that one :

```
action: function() {
  Meteor.call('getPost', function (err, res) {
    console.log('err : ', err);
    console.log('res : ', res);
    ReactLayout.render(BlogLayout, {
      content: <PostList />
    });
  });
}
```

And add the method to retrieve a post :

```
 if( Meteor.server )
    Meteor.methods({
      getPost(){
        return Posts.findOne();
      }
    });
```

You can now find the retrieved post in the client and server console. It works.

But now, comment the subscription :

```
//this.register('posts', Meteor.subscribe('posts', selector));
```

Client side, it keeps working, but server side, the result is now undefined (the view is broken now of course, but we don't care for this example).

Is it a bug ? Is it supposed to work that way ? Is there a workaround ?

Here are the stack traces :

Call from server :

```
Trace: undefined
at [object Object].Meteor.methods.getPost (both/router.jsx:14:19)
at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
at packages/ddp/livedata_server.js:1530:1
at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
at [object Object]._.extend.apply (packages/ddp/livedata_server.js:1529:1)
at [object Object]._.extend.call (packages/ddp/livedata_server.js:1472:1)
at FlowRouter.route.action (both/router.jsx:25:12)
at packages/meteorhacks:flow-router-ssr/server/route.js:19:1
at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
at packages/meteorhacks:flow-router-ssr/server/route.js:13:1
at doCall (packages/meteorhacks:picker/lib/implementation.js:98:1)
```

Call from client

```
Trace: one
at [object Object].Meteor.methods.getPost (both/router.jsx:13:19)
at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
at packages/ddp/livedata_server.js:648:1
at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
at packages/ddp/livedata_server.js:647:1
at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
at packages/ddp/livedata_server.js:546:1
```

From what I understand, this is a context matter. But I have no idea how to solve that.

**Comment by fabien-h** [comment]
I tried to subscribe globally to 'posts' like that :

    FlowRouter.subscriptions = function() {
      this.register('posts', Meteor.subscribe('posts'));
    };

And it does not work, I have to have a specific subscription for the route.

**Comment by arunoda** [comment]
I'll have some guides on SSR soon with limitations. So, in the current state, things changes a lot. 
I suggest you to wait a few days.

**Comment by arunoda** [comment]
I haven't tried meteor methods in the code yet. May be we won't support it.

**Comment by fabien-h** [comment]
Will this help to solve the problem : https://github.com/meteor/meteor/pull/4939 ?

**Comment by fabien-h** [comment]
Will this help to solve the problem : https://github.com/meteor/meteor/pull/4939 ?

**Comment by arunoda** [comment]
I think it's not related. Currently we don't support or haven't done any
experiments with method calls.

You should use a subscription to get data. Otherwise, it data won't show
up.

So basically, even it runs on the server it has client side like context.

**Comment by fabien-h** [comment]
Sorry, I explained myself poorly : You **DO** support method calls. They work with flow router SSR.

If you fork your repo : https://github.com/arunoda/hello-react-meteor and change the first route to that : 

    FlowRouter.route("/", {
      action: function() {
        Meteor.call( 'getNumber', ( error, number ) => {
          ReactLayout.render(BlogLayout, {
            content: <PostList number={ number } />
          });
        } );
      }
    });

Then create the corresponding method :

	getNumber() {
		return 42;
	},

And then add this in the render function : `<div>My number : { this.props.number }</div>`

It works, the server send this code : `My Blog </h1><div data-reactid=".bg4v8zp6gw.2"><div data-reactid=".bg4v8zp6gw.2.0"><span data-reactid=".bg4v8zp6gw.2.0.0">My number : </span><span data-reactid=".bg4v8zp6gw.2.0.1">42</span></div>`

When you `console.log( this.props.number )` in the render function of the PostList component, the terminal and the console return 42. So, no question. You can call a method and it works well to send static data. But, when you try another method like :

	getPost() {
		return Posts.findOne();
	},

It stops working server side and returns undefined (but still works client side). It would be a killer feature to be able to send a collection count in the props for instance. Or to modify a cursor server side to inject needed translations for i18n.

So the question is not 'why metor call don't work server side in the router', but 'why meteor call cannot get data from a collection'.

I'm not sure why this happens, but I suspect a synchronicity problem. Try this for instance :

    FlowRouter.route("/", {
      action: function() {
        Meteor.setTimeout( () => {
          ReactLayout.render(BlogLayout, {
            content: <PostList />
          });
        }, 2000 );
      }
    });

Ok, you would never do that in real life. It still works client side : when you land on the page, nothing happen for 2 sec and the page renders. But server side, nothing is rendered. `<body><div id='react-root'></div>`is returned.

So, it behave like async is not possible.

**Comment by arunoda** [comment]
Okay. Now I got it and I know the issue.
That's because, since you call if from the SSR context, Method call also has the SSR context.
I know how to fix this.

I will do a fix.

**Comment by arunoda** [comment]
I've did some changes to the latest version and this should work with that. Could you try with the SSR branch.

**Comment by fabien-h** [comment]
Well, now it's broken with a big and scarry error message :

	xception in delivering result of invoking 'getNumber': Error: Can't call yield in a noYieldsAllowed block!
	I20150817-11:58:52.452(2)?     at Function.Fiber.yield (packages/meteor/fiber_helpers.js:8:1)
	I20150817-11:58:52.453(2)?     at Function.wait (/Users/fabienhuet/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:183:14)
	I20150817-11:58:52.453(2)?     at Object.Future.wait (/Users/fabienhuet/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:397:10)
	I20150817-11:58:52.453(2)?     at [object Object]._.extend._nextObject (packages/mongo/mongo_driver.js:929:1)
	I20150817-11:58:52.453(2)?     at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:963:1)
	I20150817-11:58:52.453(2)?     at [object Object]._.extend.map (packages/mongo/mongo_driver.js:973:1)
	I20150817-11:58:52.453(2)?     at [object Object]._.extend.fetch (packages/mongo/mongo_driver.js:997:1)
	I20150817-11:58:52.453(2)?     at [object Object].Cursor.(anonymous function) [as fetch] (packages/mongo/mongo_driver.js:812:1)
	I20150817-11:58:52.453(2)?     at [object Object].React.createClass.getMeteorData (both/components/post_list.jsx:8:53)
	I20150817-11:58:52.454(2)?     at packages/react-meteor-data/meteor-data-mixin.jsx:73:28
	W20150817-11:58:52.496(2)? (STDERR) error on fast-rendering path: / ; error: Error: Can't set headers after they are sent.
	W20150817-11:58:52.496(2)? (STDERR)     at ServerResponse.OutgoingMessage.setHeader (http.js:690:11)
	W20150817-11:58:52.496(2)? (STDERR)     at ServerResponse.res.setHeader (/Users/fabienhuet/.meteor/packages/webapp/.1.2.0.15p5axz++os+web.browser+web.cordova/npm/node_modules/connect/lib/patch.js:59:22)
	W20150817-11:58:52.496(2)? (STDERR)     at next (/Users/fabienhuet/.meteor/packages/webapp/.1.2.0.15p5axz++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:153:13)
	W20150817-11:58:52.497(2)? (STDERR)     at next (/Users/fabienhuet/.meteor/packages/webapp/.1.2.0.15p5axz++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:127:23)
	W20150817-11:58:52.497(2)? (STDERR)     at processNextSubRouter (packages/meteorhacks:picker/lib/implementation.js:74:1)
	W20150817-11:58:52.497(2)? (STDERR)     at processNextSubRouter (packages/meteorhacks:picker/lib/implementation.js:74:1)
	W20150817-11:58:52.497(2)? (STDERR)     at processNextRoute (packages/meteorhacks:picker/lib/implementation.js:65:1)
	W20150817-11:58:52.497(2)? (STDERR)     at processNextMiddleware (packages/meteorhacks:picker/lib/implementation.js:48:1)
	W20150817-11:58:52.497(2)? (STDERR)     at packages/meteorhacks:fast-render/lib/server/routes.js:39:1
	W20150817-11:58:52.497(2)? (STDERR)     at packages/meteorhacks:fast-render/lib/server/routes.js:93:1
	W20150817-11:58:52.497(2)? (STDERR) error on fast-rendering path: / ; error: Error: Can't set headers after they are sent.
	W20150817-11:58:52.498(2)? (STDERR)     at ServerResponse.OutgoingMessage.setHeader (http.js:690:11)
	W20150817-11:58:52.498(2)? (STDERR)     at ServerResponse.res.setHeader (/Users/fabienhuet/.meteor/packages/webapp/.1.2.0.15p5axz++os+web.browser+web.cordova/npm/node_modules/connect/lib/patch.js:59:22)
	W20150817-11:58:52.498(2)? (STDERR)     at next (/Users/fabienhuet/.meteor/packages/webapp/.1.2.0.15p5axz++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:153:13)
	W20150817-11:58:52.498(2)? (STDERR)     at next (/Users/fabienhuet/.meteor/packages/webapp/.1.2.0.15p5axz++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:127:23)
	W20150817-11:58:52.498(2)? (STDERR)     at processNextSubRouter (packages/meteorhacks:picker/lib/implementation.js:74:1)
	W20150817-11:58:52.498(2)? (STDERR)     at processNextSubRouter (packages/meteorhacks:picker/lib/implementation.js:74:1)
	W20150817-11:58:52.499(2)? (STDERR)     at processNextRoute (packages/meteorhacks:picker/lib/implementation.js:65:1)
	W20150817-11:58:52.499(2)? (STDERR)     at processNextMiddleware (packages/meteorhacks:picker/lib/implementation.js:48:1)
	W20150817-11:58:52.499(2)? (STDERR)     at packages/meteorhacks:fast-render/lib/server/routes.js:20:1
	W20150817-11:58:52.499(2)? (STDERR)     at handleError (packages/meteorhacks:fast-render/lib/server/routes.js:106:1)
	W20150817-11:58:52.499(2)? (STDERR)
	W20150817-11:58:52.499(2)? (STDERR) /Users/fabienhuet/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
	W20150817-11:58:52.504(2)? (STDERR) 						throw(ex);
	W20150817-11:58:52.504(2)? (STDERR) 						      ^
	W20150817-11:58:52.504(2)? (STDERR) Error: Can't set headers after they are sent.
	W20150817-11:58:52.505(2)? (STDERR)     at ServerResponse.OutgoingMessage.setHeader (http.js:690:11)
	W20150817-11:58:52.505(2)? (STDERR)     at ServerResponse.res.setHeader (/Users/fabienhuet/.meteor/packages/webapp/.1.2.0.15p5axz++os+web.browser+web.cordova/npm/node_modules/connect/lib/patch.js:59:22)
	W20150817-11:58:52.505(2)? (STDERR)     at next (/Users/fabienhuet/.meteor/packages/webapp/.1.2.0.15p5axz++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:153:13)
	W20150817-11:58:52.505(2)? (STDERR)     at next (/Users/fabienhuet/.meteor/packages/webapp/.1.2.0.15p5axz++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:127:23)
	W20150817-11:58:52.505(2)? (STDERR)     at processNextSubRouter (packages/meteorhacks:picker/lib/implementation.js:74:1)
	W20150817-11:58:52.506(2)? (STDERR)     at processNextRoute (packages/meteorhacks:picker/lib/implementation.js:65:1)
	W20150817-11:58:52.506(2)? (STDERR)     at processNextMiddleware (packages/meteorhacks:picker/lib/implementation.js:48:1)
	W20150817-11:58:52.506(2)? (STDERR)     at packages/meteorhacks:fast-render/lib/server/routes.js:20:1
	W20150817-11:58:52.506(2)? (STDERR)     at handleError (packages/meteorhacks:fast-render/lib/server/routes.js:106:1)
	W20150817-11:58:52.506(2)? (STDERR)     at packages/meteorhacks:fast-render/lib/server/routes.js:95:1
	=> Exited with code: 8

**Comment by fabien-h** [comment]
Maybe it could be put in `triggersEnter`. But triggersEnter is not supported server side.

**Comment by arunoda** [comment]
Can I have a sample code for this. I need to experiment with this.

May be this leads to anti-pattern or something. Let's see.

**Comment by fabien-h** [comment]
Of course :
https://www.dropbox.com/s/vxq5ipqub2psqm9/examples-ssr.zip

The "call-value" example works client and server side. (look at the generated source code)
The "call-collection" example works client side but not server side (the call returns `undefined`).

When you use the last version of the ssr branch (not the one on atmosphere, juste download and use as a local package), both examples crash the whole thing.

**Comment by arunoda** [comment]
I can understand the issue. Will work it.

**Comment by fabien-h** [comment]
You are the man !

**Comment by fabien-h** [comment]
Any news on that one ?

**Comment by fabien-h** [comment]
I looked at it a bit and here's the problem :

    ReactLayout._renderServer = function(layoutClass, regions) {         // 29
      var el = React.createElement(layoutClass, regions);                // 30
      var html = React.renderToString(el);                               // 31
                                                                         // 32
      if(Package['kadira:flow-router-ssr']) {                            // 33
        var FlowRouter = Package['kadira:flow-router-ssr'].FlowRouter;   // 34
        var ssrContext = FlowRouter.ssrContext.get();                    // 35
        ssrContext.setHtml(html);                                        // 36
      }                                                                  // 37
    };                                                                   // 38

When `ReactLayout.render` is called asynchronousely, `FlowRouter.ssrContext.get()` is null. The solution is probably to provide it when you call `ReactLayout.render`. For example :

	action( params, queryParams ) {
		let context;
		if ( Meteor.isServer ) {
			context = FlowRouter.ssrContext.get();
		}
		Meteor.call( 'getPostData', params.slug, ( error, result ) => {
			if ( Meteor.isServer ) {
				let el = React.createElement( ReactLayouts.MainLayout, {
					content: <ReactViews.Post data={ result } />,
				} );
				let html = React.renderToString( el );
				context.setHtml( html );
			} else
				ReactLayout.render( ReactLayouts.MainLayout, {
					content: <ReactViews.Post data={ result } />,
				} );

		} );
	}

This way, it works. But it's ugly. The action hook should send by default the ssr context, so it's never lost.

I try to make a PR.

(and for dochead, it's the same problem)

**Comment by tomwasd** [comment]
Hi,

Just adding my support to this. Being able to have the result of a Meteor method available would be very helpful.

I currently use a meteor method to get an array of _ids and then subscribe to the those _ids. It lets me keep the initial ordering of the documents whilst retaining reactivity (this article describes it in more detail: http://tomkelsey.co.uk/reining-in-the-reactivity-with-meteor/)

I haven't worked out how to do this with SSR as I can't wait on the method call on the client - so react reports a mismatch between the client and server code.

If @fabien-h's PR solves the issue I'm all for it :+1:

**Comment by sammkj** [comment]
I'm having the same problem too! But with `react-mounter`. Has this been resolved? Or FR SSR won't support this?

**Comment by SachaG** [comment]
You can use Inject-Initial as a workaround to make data instantly available on the client: https://github.com/meteorhacks/meteor-inject-initial

**Comment by MickaelBZH** [comment]
Hi,

Any update on how to fetch content with methods and SSR?
