### ISSUE TITLE
how to wait (loading) FlowRouter.subsReady in template helper?

### ISSUE THREAD

**Issue by thearabbit** [kadirahq/flow-router#229]
I seem don't understand for waiting `FlowRouter.subsReady()` in helper.
I want to wait (loading), if I don't get data  ready like this
```js
// Router
FlowRouter.route('/post', {
    subscriptions: function(params) {
        this.register('myPost', Meteor.subscribe('blogPost'));
    },
    action: function(params) {
        BlazLayout.render('layout', {content: 'myTpl'});
    }
});

// Template
{{#if data}}
   {{data}}
{{else}}
    {{> loading}}
{{/if}}

// Js
Template.myTpl.helpers({
   data: function(){
      FlowRouter.subsReady("myPost", function() {
          var data = Post.findOne();

          return data;
      });
   }
});
```
Please help me.

**Comment by arunoda** [comment]
Check this: https://kadira.io/academy/meteor-routing-guide/content/subscriptions-and-data-management

**Comment by thearabbit** [comment]
Thanks for your reply, but I still don't understand.
Could you example for my option above?

**Comment by lucatros** [comment]
@thearabbit you might also want to check this: https://meteorhacks.com/flow-router-and-subscription-management

Also, pay attention to the typo on ````BlazLayout.render```` (it should be ````BlazeLayout.render````

**Comment by thearabbit** [comment]
Thanks again, I will try.

**Comment by thearabbit** [comment]
Now I understand, I must to use 2 properties on helper (isReady and data)
```js
// Template
{{#if isReady}}
   {{data}}
{{else}}
    {{> loading}}
{{/if}}

// Js
Template.myTpl.helpers({
   isReady: function(){
      return FlowRouter.subsReady(sub);
   },
   data: function(){
          var data = Post.findOne();
          return data;
   }
});
```
