### ISSUE TITLE
How to redirect router when User logout?

### ISSUE THREAD

**Issue by thearabbit** [kadirahq/flow-router#231]
I want to redirect router when user logout.
Example I have
```js
Currently I stay at  
// admin/event
when click logout it will go to
// '/'
```

**Comment by arunoda** [comment]
How you handle the logout code. If you are using `Meteor.logout` you can do this:

~~~js
Meteor.logout(function() {
  FlowRouter.go('/');
});
~~~

**Comment by thearabbit** [comment]
I use `ian:accounts-ui-bootstrap-3`.

**Comment by thearabbit** [comment]
Work fine. thanks :+1:

**Comment by ldong** [comment]
Here's the second way of doing it.

```
FlowRouter.route('/logout', {
  name: 'logout',
  action() {
    Accounts.logout();
    FlowRouter.go('/');
  }
});
```

**Comment by soulmachine** [comment]
@ldong the URL in the browser address bar doesn't change if you use `FlowRouter.go('/')`, however, `FlowRouter.redirect('/')` works well.
