### ISSUE TITLE
Use "FlowRouter.getQueryParam(queryStringKey), FlowRouter.getParam(paramName)" with multi query key???

### ISSUE THREAD

**Issue by thearabbit** [kadirahq/flow-router#232]
Could I use `FlowRouter.getQueryParam(queryStringKey), FlowRouter.getParam(paramName)` with multi key like object
```js
var q = FlowRouter.getQueryParam();
q.key1;
q.key2
...
```
How to solve this?

**Comment by abernix** [comment]
You might be looking for something like this:

```
FlowRouter.current().queryParams
```

Which will return an object containing all of the query params.

Please note, that *unlike* ``getQueryParam``, this is **not reactive**.  If you need reactivity, you'll need to use [``watchPathChange``](https://github.com/kadirahq/flow-router#flowrouterwatchpathchange).

**Comment by thearabbit** [comment]
Very thanks, I will try.
