### ISSUE TITLE
Weird bug after updating: links don't work, routes do

### ISSUE THREAD

**Issue by lsunsi** [kadirahq/flow-router#233]
Just updated to kadira:flow-router and kadira:flow-layout.

I'm getting a weird bug where all link from my page won't work properly ("There is no route ..." printed on console).

If I use FlowRouter.go from console it works fine, and so does typing to URL for the route.

Am I doing something wrong?

**Comment by arunoda** [comment]
You need to remove old meteorhacks:flow-router. Check the README for
migration guide.

**Comment by lsunsi** [comment]
I did that already before I opened this issue.
Removed both old packages and added the new ones.

**Comment by jhuenges** [comment]
Are you using a flow router helpers package?

**Comment by lsunsi** [comment]
I had the flow-router-helpers package added.
Removing it I noticed it kept the meteorhacks flow-router installed, as a dependency.

Thanks guys, it's fixed now
