### ISSUE TITLE
serving static files

### ISSUE THREAD

**Issue by greenwolfe** [kadirahq/flow-router#235]
I apologize if this is a basic question.
I am using tomi:meteor-uploads to enable users to upload files to my web site.  The upload works fine with flow router.  Say the file is uploaded to /.uploads/filename.txt .  With iron router, I just put in an anchor tag 

    <a href="/uploads/filename.txt"> filename</a>

and the link worked.  The user clicks on it and the browser opens it in a new tab or prompts the user to download it, etc.  

Flow router seems to interpret the link as a route and returns "There is no route for the path:" "/.upload/fileName.txt"  

How do I serve static files with flow router?

**Comment by greenwolfe** [comment]
I have found the following workaround:

    var parentPath;
    FlowRouter.triggers.exit([function(context,redirect) {
      parentPath = context.path;
    }])
    
    var uploadRoutes = FlowRouter.group({
      prefix: '/upload',
      triggersEnter: [function(context, redirect) {
        window.open(Meteor.absoluteUrl(context.path),"","",true); //open file in a new window, browser handles from there
        redirect(parentPath); //redirect parent window back to parent template
      }]
    });
    
    uploadRoutes.route('/(.*)',{})

This has the advantage over the iron router behavior that I now have a ready place for validation and permissions - to check if the user is logged in and has the rights to view the file before serving it, which is required in my case.

I realize I could just put the triggersEnter in the route rather than the group, but I like the prefix syntax better.  It would be nice if it worked without needing a route definition with the regexp to select all of the sub routes.  

Does anyone have a more elegant solution, or is there a standard way that flowrouter was designed to handle static files that I just failed to find?  Suggestions appreciated.

Thanks,

Matt

**Comment by arunoda** [comment]
Try this. I haven't try this, but it should work properly.

~~~html
<a href="/uploads/filename.txt" target="_blank"> filename</a>
~~~

**Comment by meteor-software** [comment]
I've found the same bug when I created link to server side route made with Picker package.

Temporary for solution for me is using target="_self" - It doesn't change link's behavior and works well.

**Comment by greenwolfe** [comment]
Took me a while to get back to this but target="_blank" works in my case, opening the document in a new tab.  I did not test target="_self" which may well also work, and might provide different handling.

**Comment by arunoda** [comment]
I think it's better to have a section on the README for this.

**Comment by arunoda** [comment]
We use page.js behind the scene and they handle this feature. I'm quoting it. 

> **Under certain conditions, links will be disregarded and will not be dispatched, such as:**
> 
> Links that are not of the same origin
> Links with the `download` attribute
> Links with the `target` attribute
> Links with the `rel="external"` attribute

See more: https://github.com/kadirahq/page.js#pagepath-callback-callback-

I'm locking this issue because this act as a documentation.
