### ISSUE TITLE
Redirect() and FlowRouter.go() do not update address bar when called within trigger

### ISSUE THREAD

**Issue by serkandurusoy** [kadirahq/flow-router#239]
I'm using a basic trigger to check the currently logged in user's role and if it does not pass, I redirect to another route:

````javascript
function requireRoleAdmin(context,redirect) {
  if (Meteor.isClient){
    if ( !userHasRole('admin') ) {
      redirect('/');
    }
  }
}

FlowRouter.route('/', {
  name: 'home',
  action: function(params) {
    BlazeLayout.render('mainLayout', { main: "home", navbar: "topNav", sidenav: "sideNav" });
  }
});

FlowRouter.route('/adminonly', {
  name: 'adminOnly',
  triggersEnter: [requireRoleAdmin],
  action: function(params) {
    BlazeLayout.render('mainLayout', { main: "adminOnly", navbar: "topNav", sidenav: "sideNav" });
  }
});

````

When I enter `http://localhost:3000/adminonly` directly, I do get redirected to `http://localhost:3000/` but if I click on links with `<a href="/adminonly">Go to admin area</>` although the `home` template gets rendered, the URL on the address bar remains unchanged as `http://localhost:3000/adminonly`.

The behavior is the same when I use `FlowRouter.go('/')` instead as well.

**Comment by arunoda** [comment]
You should not check user permission on the router. Could you check there are any errors on the console? If so, just bring them here.

**Comment by serkandurusoy** [comment]
I'm not checking permission on the router, I already do that on the
main layout and establish a user session.

There's no reactive dependency either, just a simple one time check of
an information that is altrady on the client.

Besides, there is no problem with direct entry, just clicks on links.

There is no error printed on the console.

**Comment by arunoda** [comment]
Okay. I will have a look at this.

**Comment by arunoda** [comment]
Hi,

I just fixed this issue.
Could you try with the new version: `2.0.1`

**Comment by serkandurusoy** [comment]
Yes, it now works as expected. Thanks.
