### ISSUE TITLE
Could I add both "kadira:flow-router" and "meteorhacks:flow-router"?

### ISSUE THREAD

**Issue by thearabbit** [kadirahq/flow-router#240]
Could I add both `kadira:flow-router` and `meteorhacks:flow-router`?
Because I has any package use `meteorhacks:flow-router` such as: `arillo:flow-router-helpers, zimme:active-route`

**Comment by arunoda** [comment]
No you can't do that. 
I think both of those packages working for a fix.
For now, stick with the older version. Once the new version comes, migrate.
