### ISSUE TITLE
Could I use the waiting (loading) with Meteor method?

### ISSUE THREAD

**Issue by thearabbit** [kadirahq/flow-router#241]
I use `Meteor method`, I want to show (loading) when calling in client like sub is ready.
```js
// Server
Meteor.method({
   myMethod: function(){
    // do ..... (time: 5000ms)
    return data;
  }
})

// Client
Template.myTpl.helpers({
   data: function(){
      Meteor.call('myMethod', ..........);
      .......
      return data; 
   }
});
```
I want  to wait after calling is completed.

**Comment by arunoda** [comment]
I think this a question you should post on Stackoverflow.

**Comment by thearabbit** [comment]
Excuse me, I think that I could use other way in Flow Router like subscription.
