### ISSUE TITLE
Problem with submit form that use action="url" attribute (Error: There is no route for...)?

### ISSUE THREAD

**Issue by thearabbit** [kadirahq/flow-router#242]
I use form action attribute like this to generate report (open new tab)
```js
// Router
FlowRoutes.route('/reportgen', {
    name: 'reportgen',
    action: function (params, queryParams) {
       Console.log('Hi My Report');
    }
});

// Template
        {{#autoForm schema=EventReport id="eventReport" action="reportgen" target="_blank"}}
                    {{> afQuickField name='user'}}
                    {{> afQuickField name='type'}}

                    <button type="submit" class="btn btn-primary"> Generate</button>
                    <button type="reset" class="btn btn-default">Reset</button>
        {{/autoForm}}

// It show error
There is no route for the path: /reportgne?user=kNvsQFxxKP2SkMdSy&type=typeVal
```
Please help me.

**Comment by thearabbit** [comment]
Oh now it don't have problem with this.
It is always show `There is no route for the path: /` in browser console.

**Comment by arunoda** [comment]
It's very hard to debug like these question like this. You need, give us a sample project with the bug.
I assume, either you don't have a route for "/" or you are using two different versions of FlowRouter is a single app.

**Comment by thearabbit** [comment]
Now I think that it have problem with packages helper use difference `meteorhack:, kidira:`.
I will check again, when all of packages helper up to date (kidira).

**Comment by arunoda** [comment]
I think that's the issue. If there is any issue once the helper package updated, reopen this issue.
