### ISSUE TITLE
Paths failing to run at all

### ISSUE THREAD

**Issue by teknetia** [kadirahq/flow-router#244]
I've created a couple of layouts and routes but when I try to go to any of them (root included) I just get failure messages. I have been through multiple things and can't figure out what would be causing the grief. I am sure it is something silly and I have overlooked it but no amount of googling or re-coding has achieved anything beneficial. Any help massively appreciated!

Errors in the Chrome Console:
<img width="1295" alt="screen shot 2015-08-02 at 12 38 24" src="https://cloud.githubusercontent.com/assets/7970809/9024460/97d7ba16-3913-11e5-8ca0-8d6bb1046dc3.png">

lib/router.js:
```javascript
FlowRouter.notfound = {
	action: function() {
		BlazeLayout.render('Blank', { content: 'NotFound' });
	}
};

//Home page routes
FlowRouter.route('/', {
	name: 'home',
	action: function() {
		BlazeLayout.render('Standard', { content: 'Dashboard' } );
		console.log('Home rendered');
	}
});

//Login page
FlowRouter.route('/login', {
	name: 'login',
	action: function() {
		BlazeLayout.render('Blank', { content: 'Login' });
	}
});

//Register page
FlowRouter.route('/register', {
	name: 'register',
	action: function() {
		BlazeLayout.render('Blank', { content: 'Register' });
	}
});
```

client/global.html:
```html
<template name="Standard">
	{{> Header}}
	{{> Template.dynamic template=content}}
	<footer>
		<p>&copy; Copyright 2015 • All Rights Reserved</p>
	</footer>
</template>

<template name="Blank">
	<div class="background brand-bg">
		{{> Template.dynamic template=content}}
	</div>
</template>

<template name="Header">
	<h1>This is the header</h1>
	<p>Hello, you're logged in!</p>
</template>

<template name="NotFound">
	<h1>404 Not Found!</h1>
	<p>Oops, can't find that, sorry!</p>
</template>
```

client/login/login.html:
```html
<template name="Login">
	<div class="small-container">
		<header>
			<img src="http://placehold.it/200x200">
			<h1>Login to see your dashboard</h1>
		</header>
		<form class="login-form" id="loginForm" method="post">
		  <label for="loginEmail">Email address</label>
		  <input type="email" name="loginEmail" placeholder="Email address">
		  <label for="loginPassword">Password</label>
		  <input type="password" name="loginPassword" placeholder="Password">
		  <a href="{{route 'register'}}" class="light button">Register</a>
		  <input type="submit" class="login-btn" value="Login">
		</form>
		<hr>
		<ul>
			<li><button type="button" class="login-google"><i class="fa fa-google"></i> Sign in with Google</button></li>
			<li><button type="button" class="login-microsoft"><i class="fa fa-windows"></i> Sign in with Microsoft</button></li>
		</ul>
	</div>
</template>

<template name="Register">
  <div class="background brand-bg">
    <header>
    	<img src="http://placehold.it/200x200">
    	<h1>Register</h1>
    </header>
    <form class="register-form" id="registerForm" method="post">
	    <label for="registerName">Your name</label>
	    <input type="text" name="registerName" placeholder="Your name">
      <label for="registerEmail">Email address</label>
      <input type="email" name="registerEmail" placeholder="Email address">
      <label for="registerPassword">Password</label>
      <input type="password" name="registerPassword" placeholder="Password">
      <label for="registerPasswordConfirm">Confirm your password</label>
      <input type="password" name="registerPasswordConfirm" placeholder="Password">
      <label for="registerCompany">Company name</label>
      <input type="text" name="registerCompany" placeholder="Company">
      <input type="submit" class="register-btn" value="Register">
    </form>
    <hr>
    <ul>
    	<li><button type="button" class="login-google"><i class="fa fa-google"></i> Sign in with Google</button></li>
    	<li><button type="button" class="login-microsoft"><i class="fa fa-windows"></i> Sign in with Microsoft</button></li>
    </ul>
    <p>Already have an account? <a href="{{route 'login'}}">Return to the login page.</a></p>
  </div>
</template>

<template name="PermissionDenied">
	<h1>Permission denied</h1>
	<p>Sorry, you don't have permission to see this page.</p>
</template>

<template name="SignOut">
	<a class="sign-out" href="/" id="signOut">Log Out</a>
</template>
```

**Comment by stocksp** [comment]
change your template name to 'login' (lowercase)

**Comment by teknetia** [comment]
I had it that way originally and it still failed, but let me try it again anyway
to be sure. That doesn't explain why / fails though?

On Sun, Aug 2, 2015 at 13:12, kadirahq/flow-router
<reply@reply.github.com>
wrote:
change your template name to 'login' (lowercase)

—
Reply to this email directly or view it on GitHub
[https://github.com/kadirahq/flow-router/issues/244#issuecomment-126984874] .[https://github.com/notifications/beacon/AHmf-bj2_oodjPXII6a06FsfSnLl0rosks5ojYIXgaJpZM4FkFLt.gif]

**Comment by stocksp** [comment]
I was just responding to the error message you posted.

**Comment by arunoda** [comment]
I would love to see a repo with this issue. That's really help me to dig
into this.

**Comment by teknetia** [comment]
I can give you read only access temporarily to it easily enough, it is a private repo. Will do it now for you and push my latest files up. It will be on branch feature/login.

**Comment by arunoda** [comment]
You are using `arillo:flow-router-helpers` package. It's not yet updated for the new flow-router. So, now you've two flow-router version in your app. That's the issue.

**Comment by teknetia** [comment]
Interesting! I forgot I even had the package. I have removed it but I still see issues. Unsure if it is related to FlowRouter now or something else entirely. Possibly it is related to Blaze?

The error is about route. As below

```
Exception in defer callback: Error: No such function: route
```
<img width="1697" alt="screen shot 2015-08-03 at 08 08 42" src="https://cloud.githubusercontent.com/assets/7970809/9028270/e1565d84-39b6-11e5-8906-a69ba2edda82.png">

**Comment by teknetia** [comment]
Interestingly going to / logs the message from the route, but doesn't render the template (I'd expect the footer at least to show up).
