### ISSUE TITLE
SSR and accounts

### ISSUE THREAD

**Issue by randomnerd** [kadirahq/flow-router#246]
Hi there!

How does SSR handle accounts logic? I always get this warning when reloading a page while logged in:
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting.
Obviously, SSR sends page in state where user is not yet logged in, how can we fix that?

Thanks!

**Comment by arunoda** [comment]
SSR for loggedIn users is on the way.

**Comment by devlesedi** [comment]
Is there a package we could use in the meantime for handling accounts? Im currently experimenting with *kadira:flow-router-ssr* and *kadira:react-layout*.

PS: Awesome stuff by the way :+1:

**Comment by arunoda** [comment]
Try the latest version, it has auth support enabled. Now you `Meteor.user()` is available on the server side. I forgot to update this thread.

**Comment by devlesedi** [comment]
Oh thanks.

**Comment by bmanturner** [comment]
How would you recommend using `Meteor.loggingIn()`?

Should I set a `isClient` state in `componentDidMount()` for use in `getMeteorData()`?

**Comment by arunoda** [comment]
If you are using it inside `componentDidMount` you don't need any isClient checks. But, I am quite not sure, `Meteor.loggingIn()` should work on the server too. It should be false always. If not, we need to fix it.

**Comment by bmanturner** [comment]
[Unfortunately it's client-only as of now](http://docs.meteor.com/#/full/meteor_loggingin)

You've responded to this issue once before, but `Meteor.loggingIn()` does not default to false on server: https://github.com/kadirahq/flow-router/issues/312

**Comment by arunoda** [comment]
Yep. Seems like we need to add it on the server as well.

**Comment by arunoda** [comment]
Added `Meteor. loggingIn()` to the server side. Will be released shortly.
