### ISSUE TITLE
[Question] Meteor.user() availability inside route action?

### ISSUE THREAD

**Issue by voidale** [kadirahq/flow-router#248]
Hi Arunoda,

I wanted to ask you about the best practice about the following it's a little bit tricky:
I'm keeping a current selected profile inside `Meteor.user().profile.currentProfile` and when the user comes to my app I want to redirect him to the page with that profile.

* those routes are always with a user logged in, But Meteor.user() can be unavailable what if it's in the middle of the loggingIn. The router shouldn't wait for anything isn't that correct? 
* I don't want to use fast-render to get Meteor.user() availability how about an alternative? :)

````
FlowRouter.route('/', {
  name: 'home',
  action: function(params, queryParams) {
    // Problem
    var user = Meteor.user();
    FlowRouter.go('profile/'+user.profile.currentProfile+'/content'); 
  }
});


FlowRouter.route('/profile/:profileId/content', {
  name: 'content',
  action: function(params, queryParams) {
    // Inside that template I use the FlowRouter.getParam to subscribe to the right profile
    BlazeLayout.render('layout', {main: "content"});
  }
});
````

**Comment by arunoda** [comment]
Check this article on how to deal with auth logic: https://kadira.io/academy/meteor-routing-guide/content/implementing-auth-logic-and-permissions

**Comment by voidale** [comment]
@arunoda Yeah I have it's great guide, But it's not about auth I already use it, I just need access to Meteor.user() object inside the route to do a check where to send the user to it can't be static route it's a dynamic one. 

So basiclly it's not possible on the route and you want to say I have to send `FlowRouter.route('/'` route and inside the template wait for the meteor.user() and based on that redirect to the right route? Can't we figure out a way to do that on the router? Or it goes against on how it should work.

Thanks

**Comment by arunoda** [comment]
Nope. We can't do it on the Router.
We don't have the data on the router level.

**Comment by massimosgrelli** [comment]
Hey @voidale I went through this old post and I had the same problem a couple of days ago, while moving out from IronRouter. One way I found to solve this is to use a simple server side method and retrieve current user record:

```
Meteor.methods({
  getMyUserRecord : function() {
    var userRec = {};
    if (Meteor.userId()) {
      userRec = Meteor.user();
    }
    return userRec;
  }
});
```


@arunoda, do you think it's a good way to solve it?

**Comment by voidale** [comment]
@massimosgrelli the solution for this is to move logic to the templates don't use userId on the router level
