### ISSUE TITLE
route not found, is this is flow router?

### ISSUE THREAD

**Issue by richpowell** [kadirahq/flow-router#249]
Oops, looks like there's no route on the client or the server for url: "http://localhost:3000/tables."

Im getting this immediately under my data, the data populates just fine based on flowrouter and blaze-layout... Is this a flow router error? Or possibly one of my packages in the app depends on iron router... I swear ive seen this before in iron router.

**Comment by arunoda** [comment]
That's because on of your package depends on IR.

**Comment by richpowell** [comment]
I wish there was a command line tool that would output all the dependencies for each package.. Or can you already do this somehow?
thanks arunoda!
