### ISSUE TITLE
Feature request: Route group name and function to check group membership

### ISSUE THREAD

**Issue by ShockiTV** [kadirahq/flow-router#250]
Hi,

I think it would be nice to have a way to check if current route is part of a group.
And name group property would be nice

My current usecase - dynamically created nested category structure.
/category1/category1-3/category1-3-2
/category3/category3-2/category3-2-3/category3-2-3-4/category3-2-3-4-1

I have category1-category15 as a members of CategoryGroup and doing same subscriptions for them etc. Sad that action is mandatory itself, as I just repeat these for every route.
So current check if it is CategoryRoute consist of switch with 15 different values without break and than code for all of them.

In whole site header I am watching in onCreated autorun for path changes and to get info if it is category running again this ugly switch check etc... Same with products in these categories...
Or I can set it in trigger as separate variable indicator, but I dont want custom variables on router level.

Function to check if current route is part of group would be very nice.

Implementation: I can think of an array and by passing every named group, current group name would be pushed to that array. Than just public functions which will return that array, or return boolean if function parameter (string representing group name for which we are checking) is part of that array.

**Comment by arunoda** [comment]
Okay. `action` is not mandatory. You can leave it blank.
I'm okay to set the group info on the route as well. An array would be great.

But, I'm quite not sure about a public function for that at this moment.
Could you send me a PR for this.

**Comment by arunoda** [comment]
Looking forward for the PR.
