### ISSUE TITLE
[FR] Allow trigger functions to receive additional arguments

### ISSUE THREAD

**Issue by serkandurusoy** [kadirahq/flow-router#251]
Currently, the only two arguments that a trigger can receive are `context` and `redirect` but I find myself needing to reuse some trigger functions that are very similar, except for small changes, which would be very easy to apply if it were possible to pass in additional arguments to the function.

**Comment by arunoda** [comment]
I think you can use currying or JS bind function for this purpose.

#### Currying

~~~js
function buildTrigger(prefix) {
  return function (context, redirect) {
    var path = prefix + context.path;
    redirect(redirect);
  };
}

FlowRouter.route("/old-route", {
  triggersEnter: [buildTrigger("/new/url")]
});

FlowRouter.route("/very-old-route", {
  triggersEnter: [buildTrigger("http://myapp.io")]
});
~~~

####.bind

~~~js
function redirectTrigger(prefix, context, redirect) {
  var path = prefix + context.path;
  redirect(redirect);
}

FlowRouter.route("/old-route", {
  triggersEnter: [redirectTrigger.bind(null, '/new/url')]
});

FlowRouter.route("/very-old-route", {
  triggersEnter: [redirectTrigger.bind(null, 'http://myapp.io')]
});
~~~

**Comment by serkandurusoy** [comment]
Hm, I keep forgetting that this is indeed javascript. Or perhaps I need a little rest :)

Thanks!

**Comment by arunoda** [comment]
:)
