### ISSUE TITLE
Advice to create "Breadcrumb" pacake for Flow Router?

### ISSUE THREAD

**Issue by thearabbit** [kadirahq/flow-router#253]
I would like create `breadcrumb` package for `Flow Router`.
Please help me.

**Comment by thearabbit** [comment]
Now I tried to create the `flow-router-breadcrumb` package for `flow-router`
[Atmosphere](https://atmospherejs.com/theara/flow-router-breadcrumb)
[GitHub](https://github.com/thearabbit/flow-router-breadcrumb)
Please correct, if it have the problem.

**Comment by arunoda** [comment]
I think this is great. I'll work a new guide to allow developers build addons like this for flow-router very easily. Anyway, this is a great start.

Share this on Atmosphere and Meteor Forums. I hope you'll get more feedback.

**Comment by thearabbit** [comment]
Very thanks, I am very happy to learn from you.
(Sorry my English not good).

**Comment by arunoda** [comment]
Don't worry about english.
