### ISSUE TITLE
IE9 support

### ISSUE THREAD

**Issue by tomwasd** [kadirahq/flow-router#254]
Hi,

Prior to flow-router having IE9 support I hacked together my own solution with a patched page.js file.

I've tried my site with the latest version of flow router (with your patched version of page.js) but got 404  errors on every route except the home page. I haven't dug into page.js so I'm not entirely sure why.

I thought I'd share my patched version of page.js so you can see where it differs:

https://github.com/tomwasd/page.js

And also a fork of flow-router that takes a slightly different approach to IE9 support - it uses javascript to detect if the user's browser is IE9 or older. If so, it uses jQuery to load the history polyfill. The idea being you wouldn't unnecessarily load the history polyfill on other browsers but it would load automatically (without the need to add the tmeasday:html5-history-api package) in IE9 or older.

https://github.com/tomwasd/flow-router

There's probably a downsides to my approach that I haven't considered/realised yet!

Hopefully I'll get to the bottom of the issue myself but thought I'd post here in case anyone else is having issues of facing a similar battle.

I've also got IE8 working but the solution is far too horrible to share publicly at the moment. Needs some tweaking!

**Comment by arunoda** [comment]
That seems like a good solution. BTW: Could you send me sample test project and I am super excited to see where it goes wrong.

**Comment by arunoda** [comment]
Yep. I think there is an issue. Your page.js fork works pretty well.
We'll get that as well.

**Comment by arunoda** [comment]
Hi we released a new version with your fix to the page.js as well. Could you check that?
