### ISSUE TITLE
Feature request: FlowRouter.isRouteName(name)

### ISSUE THREAD

**Issue by steph643** [kadirahq/flow-router#255]
`FlowRouter.isRouteName(name)` would be reactively triggered whenever the value of `active route === name` changes. It would *not* be triggered when the route name changes to and from something different from `name` (like in [zimme:isActiveRoute](https://github.com/zimme/meteor-active-route#isactiveroute)).

**Comment by arunoda** [comment]
I think this is valuable, but this is not going to the core. For 3.0 we are not going to change current API.

So, I suggest you to create a package and publish to Atmosphere.

**Comment by steph643** [comment]
If you think this is valuable, please reopen it and label it as `distantFuture` :-) This way, others can find this issue easily and comment.
