### ISSUE TITLE
how Can i restore the browser state when using flow router with react?such as the scrollbar position?

### ISSUE THREAD

**Issue by yiluxin** [kadirahq/flow-router#258]
I used React+flowRouter to build a web application, Pages has different functions, I hope that the user jump between in the page, the page no Refresh, such as the position of the scrollbar

**Comment by arunoda** [comment]
Frankly, I'm not clear about the question. If this is a question related to how to write a Meteor app, I suggest you to post this on StackOverflow or Meteor Forums.

**Comment by arunoda** [comment]
Closing because I have not enough information.

**Comment by Primigenus** [comment]
@arunoda Our team (@jeroengijsman) is encountering this issue. Basically, after loading a new page with Flow Router and React, you want the page to scroll to the top (0, 0). They are having issues getting that working. Have you seen any progress in this area since August? What do you guys do with eg. Kadira etc?

**Comment by rozzzly** [comment]
`window.scrollTo(0, 0);`

 http://stackoverflow.com/questions/1144805/how-do-i-scroll-to-the-top-of-the-page-with-jquery


Use that in your `action` after `react`'s `render` function. You might need to wrap that in a `setTimeout(...)` if it's not working correctly.

**Comment by arunoda** [comment]
You can do this inside a trigger with a setTimeout.

**Comment by Primigenus** [comment]
Yeah, I proposed doing that but it feels like a hack. Was hoping you would have a better suggestion. :)

**Comment by arunoda** [comment]
@Primigenus this may help: https://github.com/okgrow/router-autoscroll

`window.scrollTo` is not a hack. That's what we do also.

**Comment by Primigenus** [comment]
@arunoda I meant the use of "`setTimeout` if it's not working correctly", not `scrollTo`. We already looked at autoscroll but it did not combine well with React.

**Comment by jeroengijsman** [comment]
We tried the autoscroll package but found out that the `scrollTop` on `triggers.enter` is to early. So what we did is still use the `triggers.exit` but run the `scrollTop` code in `componentDidUpdate()` of our Layout component instead of `triggers.enter`.
This way the scrollTop happens when the new component is loaded

**Comment by arunoda** [comment]
@Primigenus Here's how we do it for kadira.io 

Triggers:

```
Triggers = {
  // we need to keep two paths and we are interested 
  // we need to check the first path to do our validations
  _previousPaths: [null, null],
  jumpToPrevScrollPosition(context) {
    var path = context.path;
    var scrollPosition = 0;
    var prevPathInfo = this._previousPaths[0];
    if(prevPathInfo && prevPathInfo.path === context.path) {
      scrollPosition = prevPathInfo.scrollPosition;
    }
    
    if(scrollPosition === 0) {
      // scroll is right away since we don't need to wait for rendering
      $('body').animate({scrollTop: scrollPosition}, 0);
    } else {
      // now we need to wait a bit for react/meteor does rendering
      // We assume, there's subs-manager and we've previous page's data
      // here 10 seconds deley is a arbitary value with some testing.
      setTimeout(function () {
        $('body').animate({scrollTop: scrollPosition}, 0);
      }, 10);
    }
  },
  saveScrollPosition(context) {
    var pathInfo = {
      path: context.path,
      scrollPosition: $('body').scrollTop()
    };

    // add a new path and remove a one from the top
    this._previousPaths.push(pathInfo);
    this._previousPaths.shift();
  },
};

_.each(Triggers, function (value, key) {
  if(typeof value === 'function') {
    Triggers[key] = value.bind(Triggers);
  }
});
```

on router

```
FlowRouter.triggers.enter([Triggers.jumpToPrevScrollPosition]);
FlowRouter.triggers.exit([Triggers.saveScrollPosition]);
```

**Comment by jeroengijsman** [comment]
@arunoda we basically use the same code :) but we run the jumpToPrevScrollPosition in a `componentDidUpdate`
