### ISSUE TITLE
Can we get a AngularLayout package also?

### ISSUE THREAD

**Issue by timbrandin** [kadirahq/flow-router#259]
It's fine with it only working on the client right now, but it'd be nice to get SSR with Angular2 which is rumored to support this. Any thoughts?

**Comment by arunoda** [comment]
I'm open to that. Frankly, I've no experience in Angular :(

**Comment by timbrandin** [comment]
It's easy to get started with:
http://angular-meteor.com/tutorials/angular2/bootstrapping

I've come to the point I can run Sideburns with Angular support on the client, looking at how to use the System.import on the server, that's my roadblocker now. Checkout the PR I'm working on:
https://github.com/timbrandin/meteor-sideburns/pull/7

**Comment by timbrandin** [comment]
Investigating... Angular2 SSR https://angularu.com/VideoSession/2015sf/angular-2-server-rendering

**Comment by arunoda** [comment]
I think it's super awesome to have Angular Support. But, I'm quite not sure about it.
So, I'm gonna close it for now.
If you or someone need any help from me. Just ping me here.
