### ISSUE TITLE
context.oldRoute doesn't store params from oldRoute

### ISSUE THREAD

**Issue by jordangarside** [kadirahq/flow-router#260]
context.oldRoute._params.keys is always empty

If I want to know the old route from the current route and redirect back to it, I have no way to do that as is.

Right now I create a global triggersEnter and save the last route in a global on FlowRouter, but it would be nice to have at least the oldRoute real path to navigate back to.

**Comment by arunoda** [comment]
You should not go that far. Those are private variables. Only thing you can read from the route object is `name` and `object` fields.

Using a trigger seems like a good solution.

**Comment by jordangarside** [comment]
Got it, thanks!

**Comment by jordangarside** [comment]
Solution here for anyone who needs

```
// Store the lastRoutePath in the router
var lastRoutePath;
FlowRouter.triggers.enter([
  function(context){
    newRoutePath = context.path;
    FlowRouter.lastRoutePath = lastRoutePath;
    lastRoutePath  = newRoutePath;
  }
]);
```
