### ISSUE TITLE
flow-router-ssr degrade overall meteor performance

### ISSUE THREAD

**Issue by meteor-software** [kadirahq/flow-router#267]
Hi,
I've made simple react meteor app using flow router, react-layout and picker. 
For simplicity there are no subscriptions at all - nothing fancy.
I have simple react page on path / and simple server side route on path /server/route

My tests (with apache benchmark) shows that flow-router-ssr degrade overall meteor performance. 
It's more then 5 time slower compared to no-ssr version of flow router. 

It's obvious that client side routes with ssr will be slower. 
But why server side routes are affected?

Look at Apache benchmark results:

-----------------------------------------
FLOW ROUTER (NO SSR) REACT PAGE LOADING TIME TESTED WITH APACHE BENCHMARK

root@tardis:/home/hex# ab -n 10000 -c150 http://localhost:3000/
This is ApacheBench, Version 2.3 <$Revision: 1638069 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests

Server Software:        
Server Hostname:        localhost
Server Port:            3000

Document Path:          /
Document Length:        6735 bytes

Concurrency Level:      150
Time taken for tests:   4.955 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      68730000 bytes
HTML transferred:       67350000 bytes
Requests per second:    2018.27 [#/sec] (mean)
Time per request:       74.321 [ms] (mean)
Time per request:       0.495 [ms] (mean, across all concurrent requests)
Transfer rate:          13546.47 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.7      0       9
Processing:    23   74  13.7     69     172
Waiting:       17   42  24.6     31     133
Total:         23   74  13.7     70     176

Percentage of the requests served within a certain time (ms)
  50%     70
  66%     74
  75%     77
  80%     80
  90%     92
  95%    107
  98%    111
  99%    113
 100%    176 (longest request)

-----------------------------------------
FLOW ROUTER (SSR) REACT PAGE LOADING TIME TESTED WITH APACHE BENCHMARK

root@tardis:/home/hex# ab -n 10000 -c150 http://localhost:3000/
This is ApacheBench, Version 2.3 <$Revision: 1638069 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests

Server Software:        
Server Hostname:        localhost
Server Port:            3000

Document Path:          /
Document Length:        9299 bytes

Concurrency Level:      150
Time taken for tests:   31.942 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      94370000 bytes
HTML transferred:       92990000 bytes
Requests per second:    313.07 [#/sec] (mean)
Time per request:       479.126 [ms] (mean)
Time per request:       3.194 [ms] (mean, across all concurrent requests)
Transfer rate:          2885.20 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.7      0       8
Processing:   238  476  60.6    476     728
Waiting:      237  439  60.0    436     690
Total:        244  476  60.5    476     732

Percentage of the requests served within a certain time (ms)
  50%    476
  66%    500
  75%    516
  80%    528
  90%    556
  95%    577
  98%    604
  99%    616
 100%    732 (longest request)

-----------------------------------------
FLOW ROUTER (NO SSR) PICKER SERVER ROUTE LOADING TIME TESTED WITH APACHE BENCHMARK

root@tardis:/home/hex# ab -n 10000 -c150 http://localhost:3000/server/route/
This is ApacheBench, Version 2.3 <$Revision: 1638069 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests

Server Software:        
Server Hostname:        localhost
Server Port:            3000

Document Path:          /server/route/
Document Length:        22 bytes

Concurrency Level:      150
Time taken for tests:   5.289 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      1200000 bytes
HTML transferred:       220000 bytes
Requests per second:    1890.60 [#/sec] (mean)
Time per request:       79.340 [ms] (mean)
Time per request:       0.529 [ms] (mean, across all concurrent requests)
Transfer rate:          221.56 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.7      0       8
Processing:    25   79  16.8     80     128
Waiting:       19   72  20.5     74     128
Total:         25   79  16.7     80     128

Percentage of the requests served within a certain time (ms)
  50%     80
  66%     84
  75%     89
  80%     92
  90%    102
  95%    107
  98%    112
  99%    117
 100%    128 (longest request)

-----------------------------------------
FLOW ROUTER (SSR) PICKER SERVER ROUTE LOADING TIME TESTED WITH APACHE BENCHMARK

root@tardis:/home/hex# ab -n 10000 -c150 http://localhost:3000/server/route/
This is ApacheBench, Version 2.3 <$Revision: 1638069 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests

Server Software:        
Server Hostname:        localhost
Server Port:            3000

Document Path:          /server/route/
Document Length:        22 bytes

Concurrency Level:      150
Time taken for tests:   29.206 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      1200000 bytes
HTML transferred:       220000 bytes
Requests per second:    342.39 [#/sec] (mean)
Time per request:       438.094 [ms] (mean)
Time per request:       2.921 [ms] (mean, across all concurrent requests)
Transfer rate:          40.12 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.6      0       7
Processing:   252  436  61.5    431     784
Waiting:      213  398  61.4    393     744
Total:        252  436  61.5    431     788

Percentage of the requests served within a certain time (ms)
  50%    431
  66%    456
  75%    475
  80%    484
  90%    516
  95%    540
  98%    572
  99%    596
 100%    788 (longest request)

**Comment by arunoda** [comment]
This is not a secret. React rendering takes a lot of CPU power. 
We are using a cached layer to optimize it.
We also working on a fast-render only version to get rid  of this.

I'll do a complete post about these soon.

**Comment by meteor-software** [comment]
It's true that react rendering takes a lot of CPU power. 

But the point is: why It's affecting server side routes without react?

**Comment by arunoda** [comment]
If you are getting it for non react code, I'm quite not sure. 
We don't have a way to support it for non-react yet.

In either case, send me sample repo with this issue. Then we can assess.
Anyway, we are very early for performance improvements yet. 
But, I'd like to take a look at it.

**Comment by meteor-software** [comment]
My tests using kadira:flow-router-ssr from atmosphere and results was poor.

Using current version from github It's fast again with ssr.

The same app score 1650req/s with react and 1964req/s with picker route

I'm really sorry for disturbing You. Great job!

**Comment by niallobrien** [comment]
Should the newer version be published to Atmosphere?

**Comment by arunoda** [comment]
Yes it it. Current version is in atmosphere.
