### ISSUE TITLE
Setting individual query params

### ISSUE THREAD

**Issue by proehlen** [kadirahq/flow-router#268]
I'm going to test it to find the answer in a second, but it might be something that could be documented better which is why I'm raising the issue:

There's a method to retrieve one, individual query parameter `FlowRouter.getQueryParam(queryStringKey);` - where the method name is singular.

But am I right in saying there is there no way to set an individual query parameter?  The method name to set is plural: `setQueryParams(newQueryParams)`.  

Just seems a bit odd that I can test for an individual query parameter but then if I want to change it in isolation, I have to first use a second method `FlowRouter.current()` to obtain the queryParams property, change the individual property / query parameter in the variable and then use set to update all of them?

**Comment by arunoda** [comment]
Actually, you `setQueryParams` does not require you to pass all the query params. You can use it for one param as well.

* Let's say the URL is: `/?a=10&b=20`
* You need to change a into 100
* You can do this
* `FlowRouter.setQueryParams({a: 100})`

**Comment by proehlen** [comment]
Ok thank you
