### ISSUE TITLE
standardize path / pathDef in route code

### ISSUE THREAD

**Issue by alanning** [kadirahq/flow-router#272]
It's sometimes useful to access the pathDef for a route, such as when logging which route is getting executed.  In the code, there are two different ways that the path definition is referenced:

1. path - https://github.com/kadirahq/flow-router/blob/master/client/route.js#L5
2. pathDef - https://github.com/kadirahq/flow-router/blob/master/client/router.js#L189

Would you be open to a PR which standardized on **pathDef**?

It would help make things like this more clear:

```js
FlowRouter.current().path         // => /apps/this-is-my-app?show=yes&color=red
FlowRouter.current().route.path   // => /apps/:appId
```

**Comment by arunoda** [comment]
The places you mentioned in the same place right? 2nd one using the 1st one.
Anyway, I get it.

In the route, you want to mention it as `pathDef`. Yep, which is sounds good to me.
But, I don't wanna break any apps. So, we need to keep the path as it is.
We can remove `path` in 3.0
