### ISSUE TITLE
make FlowRouter.go accept route names

### ISSUE THREAD

**Issue by satyavh** [kadirahq/flow-router#275]
I think it would be a good idea if `FlowRouter.go` could accept route names as well as route paths. 
Using route names makes sure your code doesn't break when you change the route path.

**Comment by arunoda** [comment]
Yes we support it from very early releases.
Have you find any issues with that?

**Comment by joefru** [comment]
Suddenly stopped working for root ("/")

**Comment by joefru** [comment]
@satyavh Make sure your route is defined before you use it. Pay specific attention to File Load Order in Meteor: http://docs.meteor.com/#/full/structuringyourapp

**Comment by arunoda** [comment]
This is perfectly working. If you any issues, please post with a sample repo.

**Comment by NitroBAY** [comment]
you should add it on the doc (I read the github doc and I never saw that), that's a pity because I never appreciated put url instead of route name, it's really not proper as the name are temporary.

**Comment by mroftalp** [comment]
+1 for making the doc for this. Thank you!
