### ISSUE TITLE
triggersExit not firing?

### ISSUE THREAD

**Issue by themeteorchef** [kadirahq/flow-router#277]
I'm playing with triggers at the moment and for some reason, I cannot get the `triggersExit` method to fire. `triggersEnter` and `action` behave as expected, but when moving to a new route, `triggersExit` is not firing. For example:

```
FlowRouter.route( '/', {
  triggersEnter: [ function(){
    console.log( "ENTER!" );
  }],
  action: function( params ) {
    console.log( "ACTION!" );
    BlazeLayout.render( 'applicationLayout', { main: 'index' } );
  },
  triggersExit: [ function(){
    console.log( "EXIT!" );
  }]
});
```

When leaving the `/` route, I would expect to see `EXIT!` printed to the console. Instead, I see nothing, only getting `ENTER!` logged when the route loads and then `ACTION!` soon after. 

I've made a few changes to the syntax I'm using, for example, instead of passing a single function in an array, just calling it directly. Here's a quick preview of what I'm experiencing alongside my code:

![Exit example](http://cl.ly/image/2y1d1W381C3L/triggers-exit-error.gif)

Any thoughts? I've attempted a few variations and double checked the documentation. Note: this also applies to groups and global triggers as well.

Any help would be appreciated :)

**Comment by themeteorchef** [comment]
Quick update on this. It looks like the `triggersExit` _does_ fire if I call a route programatically using something like `FlowRouter.go( "/example" );` or inside of another trigger `redirect( "/example" );`.

Because this works, it appears to be intentional/by design. Is that correct?

**Comment by arunoda** [comment]
Yes it is. You need to navigate app using `<a />` tags, `FlowRouter.go` or using `redirect`. Otherwise, if you hit the page directly there is no history data in the browser.
