### ISSUE TITLE
Is there a hook to cancel exiting a route?

### ISSUE THREAD

**Issue by Zodiase** [kadirahq/flow-router#279]
Similar to `window.onbeforeunload`, a hook to decide if it's ok to exit the current route.

**Comment by arunoda** [comment]
You can use exit triggers for that. See: https://github.com/kadirahq/flow-router#triggers

**Comment by Zodiase** [comment]
It says "perform tasks before enter into a route and after **exit** from a route."

Doesn't that mean whatever I do in the exit triggers, I'm already out of the route, even if I could try to enter it again?

My question is asking if there is a hook *****before***** exiting a route and in that route I could somehow **prevent exiting the route**.

**Comment by arunoda** [comment]
Actually, that text should be **before**.

**Comment by Zodiase** [comment]
Then which part of that doc describes how to stop exiting the route?

**Comment by arunoda** [comment]
Check this: https://github.com/kadirahq/flow-router/pull/172

**Comment by Zodiase** [comment]
Does that approach have any side-effect such as triggering entering event handlers (since this is not entering or re-entering)?
