### ISSUE TITLE
triggersEnterGroup and triggersExitGroup

### ISSUE THREAD

**Issue by Sivli-Embir** [kadirahq/flow-router#282]
We need to add group names (or a reference) into an array and put it inside the route objects. Then it helps to build logics like below. 

> Original Issue is modified and make this as a feature for 3.0. Here's the original issue.
### Original Title: triggersEnterGroup and triggersExitGroup

TL;DR: Would it be possible to get triggers for when you enter and exit a group of routes? 

See the following:

``` js
var userRoutes = FlowRouter.group({
  triggersEnter: [
    function(context, redirect) {
      if (!context.path === '/groups' && !Session.get('currentGroup')) {
        redirect('/groups');
      }
    }
  ],
  triggersExit: [
    function(context, redirect) {
      Session.set('currentGroup', undefined);
    }
  ]
});

userRoutes.route('/') //a route that needs a current group ( '/:group' would not be ideal)
userRoutes.route('/groups') //a route to select a group
```

The goal is to set up a Session for when a user is in a group of routes and to unset it when they leave. How this works now is the Session gets unset when it exists the '/group' route (but after it enters the '/' route? there may be bug there)

So ideally I could use a new type of enter and exit trigger for the group scope.

EDIT: This is mostly academic, I already have an alternative solution for my use case. That said this would be a cleaner solution.

**Comment by arunoda** [comment]
I get it. But here group routes triggers simply goes into the individual routes it creates. Technically, triggers are not aware of the group.

What you can do is to setup a global trigger and check your logic with the path. We are also planning to add an array of groups to the route. So, things will be simplify then.
But we are not there yet!

**Comment by Kestanous** [comment]
Sounds good. A global `is route in group` check would definitely do the trick. That said it would be wasteful to run that for every route. Maybe putting it on the triggersExit in the group? 

Regardless an array of group routes would close this issue. Take your time, and just close this when you are there. Thanks!
