### ISSUE TITLE
Weird behavior with content-less routes

### ISSUE THREAD

**Issue by servermeta** [kadirahq/flow-router#283]
Hello everybody!

Great package!

I noticed a weird behavior. I have a content-less route:

```
FlowRouter.route('/', {
    name: 'home',
    action: function() {
        BlazeLayout.render('mainLayout');
    }
});

```

Anyhow when I try

```
FlowRouter.go('home');
```

It returns errors about content being null unless I edit my original route:

```
        BlazeLayout.render('mainLayout', {content: ''});
```

I blame this on javascript for being so forgiving in the data it let pass through. Damn I never thought I would miss strong typed languages.

**Comment by arunoda** [comment]
Can I get the full error?
Better if I could see a sample repo with this case.

**Comment by servermeta** [comment]
Hello Professor Arunoda!

I didn't thought you would have replied to me in person or I would have written a better report. Thank you again for your effort.

So if in chrome console I type: 

```
FlowRouter.go('home')
undefined
```

If I put it inside some helper it happens this:

```
Exception from Tracker recompute function:
debug.js:41 TypeError: Cannot read property 'content' of undefined
    at layout.js:59
    at Function._.each._.forEach (underscore.js:113)
    at Object._updateRegions (layout.js:58)
    at Object._render (layout.js:122)
    at layout.js:21
    at Object.Meteor.startup (startup_client.js:63)
    at Object.render (layout.js:12)
    at action [as _action] (routes.es6:4)
    at Route.callAction (kadira_flow-router.js?27ee48c1f8aeb66e86562d593ab02648ea96fbbb:2271)
    at kadira_flow-router.js?27ee48c1f8aeb66e86562d593ab02648ea96fbbb:2015
```

**Comment by servermeta** [comment]
Here's the repo:

https://github.com/servermeta/Motter

it's very possible that some other package is creating issues? Unfortunately I don't have time right now to check, if you want I can dig deeper in the weekend.

**Comment by arunoda** [comment]
Okay. got it. 
It was an issue with BlazeLayout. Update it to the latest version (2.0.1) and this problem should be gone.
