### ISSUE TITLE
Could I use " this.register('myPost', Meteor.subscribe('blogPost', params.postId));" in Template Level?

### ISSUE THREAD

**Issue by thearabbit** [kadirahq/flow-router#284]
Could I use ` this.register('myPost', Meteor.subscribe('blogPost', params.postId));` in template level:
```js
Template.myTpl.onCreated(function (){
    this.register('myPost', Meteor.subscribe('blogPost', params.postId));
})

Template.myTpl.onRendered(function (){
    this.register('myPost', Meteor.subscribe('blogPost', params.postId));
})
```
And then I check `isSubReady(...)` on `Template.html`

**Comment by arunoda** [comment]
Nope you can't.
You can read more about this here: https://kadira.io/academy/meteor-routing-guide/content/subscriptions-and-data-management

**Comment by thearabbit** [comment]
Thanks, for your reply.
But now I don't clear about `pub/sub` (When)?
For example I use `aldeed:tabular` and `Flow Router`. I my flow router I use `sub`, but it have problem with large data (more then 10000 records).

**Comment by arunoda** [comment]
You should not try to send a larger set of data. I hope rest of your question not suites here. Try Meteor Forums.
