### ISSUE TITLE
[Question] How to do redirect in special case?

### ISSUE THREAD

**Issue by Shalimov** [kadirahq/flow-router#285]
I need to implement following scenario:
My app has `start point` as address -> ```FlowRouter.route('/', ...)```
If user visits start point I need to provide following actions:
- if user logged in and his profile has special attribute I need redirect him to `Profile Page`
- if user logged in but his profile does not have special attribute I need redirect him to 'Edit Profile Page'
- if user does not logged in I need redirect him to 'Sign In page'

Could you recommend me the best way how to solve this problem by using FlowRouter?

**Comment by arunoda** [comment]
You need to do this in the layout/template level. See this: [Implementing Meteor Auth Logic and Permissions](https://kadira.io/academy/meteor-routing-guide/content/implementing-auth-logic-and-permissions)
