### ISSUE TITLE
Subdomains & Second level urls. 

### ISSUE THREAD

**Issue by rwatts3** [kadirahq/flow-router#287]
Greetings.  

I am curious if flow router offers a solution for Subdomains and second level navigation.  

For the Subdomains.  I would like to take multiple clients one application.  And restrict the data bases in the clients name so client.myapp.io would contain the data that's assigned to that client. 

And for Subdomains is it possible to build a menu system such as /blog/posts , and blog / categories but dynamically.  Rather than writing the route directly   I have a pages package I'm using with Orion, and if a user creates a page as a child of the other page the route does not handle properly.

**Comment by arunoda** [comment]
I am not sure about how to fix it, but I assume you can fix this by adding routes dynamically or adding a pattern for that page base layout.
Check this a bit: https://kadira.io/academy/meteor-routing-guide/content/introduction-to-flow-router#defining-routes

We won't have any direct ways to deal with subdomains.

**Comment by proehlen** [comment]
I found this thread after searching for subdomain support in flowrouter.   I hacked together the below solution which I'm sharing in case it's useful and also so arunoda can comment if he sees any major problem with it.

It works on a basic level but just be warned that your "teamId" or whatever value you are using your subdomains for won't be available as flowrouter parameters.  In the example below I can access it only as template data/parameters.

**Route group 'team' with 'teamId' expected in path or in subdomain**
```
var teamRoutes = FlowRouter.group({
  prefix: '/team/:teamId?',
  name: 'team'
});

teamRoutes.route('/:tab', {
  action: function(params) {
    BlazeLayout.render(
      "layout", {
        "menu": "menuTeam",
        "content": "team",
        "teamId": params.teamId ? params.teamId : getSubdomain(),
        "tab": params.tab
      }
    );
  }
});

function getSubdomain(){
  //TODO add checking here so that there actually is a subdomain to be fetched
  // or otherwise it will return main domain if none provided.
  return location.hostname.split('.')[0];
}
```

**'teamId' available in Blaze template as template parameter/data:**
```
<template name="members">
    <p>Team {{teamId}} members page coming soon...</p>
</template>
```

**Working with regular url:**
![image](https://cloud.githubusercontent.com/assets/8384068/13265115/cc4e4c4c-daa3-11e5-9cc7-e43211539bf7.png)

**Working with subdomain:**
![image](https://cloud.githubusercontent.com/assets/8384068/13265097/b471a286-daa3-11e5-82c3-14fca7a72427.png)
