### ISSUE TITLE
Flowrouter interfering with server routes (e.g. pointing to uploaded files)

### ISSUE THREAD

**Issue by tomitrescak** [kadirahq/flow-router#288]
Hi

I am serving my uploaded files from the /upload folder as such `/upload/folder/file`.

The problem is that Flowrouter keeps interfering and does not allow me to click on the link pointing to the image stored at that location and is showing me the notExists route. My current workaround is that I set `target="_blank"` in the anchor, which displays the image in the new window. 

Is there any way to disable flow router for a specific path?

Thanks

**Comment by arunoda** [comment]
Check this: https://github.com/kadirahq/flow-router/issues/235#issuecomment-131990201
