### ISSUE TITLE
Create a Gitter

### ISSUE THREAD

**Issue by rozzzly** [kadirahq/flow-router#289]
Heya Guys!

Love this package, but I'm often finding that I have questions concerning it which I can only—if at all—find solutions for after digging around in the github issue tracker/waffle.io, or wherever else google brings me.

Sometimes you just want to ask a quick question/get pointed in the right direction, ya know? 

I don't know if you're familiar with [gitter.im](https://gitter.im). Please go check it out. TL;DR slack-esque chat rooms for github repositories; users chat with their github accounts. A lot of popular repos are using it, even `Meteor`! I'm requesting that one be made for `FlowRouter`.

I'd love to contribute to `FlowRouter` because (IMHO) it's a very important package for the community and I want to add support for the—specifically in regards to SSR—functionality that I need, that `FlowRouter` needs. I think [gitter](https://gitter.im) would be the simplest way to discuss how we might go about this. Github Issues/waffle.io are great for tracking specific bugs but are not necessarily conducive to the quicker back-and-forth _conversational_ style discussions best for planning something complex. 

Even if you plan on never using it, it would take less than a minute to create; I'm certain many other developers such as myself would appreciate the resource.

Thanks for your time and consideration, look forward to talking with you guys soon

Warm Regards,
@rozzzly

**Comment by arunoda** [comment]
I don't like chat systems for support for open source projects. All the communication should be available to the pubic. Otherwise, we are wasting a lot of resources and time.

If you need to ask questions related to FlowRouter, you can come here :) Otherwise, Meteor Forums is a good place.

**Comment by rozzzly** [comment]
:unamused:

**Comment by arunoda** [comment]
Sorry!
