### ISSUE TITLE
TriggersExit not fire when manually changing route

### ISSUE THREAD

**Issue by lookingcloudy** [kadirahq/flow-router#291]
The TriggersExit does not fire if the user manually changes the route

**Comment by arunoda** [comment]
Hope this is related to this: https://github.com/kadirahq/flow-router/issues/277

**Comment by arunoda** [comment]
Reopen it it's not. Just tell us your case as well.

**Comment by lookingcloudy** [comment]
Ok - thanks.  It is the same issue.  Just a suggestion, you may want to make the clarification in the docs.

**Comment by arunoda** [comment]
Yeah! That's a good point.
