### ISSUE TITLE
Request: Allow layouts for notFoundPage

### ISSUE THREAD

**Issue by ciwolsey** [kadirahq/flow-router#296]
Currently you can't do something like this in your action for your not found page:

```
FlowRouter.notFound = {
  action: function() {
    BlazeLayout.render('navBarLayout', { main: "notFoundPage" });
  }
};
```

Layout in this example is ignored. There are some situations where you don't want to remove the current layout from the DOM and display the 404 in a region.

**Comment by niallobrien** [comment]
Ah, I was just solving this issue myself - what I did was write a merge function to merge a `layout` object with `{main: 'notFoundPage'}`, so I always call that function within the `render()` method. To make this `merge` function a little more readable, I called it `layout` so I read it as `layout(params)` if that makes sense?

Place this at the bottom of your `router.js` file and adjust the `layoutObj` to reflect your layout.
```
// Layout helper
function layout(source) {
  var layoutObj = {
    nav: 'nav',
    footer: 'footer',
    main: 'main'
  }

  for (var property in source) {
    if ( source.hasOwnProperty(property) ) {
      var sourceProperty = source[ property ]
      if ( typeof sourceProperty === 'object' ) {
        layoutObj[ property ] = util.merge( layoutObj[ property ], sourceProperty )
        continue
      }
      layoutObj[ property ] = sourceProperty
    }
  }
  for (var a = 2, l = arguments.length a < l a++) {
    layoutObj(arguments[a])
  }
  return layoutObj
}
```

So, to use it with your example you can do
```
FlowRouter.notFound = {
  action: function() {
    BlazeLayout.render('navBarLayout', layout({main: 'pageNotFound'}))
  }
}
```

**Comment by niallobrien** [comment]
In this instance, I created a `router` directory and placed `router.js` and `router-helpers.js` in there.

```
// router-helpers.js
// Router & Layout helper(s)
Meteor.app = {
  layout: function(source) {
    var layoutObj = {
      nav: 'nav',
      footer: 'footer',
      main: 'main'
    }

      if (typeof source == 'undefined' || null) {
      return layoutObj
    }

    for (var property in source) {
      if ( source.hasOwnProperty(property) ) {
        var sourceProperty = source[ property ]
        if ( typeof sourceProperty === 'object' ) {
          layoutObj[ property ] = util.merge( layoutObj[ property ], sourceProperty )
          continue
        }
        layoutObj[ property ] = sourceProperty
      }
    }
    for (var a = 2, l = arguments.length; a < l; a++) {
      layoutObj(arguments[a])
    }
    return layoutObj
  }
}
```

Then in `router.js` you can call it as `BlazeLayout.render('navBarLayout', Meteor.app.layout({main: 'pageNotFound'}))` which is a little more verbose, but a workable solution until Blaze Layout has such a feature. I hope that helps.

**Comment by ciwolsey** [comment]
Thanks for the effort Niall! I'll give this a try when I have time. I guess it will do until it's possible without it :)

**Comment by niallobrien** [comment]
No problem @ciwolsey

**Comment by arunoda** [comment]
I close this because this is a question. Feel free to discuss.

**Comment by niallobrien** [comment]
Is this something Blaze Layout should include @arunoda? Having to specify the layout of the entire app for every route is quite verbose otherwise. Just a thought.
