### ISSUE TITLE
Statically served html pages

### ISSUE THREAD

**Issue by jjman505** [kadirahq/flow-router#297]
I'm serving a static page at `/public/index.html` When I navigate to `/index.html` it displays fine.
I don't have a route since Meteor serves it statically. However, when I try to create a route for `/landing`, and have an enter trigger to redirect to `/index.html` it shows the correct url, `/index.html`, but renders the not found page.

Here's my code:

`/lib/router.js`
```
function redirect (url) {
  return function (context, redirect) {
    redirect(url);
  };
}

FlowRouter.notfound = {
  action: function (params) {
    FlowLayout.render('notFound');
  },
};

FlowRouter.route('/landing', {
  triggersEnter: [redirect('/index.html')]
})

```

**Comment by arunoda** [comment]
This index.html directly served from the public directory and it's done on the serverside. So, basically it just act like a normal static assets.

FlowRouter works on the client side it does not know about it. So, don't use public directory for any html content.

**Comment by shawnim** [comment]
I have what I think is s similar problem.  I have a link to a static page that I want to serve from meteor without using any templates. The `static.html` is in `/public`. My meteor template contains:
    <a href="/static.html">Go to the static page</a>
If I type in the url `loclahost:3000/static.html` or right click on the link and open in a new tab it works fine.
If I click the link I get the FlowRouter `notFound` template.
Is there anyway to tell FlowRouter to let the browser go to the static page?

**Comment by sunlee-newyork** [comment]
I'm using `window.location.href = [REL_PATH_TO_STATIC_FILE]` as a workaround:

```
FlowRouter.route('/:key', {
	action(params) {
		if (params.key === "SOME_VALUE") window.location.href="/SOME_FILE.pdf";
	}
});
```
