### ISSUE TITLE
Browserify error on adding flow-router

### ISSUE THREAD

**Issue by BrooklynC** [kadirahq/flow-router#303]
I am trying to add flow-router to my app to replace iron-router but am receiving the following error on "meteor add kadira:flow-router":

    Errors while adding packages:
    While selecting package versions:
    error: Conflict: Constraint cosmos:browserify@0.5.0 is not satisfied by cosmos:browserify 0.1.4.
    Constraints on package "cosmos:browserify":
    * cosmos:browserify@0.5.0 <- kadira:flow-router 2.4.0

    Conflict: Constraint coffeescript@1.0.6 is not satisfied by coffeescript 1.0.6-rc.0.
    Constraints on package "coffeescript":
    * coffeescript@=1.0.6-rc.0 <- top level
    * coffeescript@1.0.6 <- cosmos:browserify 0.1.4 <- kadira:flow-router 2.4.0

Background
- I don't use coffescript or browserify anywhere in my app.
- I am on Windows.  I ran meteor update and see "This project is already at WINDOWS-PREVIEW@0.3.0, the latest release."  My version is meteor@1.1.5-rc.0.
- I also tried adding cosmos:browserify separately but it wouldn't add and I still received the coffeescript error.

Thanks, any help would be much appreciated.  I read through your Routing Guide and think I could make this switch pretty quickly (even as a complete novice).

Brendan

**Comment by arunoda** [comment]
This is due to the use of RC. It's very hard to play with package authors for RC. In order to fix this, browserify package needs to use RC version of coffescript. 

So, for now I think just use the stable Meteor release.

**Comment by BrooklynC** [comment]
Thanks for the reply. I didn't mean to use RC, actually not sure what that is. I simply installed the latest version on Meteor using the Windows installer and this is what it gave me. Would you mind directing me to how I can use the stable release?  Much appreciated.

**Comment by arunoda** [comment]
Try to download the latest version of Meteor and run: https://www.meteor.com/install

**Comment by arunoda** [comment]
Gonna close this, since I hope issue is fixed. If not reopen with more info.

**Comment by BrooklynC** [comment]
Thank you Arunoda, very helpful. I still need to resolve Meteor version on my end but doesn't belong in this thread.
