### ISSUE TITLE
Stop callback in triggers

### ISSUE THREAD

**Issue by VladShcherbin** [kadirahq/flow-router#304]
### Original Title: Stop route action in triggersEnter

I have the code:

```js
var localeGroup = FlowRouter.group({
  prefix: '/:locale?',
  triggersEnter: [localeCheck]
});

localeGroup.route('/login', {
  action: function (params, queryParams) {
    console.log(params.locale);
    console.log('login');
  }
});

function localeCheck(context) {
  var locale = context.params.locale;

  if (locale !== 'en' && locale !== undefined) {
    console.log('locale fail');
    // Show the notFound template and stop the action
    // from firing
  }
}
```

Here in triggersEnter I check the locale (the group prefix) and if it fails I want to render the 404 page (notFound route) and stop before the route action fires. I can render with `BlazeLayout.render('notFound');`, but then the action overrides is.

How can I stop the action from firing with triggersEnter?

**Comment by arunoda** [comment]
You can use our redirect functionality.
See: 

~~~js
function localeCheck(context, redirect) {
  var locale = context.params.locale;

  if (locale !== 'en' && locale !== undefined) {
    redirect('/my-404-page');
  }
}
~~~

**Comment by VladShcherbin** [comment]
@arunoda yes, i tried that, it works fine, but changes the url. But I want the standard behaviour - don't change the url and show the 404 (expected behaviour). Can this somehow be done? (a stop() function in triggers would be great I guess)

**Comment by arunoda** [comment]
Then you need to use the action, try to do it in the layout level.
For that, you need to keep a shared variable which checked in the action to
whether see if it's filter on the trigger or not.

**Comment by VladShcherbin** [comment]
@arunoda I don't think it is the layout task and don't want to mess the layout more (it is already heavy with the permissions and loading stuff).

It is definitely the router level (check the url - stop the action from firing), maybe the `stop()` function could be added to the triggers like the redirect one?

**Comment by arunoda** [comment]
Then you can do something like this:

~~~
var filtered = false;
var localeGroup = FlowRouter.group({
  prefix: '/:locale?',
  triggersEnter: [localeCheck]
});

localeGroup.route("/something", {
  action: function() {
    renderIfNotFiltered("myLayout", {aa: 10});
  }
});

function renderIfNotFiltered (layout, regions) {
  if(!filtered) {
    BlazeLayout.render(layout, regions);
  }
}

function localeCheck(context) {
  var locale = context.params.locale;

  filtered = false;
  if (locale !== 'en' && locale !== undefined) {
    filtered = true;
  }
}
~~~

**Comment by VladShcherbin** [comment]
@arunoda yes, this can be a quick workaround, but it is very dirty and ugly :(

I have the time for the app, so maybe you can think of a better solution in next releases (like a stop function or smth else). But if you think, it is fine to use this solution, feel free to close the issue.

**Comment by arunoda** [comment]
I think this is a good project for a package. (You can override action and add a stop method).
But, it's won't be in core (at least for now)

**Comment by VladShcherbin** [comment]
I think, it would be a great core feature. I tried to add the stop function but you hardcoded the redirect function [here](https://github.com/kadirahq/flow-router/blob/master/client/triggers.js#L72) and in the trigger loop below. A simple function like this would do the work:

```js
doStop = function() {
    abort = true;
}
```

I tried it instead of redirect and it works as expected. Maybe someday you will refactor the triggers and they will accept not only redirect function.

**Comment by arunoda** [comment]
Okay. I understand. Now, I open to accept this :)

Here's the API I'm having in my mind.
Add a 3rd callback to trigger called stop. If so, it'll stop after that.
I think you can simply modify here:
https://github.com/kadirahq/flow-router/blob/master/client/triggers.js#L72 (As
you mentioned)

Could you send me a PR with some tests?

**Comment by VladShcherbin** [comment]
@arunoda haha, I forked the repo and tried the same thing :)

If I understand correctly, it would look like this (in the loop):

```js
trigger(context, doRedirect, doStop);

// below the doRedirect
function doStop() {
    abort = true;
}
```

If I am right, when we want to use the stop function - we should always pass the second param (redirect), even if we don't use it, so if would look like this:

```js
triggersEnter: [checkSomething]

function checkSomething(context, redirect, stop) {
    if (***) {
        stop();
    }
}
```

I tried exactly this workaround and it worked as expected. If I understood everything right, I can try to make tests and a PR. ?

**Comment by arunoda** [comment]
Yeah! That's how to do it. I can't think of a better way :)
Add following tests:

* one on Triggers.runTriggers
* another on using stop inside a trigger

**Comment by VladShcherbin** [comment]
Yes, I also didn't find a better way without refactoring the triggers. I'll do the tests and a PR later today ;)

**Comment by arunoda** [comment]
This is implemented.

**Comment by raduchiriac** [comment]
I am using
```javascript
FlowRouter.triggers.enter([isLogged], {
  only: allPostsRoutes
});
```
but inside my `function isLogged(context, redirect, stop) {...}` **stop** is undefined.

**Comment by space-alien** [comment]
@raduchiriac Are you using flow-router in a package by any chance? I have just run into the same problem with code that was working fine until I moved flow-router into a sub-package.

**Comment by space-alien** [comment]
Oops, I wasn't specifying the dependency version in my package.js, and an old version of flow-router was being used. `meteor reset` cleared the old cached version and now all fine.

**Comment by raduchiriac** [comment]
Yes, flow-router is being added as a dependency for one of the packages I use (telescope:lib) Should I also mention flow-router in my own main `packages` file?

**Comment by s7dhansh** [comment]
Does this work on the client side in the ssr version? `stop` is defined and gets executed but page still goes on to the next url.
