### ISSUE TITLE
How can I run after Meteor.ready?

### ISSUE THREAD

**Issue by AdamBrodzinski** [kadirahq/flow-router#307]
I'm using webpack to build my Meteor app so I can have ES6 modules, hot loading, and an easier env. for React. However there's an issue with this and FlowRouter because the bundled webpack code is ran after Meteor is ready (i'm assuming). 

I get the error "There is no route for the path / ". If I move the route outside webpack and into the meteor folder then it works. It seems to require a route to be defined before webpack is executing this.

Is there a way to allow FlowRouter to work? Or is it a hard requirement that the route be defined before Meteor is ready? I would like to use FlowRouter instead of react-router for this project.

Thanks!

**Comment by VladShcherbin** [comment]
@AdamBrodzinski Hi, maybe [this](https://github.com/kadirahq/flow-router#flowrouterwait-and-flowrouterinitialize) is what you are looking for

**Comment by AdamBrodzinski** [comment]
@VladShcherbin yep that did it thanks!!!
