### ISSUE TITLE
Error in IE9 for METEOR@1.2-rc.11: Object doesn't support property or method 'replaceState' 

### ISSUE THREAD

**Issue by timbrandin** [kadirahq/flow-router#309]
I get this error when testing out flow-router-ssr for react in IE9 in the METEOR release @1.2-rc.11

```
SCRIPT438: Object doesn't support property or method 'replaceState' 
kadira_flow-router-ssr.js?50c95030de55d57abd227d6eaa5b11ceda39d000, line 568 character 5
```

**Comment by timbrandin** [comment]
Oh, I guess it has to do with a non-existing support for IE9:
http://stackoverflow.com/questions/3722815/does-internet-explorer-support-pushstate-and-replacestate

**Comment by timbrandin** [comment]
Maybe a solution could be to use a polyfill?
https://github.com/browserstate/history.js

**Comment by timbrandin** [comment]
This package solves the issue!
```
meteor add tomwasd:history-polyfill
```

**Comment by arunoda** [comment]
May be we need to update docs to use this polyfill
