### ISSUE TITLE
There is no route for the path - "/" in Safari browser

### ISSUE THREAD

**Issue by bilalahmed70** [kadirahq/flow-router#310]
App is working fine in chrome and firefox but in safari it gives an error 'there is no route for the path /'

Here is the route:

FlowRouter.route("/", {
  action: function() {
    ReactLayout.render(App, {
      content: <GroupBox />
    });
  }
});

and here is the error:

There is no route for the path - "/":
_notfoundRoutekadira_flow-router.js:1902
(anonymous function)kadira_flow-router.js:2074
(anonymous function)kadira_flow-router.js:577
nextEnterkadira_flow-router.js:409
dispatchkadira_flow-router.js:415
replacekadira_flow-router.js:377
(anonymous function)kadira_flow-router.js:1935
startkadira_flow-router.js:273
pagekadira_flow-router.js:207
initializekadira_flow-router.js:1943
(anonymous function)kadira_flow-router.js:2370
runStartupCallbacksstartup_client.js:29
readystartup_client.js:31

**Comment by arunoda** [comment]
That's pretty weird. Can I have a sample repo where I can see it.

**Comment by bilalahmed70** [comment]
Here it is https://gist.github.com/bilalahmed70/3f088243da1f5a9fff7c

**Comment by imkost** [comment]
I have the same issue. I use Chrome and METEOR@1.2-rc.12

**Comment by imkost** [comment]
I had the same issue (but in Chrome). The problem was solved after I removed `tomwasd:flow-router-autoscroll` package

**Comment by arunoda** [comment]
I'm quite not sure, how these module system works. So, this question better suites here. The thing is FlowRouter didn't get a route when it's booting stuff.

May be you can try this: https://github.com/kadirahq/flow-router#flowrouterwait-and-flowrouterinitialize

**Comment by bilalahmed70** [comment]
I do not have any such package installed. I created a meteor app from scratch and added just one route and have the problem still. @arunoda I shared the repo as you requested. I tried with both current stable and release candidate version of meteor. Your help would be appreciated. I am not able to publish app just because this. Thanks!

**Comment by arunoda** [comment]
Yes you've: `universe:modules`

**Comment by imkost** [comment]
I've just cloned your repo, run it with Meteor 1.1.0.3 and it runs without any errors.

Here is what I've got in the console:

```
babel-compiler       added, version 5.8.3_1
babel-runtime        added, version 0.1.3
coffeescript         added, version 1.0.6
cosmos:browserify    added, version 0.5.0
jsx                  added, version 0.1.6
kadira:flow-router   added, version 2.6.0
kadira:react-layout  added, version 1.3.0
react                added, version 0.1.10
react-meteor-data    added, version 0.1.6
react-runtime        added, version 0.13.3_6
react-runtime-dev    added, version 0.13.3_5
react-runtime-prod   added, version 0.13.3_4
universe:modules     added, version 0.4.2
```

Maybe you should update `universe:modules` package (you have 0.3.0)

**Comment by imkost** [comment]
I also use `universe:modules` in my projects and I found this issue:

If I have something wrong inside some `.import.js(x)` file and I import this file in another file, then I don't see errors, I see `There is no route for the path - "/"` instead. Maybe you import some bad code somewhere in your project. Anyway, there is no wrong with the code you provided.

**Comment by bilalahmed70** [comment]
@arunoda the problem is resolved after I renamed one of my file.import.jsx to file.jsx. there was no export module in this file and universe:modules was throwing an error. chrome and firefox were fine but apparently safari didn't like it but there was no clear message. anyways thank you for your help and work in meteor project.

@imkost you were right about the bad code. In my test code there was an incorrect class used in .import.jsx file. Again chrome and firefox were fine but Safari didn't like it. Thanks for your help!

**Comment by arunoda** [comment]
Great.

**Comment by noushka86** [comment]
I have the same problem and I cant seem to solve it... 
here's my repo: https://github.com/noushka86/swiper
