### ISSUE TITLE
Error when doing SSR. path: /   Object [object Object] has no method 'loggingIn'

### ISSUE THREAD

**Issue by churcho** [kadirahq/flow-router#312]
I have this in my ReactLayout 

```
getMeteorData() {   
   let data ={
    authInProcess:Meteor.loggingIn(),
    canShow: !!Meteor.user(), 
   } ;
```

The code worked well but I am getting the notification 
```
Error when doing SSR. path: /   Object [object Object] has no method 'loggingIn'
TypeError: Object [object Object] has no method 'loggingIn'
```

What am I missing?

**Comment by delgermurun** [comment]
There is no `Meteor.loggingIn()` method on server. http://docs.meteor.com/#/full/meteor_loggingin

**Comment by arunoda** [comment]
Yes. In the serverside, you don't need authInProcess. Simply make it false.
