### ISSUE TITLE
Supporting Subdirectory as ROOT_URL?

### ISSUE THREAD

**Issue by totorokk** [kadirahq/flow-router#315]
I'm deploying two apps on the same server/base domain, using nginx to handle the proxy to subdirectories. e.g. http://mydomain.com/appOne and http://mydomain.com/appTwo. 

But I think [when FR resolves the url](https://github.com/kadirahq/flow-router/blob/master/test/server/_helpers.js#L29), the subdirectories of ROOT_URL are stripped off. So if I want a route "http://mydomain.com/appOne/login" with ROOT_URL="http://mydomain.com/appOne", I still need to config route "/appOne/login" instead of "/login".

The issue originally comes from the npm "url" package. But would FR be supporting subdirectory in the future, or we should stick with the above work-arounds for this?

**Comment by arunoda** [comment]
What I suggest it to create a Group route. Create is based on the `Meteor.settings`. I mean get the prefix from the `Meteor.settings.`

So, locally you can run it with "/" and when deploying you can set it to whatever you want.

**Comment by totorokk** [comment]
Got it. I'll use group prefix instead of changing the way url gets resolved. Thanks!

**Comment by arunoda** [comment]
Awesome.. Hope we can close this.

**Comment by mquandalle** [comment]
Hum, I also encounter this problem in Wekan (cf. https://github.com/wekan/wekan/issues/133) with the difference that I'm not fully controlling the production environment in case people are self-hosting the application.

From https://github.com/meteor/meteor/issues/2067, it seems to me that flow-router should handle this subdirectory parameter exposed by Meteor.

**Comment by arunoda** [comment]
Hmm. Good idea. 
Could you send me a PR?

Here's the place to add it: https://github.com/kadirahq/flow-router/blob/master/client/router.js#L367
(You can easily do this buy adding a pagejs option: https://goo.gl/jgpidT - I assume it'll work)
