### ISSUE TITLE
flow-router-ssr - issue with react + collection hooks

### ISSUE THREAD

**Issue by markoshust** [kadirahq/flow-router#316]
I'm not sure if this is an issue with `flow-router-ssr` or `dburles:collection-helpers`, but I was receiving errors like the following from meteor console:
```
W20150910-10:01:47.240(-4)? (STDERR) Error when doing SSR. path: /   Cannot read property 'user' of undefined
W20150910-10:01:47.363(-4)? (STDERR) TypeError: Cannot read property 'user' of undefined
```

The "user" prop comes from the `dburles:collection-helpers` package and is a custom collection helper.

The error went away on the meteor side when I added the following to react component:
```
    if (typeof this.props.wallPost.user == "function") {

      return (
        <UserProfileRep user={this.props.wallPost.user()}/>
      );
    }
```

However, now I'm receiving the following error from react, complaining that the server and client are sending mismatched info, and that I may not be receiving the full benefits of SSR:
```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) 8n0yzda8.2.0.2.0.0">
</textarea><button 
 (server) 8n0yzda8.2.0.2.0.0"></textarea><button c
```

Any idea what could be going on here? Is my func check & implementation correct?

Thanks!
Mark

**Comment by arunoda** [comment]
I'm sorry. I can't tell anything, without looking at any sample code.

**Comment by klarstrup** [comment]
I've also run into this issue, seems like FlowRouter's SSR doesn't have the methods from collection-helpers on the documents.

I can type up a small reproduction if necessary.

**Comment by TimoRuetten** [comment]
You can simply fix this with: document = MyCollection._transform(document);

You only need to do this on Server and not on Client.
