### ISSUE TITLE
FlowRouter.all() && Database based Routing

### ISSUE THREAD

**Issue by rockymontana** [kadirahq/flow-router#317]
It'd be really awesome (mostly for debug purposes) to be able to get a list of all registered routes.

I'm building a database based routing system with FlowRouter at the moment.
As with any CMS system all page routes are saved to the DB, but now that I'm trying to fetch the routes I get an error saying '/' is not defined.

Some code:
lib/routes.jsx
```
Routes.find().fetch().map((dbRoute) => {
    FlowRouter.route(dbRoute.path, {
        name: dbRoute.name,
        action(params) {
            renderWithLayout(dbRoute);
        }
    });
});

function renderWithLayout(dbRoute) {
    ReactLayout.render(window[dbRoute.template], {
        content: window[dbRoute.component],
    });
}
```

/lib/bootstrap.jsx
```
Meteor.startup(() => {
    if (Routes.find().count() === 0) {
        Routes.insert({
            path: '/',
            name: 'Start',
            template: 'MainLayout',
            component: 'Home'
        }, function(error, result) {
            console.log(error);
        });

        Routes.insert({
            path: '/login',
            name: 'Login',
            template: 'MainLayout',
            component: 'Login'
        }, function(error, result) {
            console.log(error);
        });
    }
});
```

lib/collections/routes.jsx
```
Schemas = {};

Schemas.Routes = new SimpleSchema({
    path: {
        type: String,
        optional: false,
    },

    name: {
        type: String,
        optional: false,
    },

    component: {
        type: String,
        optional: false
    },

    template: {
        type: String,
        optional: true
    }
});

Routes = new Meteor.Collection('Routes');
Routes.attachSchema(Schemas.Routes);
```
Any ideas?

**Comment by arunoda** [comment]
The things is FlowRouter tries to run routes just after the DOM loaded. But in your case, you don't have data at that time and no routes will be rendered.

So, you can use this: https://github.com/kadirahq/flow-router#flowrouterwait-and-flowrouterinitialize

**Comment by rockymontana** [comment]
Awesome! Ill try that!

So Ill set flowrouter to wait, load My DB set and then initialize?

What about the serverside rendering? Are there any differences there?

Because I don't want that blank page when the site initializes before the router loads the default page. Is that possible?




Jonas



—
Have a nice day!
