### ISSUE TITLE
Error installing on Windows 7 - flow-router 2.0

### ISSUE THREAD

**Issue by jsmeteor** [kadirahq/flow-router#319]
Hello 
I received the following error when trying to install on Windows 7 machine - with latest version of Windows version of Meteor

Thanks in advance
JS.

C:\CodeJS\meteorjs\flowpub>meteor add kadira:flow-router
 => Errors while adding packages:

While selecting package versions:
error: Conflict: Constraint cosmos:browserify@0.5.0 is not satisfied by
cosmos:browserify 0.1.4.
Constraints on package "cosmos:browserify":
* cosmos:browserify@0.5.0 <- kadira:flow-router 2.6.0

Conflict: Constraint coffeescript@1.0.6 is not satisfied by coffeescript
1.0.6-rc.0.
Constraints on package "coffeescript":
* coffeescript@=1.0.6-rc.0 <- top level
* coffeescript@1.0.6 <- cosmos:browserify 0.1.4 <- kadira:flow-router
2.6.0

**Comment by arunoda** [comment]
Seems like somehow, you are using a RC version of coffeescript. Try to remove it.
Meteor won't play well with RCs.

**Comment by arunoda** [comment]
This is related to packages based question. I support this is best for Meteor Forums.

**Comment by jsmeteor** [comment]
Thanks for your response. However, I don't have coffeescript package on my system. Meteor list does not list coffeescript; I tried removing it using Meteor remove coffeescript - Isays not installed on the system). So I am not sure why it is conflicting with flow-router. I assumed it was something in flow-router package that was requiring coffeescript. If this is this the wrong forum - I will perhaps post on the forum. 
Thanks

**Comment by jsmeteor** [comment]
Just wanted to leave an update: Apparently the problem was my version Meteor which has pre-release version. Running Meteor update didn't update it to the released version.
I found this other thread with the same problem: solution was go and download the new install of Meteor for windows and reinstall Meteor to version 1.1.0.3 and it worked. 
Here is the link to the old thread:
https://github.com/kadirahq/flow-router/issues/303

Thanks for your quick response
