### ISSUE TITLE
Using FlowRouter.getParam as template-wide variable

### ISSUE THREAD

**Issue by JulianKingman** [kadirahq/flow-router#320]
I have a route that's roughly like this:
posts/:postId/

What's the best way to reference the postId for the whole post.html template? I'd like to be able to do this:
````javascript
var postId = FlowRouter.getParam('postId');
Template.post.helpers({
    post: function(){
        return posts.findOne({_id: postId});
    }
});
````
But the postId variable comes back undefined. I thought this could be related to bug #95, but I don't have getParam inside onCreated, so it's a little different. 

For now, I can declare the postId in each of the helpers, but it's redundant, and I use it almost a dozen times, not very DRY.

**Comment by arunoda** [comment]
You need put `var postId = FlowRouter.getParam('postId');` inside the helper itself.

**Comment by JulianKingman** [comment]
I was hoping to avoid that so I could reuse the variable in several helpers and events, for example:
````javascript
author: function(){
    return authors.findOne({posts: {$in: postId}});
}
````
Is there a better way to get the postId/context? Should I be pulling the context from the template, and using that to find related docs?

**Comment by JulianKingman** [comment]
I almost forgot another thing, I would like to subscribe to a collection with the postId as an argument.

**Comment by arunoda** [comment]
May be you are looking to pass FR context as data to a template. So, check this: https://kadira.io/blog/meteor/introducing-blaze-plus-the-next-generation-of-blaze

**Comment by arunoda** [comment]
I close this because this is a question. Feel free to discuss.

**Comment by JulianKingman** [comment]
Very interesting, I'll have to take a deeper look into blaze plus. Is it a drop-in replacement for blaze (as in remove blaze, add blaze plus, works like blaze plus the other functionality)?
