### ISSUE TITLE
Lazy loading of JS/CSS bundles

### ISSUE THREAD

**Issue by skosch** [kadirahq/flow-router#321]
Hi,

I'd like to know your thoughts on what might a FlowRouter-appropriate replacement for Miro's preloader package might look like.

I'm not personally a fan of specifying the list of dependencies on a per-route basis. One reason is that it would require the router to wait for the downloads to finish (and I love FlowRouter precisely because it doesn't wait for things). The other, more important reason is that I'm working with dynamic templates *a lot*, and many of those should really only be pulled in, along with their dependencies, just before they are rendered (and often times the route won't change at all when the dynamic template changes). In other words, I believe modularity should be a matter of templates, not routes.

Still, our app is growing quite large, and this is a pressing enough issue that I'm considering going back to IR just to be able to use preloader.

So, a penny for your thoughts—and if this is completely outside of FlowRouter's/Blaze-Layout's scope, then what would be the best place to start?

**Comment by arunoda** [comment]
I think we have a similar feature in the SSR version. In there, we download the app code after the HTML. So, still you need to download the whole bunch, but it doesn't affect the rendering. It's in action on Kadira's homepage.

See: https://kadira.io/blog
(Check the source as well)

**Comment by arunoda** [comment]
Other than that, it's a kind a too big project. We'll wait a bit for that.
