### ISSUE TITLE
Conditional triggers

### ISSUE THREAD

**Issue by thinklinux** [kadirahq/flow-router#322]
I have a trigger that scrolls page to the top when navigating through my app. But there are cases that I don't want that to happen. Here is an example:

I have a `:locale` param in  the url like so: `/en/home`. When I want to change the locale of the app and to stay on the same page I have to change the `:locale` param so I do:

```javascript
FlowRouter.setParams({locale: "fr"});
```

But I didn't find a way to stop the trigger to scroll the page. I want seamless transition between languages without disturbing the user. It would be nice if I could do something like that:

```javascript
FlowRouter.setParams({locale: "fr"}, {scrollTop: false});
```

and then in the trigger:

```javascript
triggersEnter: [function(context, redirect, options) {
  if (options.scrollTop) {
    // scroll to top
  }
}]
```

Do you think that would be useful?

**Comment by arunoda** [comment]
We won't have a feature like that. But, it's fairly simple to implement outside of FlowRouter. Simply create a global variable and use that.

~~~js
Options = {};
FlowRouter.setParams({locale: "fr"});
Options.scrollTop = false;

triggersEnter: [function(context, redirect) {
  if (Options.scrollTop) {
    // scroll to top
    delete Options.scrollTop;
  }
}]
~~~
