### ISSUE TITLE
FlowRouter.setParams does not work with multiple params?

### ISSUE THREAD

**Issue by atlewee** [kadirahq/flow-router#323]
First: Thanks for this wonderful simple router! :)

my problem...
Route: 
FlowRouter.route("/settings/:PAGE?/:SUBPAGE?

Trying:
FlowRouter.setParams({PAGE: "a page", SUBPAGE:"a subPage"});

This is not working. Seems like SetParams only use the param SUBPAGE and sets this as PAGE param.
This only happends if I set SUBPAGE. No matter what PAGE is set to, nothing happends. If I say TEST="a subPage" nothing happends. The only time something happends is if I set SUBPAGE to something, it does not matter if its first or last. The value of SUBPAGE becomes PAGE in the route.
Is this intended?

**Comment by arunoda** [comment]
I tried it. It's working and it should be.
Would like to see a sample?

**Comment by atlewee** [comment]
Thanks for your quick reply. An example would be great.

To clearify:

I'm sending the parameters into an React component as props.. This works perfect, when entering/changing the url manually or with href/link, no problems.

FlowRouter.route("/settings/:page?/:subPage?", {
    action(p) {
        ReactLayout.render(MainLayout, {menu:<MainMenu/>, content:<Settings page={p.page} subPage={p.subPage}/>})
    }
});

Inside the settings component I use this:
    onSubClick(e) {
        FlowRouter.setParams({page:"test1", subPage:"test2"});
    },

But that changes my url to: /settings/test2 insted of /settings/test1/test2
