### ISSUE TITLE
FlowRouter break onClick functionality of React components on anchors

### ISSUE THREAD

**Issue by tomitrescak** [kadirahq/flow-router#326]
I have spent significant time on checking why my onClick events on anchors are not triggered and it all points to the FlowRouter. consider these examples:

NOT TRIGGERED
```
<a onClick={this.myEvent.bind(this)} href={FlowRouter.path("some")} />
```

TRIGGERED
```
<a onClick={this.myEvent.bind(this)} />
```

TRIGGERED

```
<a onClick={this.myEvent.bind(this)} href="#" />
```

Do you have any idea what can be the problem?
Thanks

**Comment by arunoda** [comment]
I'm not sure we do anything for that. May be React doesn't do it when there's an URL href.
Again, I'm not sure about the real reason.

**Comment by tomitrescak** [comment]
Hmm, I thought that Router is somehow interfering with events. My last possibility is semantic ui, which tend to do weird stuff with DOM. If you are sure it cannot be FlowRouter, I'll close this issue.

**Comment by macrozone** [comment]
can confirm this. It's flow router that interferes with click events on links.

**Comment by semeano** [comment]
I'm having the same issue.

Works
```
var link = "https://www.google.com";
...
<a onClick={this.props.onClickEvent} href={link}>
```

Doesn't work
```
var link = FlowRouter.path('anotherPage', { param: paramValue });;
...
<a onClick={this.props.onClickEvent} href={link}>
```

Any ideas how do get around this?


Update:

Nevermind. This doesn't work either (onClickEvent is not triggered):
```
var link = "/blog";
...
<a onClick={this.props.onClickEvent} href={link}>
```
