### ISSUE TITLE
redirect to external url

### ISSUE THREAD

**Issue by OminStyle** [kadirahq/flow-router#327]
Is it possible to redirect to external url? I saw #172 but it doesn't seem like it's supported.

**Comment by OminStyle** [comment]
Will do this from the client side for now.

**Comment by bolus** [comment]
It seems there's a bug.

'redirect("http://foo.com/bar.html")' redirects to http://my-domain.com/foo.com/bar.html and not to http://foo.com/bar.html

At least on the SSR branch.

There should either be an exception or the visitor should get redirected to the URL.

Also, I'm wondering why it's only possible to redirect from within triggers.

Is it somehow possible to redirect visitors from within the action callback?

**Comment by arunoda** [comment]
We are not adding external app redirect support. At least for current stable version. If you need that, you need to do that, inside a trigger.

Then simply call:

```
window.location = 'whatever the url you need';
```

**Comment by bolus** [comment]
Okay, but would it be possible to document this?

And wouldn't it be better to throw an exception?

When my domain is 'my-domain.com' and I write 'redirect("http://foo.com/bar.html")' then there should be an exception.

To redirect to 'http://my-domain.com/foo.com/bar.html' seems broken to me.

**Comment by arunoda** [comment]
I like to throw an exception if there is http(s):// part in the url. @bolus could you send me a PR?
Here's the place, you can do that.

**Comment by bolus** [comment]
@arunoda: [done!](https://github.com/kadirahq/flow-router/pull/339)

This is the first time I created a pull request and used git (besides git clone/commit/push). Let me know if I did something wrong and I'll try to fix it.

Btw., did you see my last comment in the other issue? I did forget to tag you.

[Here is a link to the comment](https://github.com/kadirahq/flow-router/issues/328#issuecomment-143788157)

**Comment by arunoda** [comment]
Merged the PR. 
Hope we can fix this.
