### ISSUE TITLE
SSR: Triggers don't work as expected (code gets executed on the client instead of on the server)

### ISSUE THREAD

**Issue by bolus** [kadirahq/flow-router#328]
I have the following CoffeScript code ([Compiled to JavaScript](https://gist.github.com/bolus/8e095d7fefc87d11d4c5)):

```coffeescript
FlowRouter.route "/foo",
    triggersEnter: [
        (context, redirect) ->
            console.log("foo trigger")
            redirect("/bar")
    ]
    action: (params, query_params) ->
        console.log("foo action")

FlowRouter.route "/bar",
    action: (ps, qs) ->
        console.log("bar action")
```

This logs to the browser:

```
foo trigger
bar action
```

and to the server:

```
foo action
```

But this shouldn't happen because I use the SSR branch, if I understand the purpose of Flow Router SSR correctly.

foo trigger and bar action should get executed on the server (SSR) and foo action should never get executed.

Am I right or do I misunderstand something?

**Comment by arunoda** [comment]
SSR and redirect is consuming. I'm closing this for now.
We'll fix this when we are ready for 3.0

**Comment by bolus** [comment]
Can you explain what you mean with "SSR and redirect is consuming". To be honest, I don't understand what you mean.

Is this documented somewhere?

Also, do you have a rough estimate when 3.0 will be ready?

By the way, thanks a million for your work for the Meteor community!

**Comment by alansikora** [comment]
@bolus, I believe @arunoda refers to how expensive SSR already is to the server and adding that extra feature would make it even more.

So, performance improvements are still needed before that's possible.
