### ISSUE TITLE
Hashbang URL with SSR issue

### ISSUE THREAD

**Issue by minhanhhere** [kadirahq/flow-router#330]
Hello,

I clone this sample project and initialize FlowRouter with **hashbang:true**
https://github.com/arunoda/hello-react-meteor
Then, in a web browser, I enter this url: `http://localhost:3000/#!/post/two`. The post list was showed first, then the post two showed after that.

How can I get rid of this behavior?

**Comment by arunoda** [comment]
You can't use hashbang with SSR. Hasgbangs never sent to the server.
