### ISSUE TITLE
Is GitHub style routing officially supported?

### ISSUE THREAD

**Issue by derwaldgeist** [kadirahq/flow-router#332]
I want to set-up a routing that resembles GitHub's. That means:
>
```
/
```
is a home-page
```
/:user
```
is a user page
```
/:user/:repo
```
is a repository page

but
>
```
/reservedword
```
routes to a special route, based on the reserved word (like ```https://github.com/pulls```)
```
/reservedword/subpage
```
the same for sub-pages

I found out that this kind of routing actually works, but only if you set-up the routes in the correct order. That means: The routes that define the "reserved words" have to be initialized first, and then the generic fall-back routes (using parameters). If I do it the other way round, the parametrized routes take precedence.

Yet, I am wondering if this is just working "by chance", or if I may rely on this behaviour? It would have a heavy impact on my site if the routing behaviour would change in the future.

**Comment by arunoda** [comment]
You are correct. This is the way to do it. You need to specializations at the first and then to all the generic stuff.

**Comment by derwaldgeist** [comment]
Ok, thanks a lot for the quick reply!
