### ISSUE TITLE
Update cosmos:browserify dependency 

### ISSUE THREAD

**Issue by boustanihani** [kadirahq/flow-router#333]
Please update the ```cosmos:browserify``` dependency to the latest version (currently ```0.7.0```):

Check: https://github.com/kadirahq/flow-router/blob/master/package.js#L63

**Comment by arunoda** [comment]
version 0.7.0 have issues and they fixed some stuff with 0.8.0.(So I'll wait a bit, until 0.8 became stable) But we don't need to update it.
Meteor's package system semver based. So, if there is 0.8.0 or higher, FR will use it.
