### ISSUE TITLE
React is undefined since meteor 1.2.0.1

### ISSUE THREAD

**Issue by ravid87** [kadirahq/flow-router#334]
Hello,
I have a console error "ReferenceError: React is not defined" on the client side since i updated meteor, here my packages list in my own package : 

    api.use([
        'react@0.1.13',
        'kadira:flow-router@2.6.2',
        'kadira:react-layout@1.3.0',
        'aldeed:collection2@2.5.0',
        'aldeed:simple-schema@1.3.3',
        'twbs:bootstrap@3.3.5'
    ]);

hope you will help.

**Comment by arunoda** [comment]
Released a new version which weakly depend on react. Try this: v1.3.1 for
react-layout.

**Comment by ravid87** [comment]
work perfectly :+1:

**Comment by arunoda** [comment]
Great.
