### ISSUE TITLE
Get the path by route name.

### ISSUE THREAD

**Issue by nixoz** [kadirahq/flow-router#335]
Hi guys! thanks for the great piece of software.

Recently i've decided to migrate from the iron:router to flow-router, and having some issues..
The one i want to ask about is this one:

I have route definition:

```
FlowRouter.route('/', {
  name: 'home',
  action: function(params) {
    BlazeLayout.render('baseLayout', {content: 'home'});
  }
});
```
So, then i want to get the path for route named "home":
And according to the docs i can do it (even by name) with FlowRouter.path();

> You can also use the route's name instead of the pathDef. Then, FlowRouter will pick the pathDef from the given route. See the following example...[CUT]

So when i'm doing FlowRouter.path('home') - method returning "/home" to me, which kinda frustrating.

I've also checked the Router.prototype.path definition, not sure it's going do something else for me.

Right now i need to create custom method which is looking at private _routesMap and getting the "path", i'm not sure it's a clean way of things here.

Any thoughts?

Best,
S.

**Comment by arunoda** [comment]
If you call `FlowRouter.path('home')` you should get back `/`. If not that's a bug. (I didn't see that earlier).
Could you create a sample repo and send to me. I'll have a look at it.

**Comment by nixoz** [comment]
Thank you for your reply.

I'm trying to localize that problem in distinct app and to reproduce the problem. But can't do that.
On freshly created meteor app, everything is according to behavior you have described.

Looks like i have mess with the dependencies, or maybe i'm just stupid =)...
Anyway, thank you so much and sorry for disturbance.

p.s. if i'll find any problem i'll report properly.

**Comment by arunoda** [comment]
Reopen once you get a re-produible app.
