### ISSUE TITLE
1.2 Meteor - FlowRouter not defined

### ISSUE THREAD

**Issue by mgambati** [kadirahq/flow-router#336]
I'm creating a new project from zero. After the meteor 1.2 release Flow is not working. 

Test route:
``` javascript
FlowRouter.route( '/test', {
  action: function() {
    console.log( "Working" );
  }
});
```
 The console log.
![image](https://cloud.githubusercontent.com/assets/813131/10088791/6c45cff8-62eb-11e5-8007-e49512752c9a.png)

It's appear that flow's package loads after my router.js files. I also made a test with old release of meteor and it's working fine.

**Comment by nixoz** [comment]
@mgambati mate, looks like it's not the FlowRouter problem. Check the stacktrace within the first thrown exception. It's materialize's issue refer to [this issue](https://github.com/meteor/meteor/issues/5231)

**Comment by arunoda** [comment]
We are using flow with 1.2 and there is not issue.
If there is an issue, try to build re-producible app.

**Comment by grsabreu** [comment]
That is a problem with lastest Materialize package release @mgambati

**Comment by mgambati** [comment]
@grsabreu It's working now. Just rollbacked materialize.
