### ISSUE TITLE
Allow CSS classes to be added to the react-root div for Server Side Rendering

### ISSUE THREAD

**Issue by rwuttke** [kadirahq/flow-router#342]
I am using Sematic UI and am trying to replicate the login layout, i.e. http://semantic-ui.com/examples/login.html

The problem is that the react-root div is breaking the page.

I can add

```jsx
componentDidMount() {
    let reactRoot = ReactLayout._getRootNode();
    reactRoot.className = "ui middle aligned center aligned grid"
  },
```
But the dialog starts in the top center and then jumps to the center/center when the client side is rendered.

I would like to be able to, in the flow router setup, set the string of classes that I would like to add to the div or something that would give the same effect

ie

```jsx
FlowRouter.route("/", {
  name: "Login",
  rootClassName: "ui middle aligned center aligned grid".
  action: function() {
    ReactLayout.render(LoginLayout, {
      content: <Login />
  });
  }
});
```
Which would add that class set to the creation of the div.

**Comment by arunoda** [comment]
How about doing this?

```js
FlowRouter.route("/", {
  name: "Login",
  action: function() {
    ReactLayout.render(LoginLayout, {
      content: (
        <div className="ui middle aligned center aligned grid">
          <Login />
        </div>
      )
    });
  }
});
```

I think that's the best way to do this.

**Comment by rwuttke** [comment]
Because it doesn't fix the problem. In fact that is even worse, as this div is placed inside the first div inside Login, which is not what I want or need.

```html
<body>
  <div id='react-root'>
    <div class="column" data-reactid=".2a3e250eadc" data-react-checksum="1761533911">
      <!-- This needs to be before the previous div, and instead of the react-root div. -->
      <div class="ui middle aligned center aligned grid" data-reactid=".2a3e250eadc.0"> 
        <span data-reactid=".2a3e250eadc.0.0">
          <h2 class="ui teal image header" data-reactid=".2a3e250eadc.0.0.0">
```

**Comment by arunoda** [comment]
Okay. Now I got it.
This is an issue we need to address on the ReactLayout: https://github.com/kadirahq/meteor-react-layout
We could have an API like:

~~~
ReactLayout.setRoot(
  <div className="your classes...">
   ....
  </div>
);
~~~

**Comment by arunoda** [comment]
Check this: https://github.com/kadirahq/meteor-react-layout#add-custom-props-to-root-element

Had to change the way I suggested.

**Comment by rwuttke** [comment]
Hi @arunoda, I have looked at this and it is almost there, the problem is now, if I have two different routes with different root props, only the first one is rendered with the routes root props.

In _getRootNode, it should change the classes to the new root props. Currently this is only done in _buildRootNode.

Regards.

**Comment by arunoda** [comment]
I am sorry. This is the best we can do. Try to design your app layout accordingly. 

Create a root node which is static. I assume it can be done with any css framework. Otherwise, it's a flaw in that framework.

**Comment by rwuttke** [comment]
No worries, cheers for everything.
