### ISSUE TITLE
Allow CSS classes to be added to the react-root div for Server Side Rendering

### ISSUE THREAD

**Issue by rwuttke** [kadirahq/flow-router#343]
#342 was closed before the issue was resolved.

The issue is the 

```html
<div id="react-root">
```

The suggested fix did nothing to address the correct issue.

If this div is in the DOM with none of the classes suggestd in 342, it will break semantic-ui screen centering layout, and from what I remember UIKit as well.

**Comment by arunoda** [comment]
I'm re-opening that issue again.

**Comment by rwuttke** [comment]
Thank you very much. Appreciate all the hard work you have put into all your projects.
