### ISSUE TITLE
Better authentication methods

### ISSUE THREAD

**Issue by themeteorchef** [kadirahq/flow-router#344]
I know this is a much contested topic, but please hear me out.

The current state of authentication in Flow Router is less than ideal. The prescribed solution of using templates works to some extent, however, it mucks up the URL for the user. For example, using the templates pattern, if I visit a route like `/admin`, ideally I'd be redirected to `/login`. Instead, I'm simply shown the `{{> login}}` template. This is fine, but it feels...odd. 

In addition to this, it's also tricky to implement things like redirecting logged in users away from public pages. For example, if I want to redirect a logged in user away from the `/login` route, it's not entirely clear how I can achieve this with templates. I imagine something must exist, but as-is it's not very clear.

While many people scorn Iron Router for its response to reactivity, one thing it does incredibly well is handling authentication flow with its hooks. For example:

```
var userAuthenticated = function(){
  if( !Meteor.loggingIn() && Meteor.user() ){
    Router.go('/');
  } else {
    this.next();
  }
}

Router.onBeforeAction(userAuthenticated, {
  only: [
    'signup',
    'login',
    'recover-password',
    'reset-password'
  ]
});
```

This is extremely clear. When I visit the routes in the `only` list, call the `userAuthenticated` method. I realize that this relies on response to reactivity, but that seems like something we want here as we always need to wait at least a little bit when Meteor loads up. Triggers seem to more-or-less behave like this, but without reactivity. If there was any spot where reactivity would be useful, this would be it.

So far, there hasn't been a clear argument as to _why_ this shouldn't be done, just that it's an "anti-pattern." For example this statement in the Flow Router guide:

> Previously, we did this in the router layer (specifically with Iron Router). However, that's not a good design and we don't recommend it.

Why is it not a good design? Why do you not recommend it? Simply saying "we don't like it" makes it difficult to really understand the merits of your own solution and how to fit it into an application.

The reason I'm adding this issue is that it looks like Flow Router is slowly becoming the community favorite. Rightfully so, as its focus on being able to render seemingly any UI framework is great. The minimalism of it all is nice, too. Authentication, though, is sticky and if Flow Router is going to be "the" solution in the future, it seems like a better authentication solution (or at least, some options outside of templates) should be considered.

Any chance for discussion on this? My first thought was that this could be a package or something that's added on selectively. One option like this [exists](https://atmospherejs.com/cottz/flow-router-auth), but it'd be nice to see something built (or recommended by) the Kadira team.

**Comment by arunoda** [comment]
Please read this post carefully: https://kadira.io/academy/meteor-routing-guide/content/implementing-auth-logic-and-permissions

And there is a link at the bottom which links to the Meteor Forums post. Here it is: https://forums.meteor.com/t/question-to-mdg-building-routing-into-core/4378/35

The decision to move the auth layer is not a **personal** preference. It's started with a technical reason. But it also gives you better UX as well.

**Comment by arunoda** [comment]
Let me add some points again :)

> For example, using the templates pattern, if I visit a route like /admin, ideally I'd be redirected to /login. Instead, I'm simply shown the {{> login}} template. This is fine, but it feels...odd.

This is based on something you've done previously. In flow-router, we do things differently. And we are strictly opinionated on these matters.

> In addition to this, it's also tricky to implement things like redirecting logged in users away from public pages

Don't redirect.

> While many people scorn Iron Router for its response to reactivity, one thing it does incredibly well is handling authentication flow with its hooks.

This is going back to reactivity. That's why IR is bad and unpredictable.

> Authentication, though, is sticky and if Flow Router is going to be "the" solution in the future, it seems like a better authentication solution (or at least, some options outside of templates) should be considered.

Auth should live outside of the router. That's something fixed and we won't have any items in the roadmap for that.

**Comment by themeteorchef** [comment]
Can you please provide more detail here? These seem to be the same responses you've given to everyone. For example:

> That's why IR is bad and unpredictable.

There's no explanation as to why its response to reactivity is bad and none of your answers to others explain it either. Nor does the guide on the Kadira site. Meteor by nature is reactive. Why is it bad for our routes to respond to that reactivity (without saying it was bad in Iron Router)? It's fine that you hold the opinion, but I'm trying to understand from a technical perspective.

**Comment by arunoda** [comment]
I've mentioned some of them in the Flow Router REAME at the end. There are some reasons in Meteor Forums. Also check Telescope's new blog about why they move to FlowRouter.

When building a big app, reactivity in router makes it hard to predict what's happening. That may be a reason how IR implemented it.

But, we avoid from it from the beginning and proved it a good way to do stuff. That's it.
If you need Reactivity in the router or do auth in the router, FR is the solution for you.

**Comment by stubailo** [comment]
> if I visit a route like /admin, ideally I'd be redirected to /login. Instead, I'm simply shown the {{> login}} template. This is fine, but it feels...odd.

I strongly disagree with this for the record; why would you want a separate URL for login? That results in all of the situations you see every day around the web where you are trying to go to a page, then get redirected to a login page, and never end up on the page you're actually looking for.

**Comment by stubailo** [comment]
@themeteorchef we're addressing all of the use cases you mentioned and more in the Meteor routing guide being built here: https://github.com/meteor/guide/issues/15

**Comment by themeteorchef** [comment]
@stubailo you've answered the question here which is "what you see around the web every day." From a developer point of view, yes, just rendering a login template is fine. From a user point of view, however, the expectation is that I'd be redirected to a login page (as you say, this is what you see every day). The desire, then, with my request is to stay in stride with the user's expectation. 

Re: the desire to redirect to the proper page, this seems like it should be something left to the developer to consider. It's fairly trivial to grab the intended route and store it until the user logs in. Then we just take the stored value and send them to the route, solving the "dead end" redirect issue.

When we consider UX even further, if we're a logged in user and for some reason we go to `/login` (e.g. that's what our browser saved), it looks shoddy to see a page flash that says "you are already logged in." To see this, check out [kadira.io](https://kadira.io). Log in as a user and then visit `/login`. That is far from good UX as we're designing our flow per the behavior the developer _wants_ the user to take, not the behavior they might actually take.

Ultimately this seems like a matter of taste. The reason I brought this all up, though, is that if Arunoda's work is going to influence an official solution, that solution should lean toward the mean/average/expected, not the opinionated/developer preferred.

**Comment by VladShcherbin** [comment]
@themeteorchef I agree with you. If 99% websites redirect to login page - we also want to redirect (change url) to this page. We don't want to confuse the user. 

I've done all of this, you are writing about - the only thing I remembered - forget triggers, create the app as if you didn't have them. You can do very little with them, so you need to rely on template level.

> if I visit a route like `/admin`, ideally I'd be redirected to `/login`. Instead, I'm simply shown the `{{> login}}`

We have admin layout and render thins there. If you are still logging - show the spinner (template level). In admin template onCreated check, if the user is logging and if is not logged in - redirect to the login route.

> In addition to this, it's also tricky to implement things like redirecting logged in users away from public pages.

Similar here, check, if the user is logged in - don't show this login page and redirect to somewhere (dashboard, profile). Like so (in onCreated of the login template):

```js
if (Meteor.user()) {
  FlowRouter.go('admin.dashboard');
}
```

You can ask me some examples and I can probably create a repo with them on the weekend.

**Comment by themeteorchef** [comment]
@VladShcherbin I would love to see some examples if you're willing to take the time as this sounds like what I'm after.

**Comment by VladShcherbin** [comment]
@themeteorchef okay, here is the example [repo](https://github.com/VladShcherbin/meteor-flow-router-auth-redirects-example) and here is the [demo link](http://frar.meteor.com/). 

I showed, how to use template helpers for [login page](https://github.com/VladShcherbin/meteor-flow-router-auth-redirects-example/blob/master/client/views/main/auth/login.html) and then created the [block helper](https://github.com/VladShcherbin/meteor-flow-router-auth-redirects-example/blob/master/client/views/partials/if-logged-in.html) to not repeat the code and used it in other places, for example [profile page](https://github.com/VladShcherbin/meteor-flow-router-auth-redirects-example/blob/master/client/views/main/auth/profile.html).

I also added an [admin layout](https://github.com/VladShcherbin/meteor-flow-router-auth-redirects-example/blob/master/client/views/admin/layouts/admin-layout.html) to show, how to easily restrict all templates (admin, admin/users, admin/categories, etc).

Check the example, it has some files, but is actually simple. Feel free to ask questions.

*ps. In my apps for admin pages I don't redirect to login, but show the 404 to kinda more secure. Maybe you'll do it too.*

**Comment by themeteorchef** [comment]
Hey @VladShcherbin thank you for putting this together. This definitely makes the process a bit clearer.

**Comment by talha-asad** [comment]
@themeteorchef I think you really have a valid point.
