### ISSUE TITLE
Upgrade cosmos:browserify to newest version

### ISSUE THREAD

**Issue by steph643** [kadirahq/flow-router#346]
so that `meteor update` doesn't display a warning message.

Just for my information, why do you need cosmos:browserify?

**Comment by arunoda** [comment]
Already tracked here: https://github.com/kadirahq/flow-router/issues/333

We use it to get some npm modules into the client.

**Comment by steph643** [comment]
> We use it to get some npm modules into the client.

 No kidding?!   :-)

**Comment by arunoda** [comment]
ha ha :)

**Comment by talha-asad** [comment]
Which NPM modules are these? Cosmos:browserify makes the entire application really slow and i would love if flowrouter can run without it. This seems to increase the over development build time by a lot more time.

**Comment by arunoda** [comment]
@talha-asad I hope we could do it with the new NPM integration.
Will do this once 1.3 is out.
