### ISSUE TITLE
Dynamic prefix

### ISSUE THREAD

**Issue by kristijanhusak** [kadirahq/flow-router#347]
Hi,

Sorry for the long text, but it's really hard to explain the issue i'm having in short terms.

I'm trying to set up routes that needs to have dynamic prefix. So for example, take a user that can be a part of multiple companies. I need to use company id as a prefix. Here's how I achieved it:

```js
functon getActiveCompany() {
  return Companies.findOne({
    userId: Meteor.userId(),
    active: true
  });
}

var companyRoutes = FlowRouter.group({
  prefix: '/' + getActiveCompany(),
  name: 'company'
});

companyRoutes.route('/home', {
  name: 'home',
  action: function() { 
    // ... 
  }
});
```

This works great until user needs to change "active" company. At that point i run into some problems.
I need to reload whole app to update routes, with a custom url that i generate myself, something like this:

```js
'change #change-company': function(e) {
  Meteor.call('changeCompany', e.target.value, function() {
    window.location.href = '/' + getActiveCompany();
  }); 
}
```

Not ideal, but acceptable. Biggest problem occurs when i try to collect company id from the url, so i can check it if it's valid, and to update user's active company if company id is different from the currently active one (need that for url sharing, etc).
Since the prefix is kinda hardcoded, it's hard to retrieve it. So i tried using the optional variable as a prefix:

```js
var companyRoutes = FlowRouter.group({
  prefix: '/:company?',
  name: 'company',
  triggersEnter: [function(context, redirect) {
    var companyId = context.params.company;
    var company = Companies.findOne(companyId);
    var activeCompany = getActiveCompany();
    if (company) {
      if (companyId !== activeCompany) {
        Meteor.call('changeCompany', companyId, function() {
          redirect(context.route.name, context.params, context.queryParams);
        });
      }
    } else {
      redirect('/' + group + context.path);
    }
  }]
});
```
In this situation there is also several problems:

* This is an update to the existing app, that didn't have these groups, so i need to update all routes to use `company` param. When prefix is hardcoded, that is done automatically.
* `context.params.company` always returns first param. That mostly makes sense, but when i try to update the company param, when some other route is hit, it changes the path. 
So for example on `/home`, when i try to do `context.params.company = companyId`, then it redirects me to `/companyId`, but i want to go to `/companyId/home`. That is solved by the manual redirect that i done in the `else` statement.

The code above works, but it does redirection every time, because routes does not have `company` param on them. It's hardly noticeable, but can be seen sometimes. I'm using https://github.com/arillo/meteor-flow-router-helpers/ package, and mostly `pathFor` in the markup. 

It would be good if there could be a way to update group with some `setGroup` method, or something like that, even if it requires re-instantiating all routes.

Is there maybe a way to solve this? I'll gladly accept any suggestions.

Sorry for the long text once more.

**Comment by arunoda** [comment]
I see what's going on here. In FR, we can create routes dynamically. But not remove. Your first version, we are not sure whether data is available or not when the code is executing. So, then the route won't work properly. You can have also mentioned that you need to reload when the active company changed. yes you are correct.

Second option is also bad since, you are accessing data inside a trigger. So, there may be data in the trigger level or not. Since flow-router doesn't deal with data, it can't wait. So, it's hard to use a trigger for this her.

You only best option is to implement your logic in the template layer. Inside a template, you can check whether is the active company or not and you can do anything you want. 

You can get some ideas from here: https://kadira.io/academy/meteor-routing-guide/content/implementing-auth-logic-and-permissions

**Comment by arunoda** [comment]
I'm closing this because of an issue. But feel free to discuss.

**Comment by kristijanhusak** [comment]
I found a bit hackish solution, but it works for me. Sharing it so it maybe helps someone.

For routes, i track the data and then initialize it:
```js
// lib/router.js

function setupRoutes(companyName) {
  var companyRoutes = FlowRouter.group({
    prefix: companyName ? '/' + companyName : '',
    name: 'company'
  });

  // ... Other routes
}

if (Meteor.isClient) {
  Tracker.autorun(function() {
    var company = getActiveCompany();
    setupRoutes(company && company.slug);
  });
}

```

And in `main.js` i defer FR initialization, and initialize it after everything is set up:

```js
// client/main.js

// Stop auto initialization of router so we can set up company url later
FlowRouter.wait();

// We need to wait until subscription is finished so we can check if the
// company from url is valid and exists in the database.
Meteor.subscribe('companies', function() {
  var url = window.location.pathname;
  var segments = lodash.filter(url.split('/'));
  var companySlug = segments.length && segments[0];
  var company = companySlug && Companies.findOne({slug: companySlug});
  var currentCompany = getActiveCompany();

  // This allows changing active company by redirecting to url with the slug
  if (company && currentCompany && companySlug !== currentCompany.slug) {
    Meteor.call('changeCompany', company._id, function() {
      Meteor.defer(function() {
        FlowRouter.initialize();
      });
    });
  } else {
    Meteor.defer(function() {
      FlowRouter.initialize();
    });
  }
});
```

This still requires to reload whole app when company is changed, but that is acceptable for this complex situation.
