### ISSUE TITLE
Make proper scroll position adjustments

### ISSUE THREAD

**Issue by deanius** [kadirahq/flow-router#349]
It would be nice if this router would:

* [ ] Scroll to top on new route navigation with no hashtag, or `#`
* [ ] Scroll to an ID within document (once document subs are ready) with `#some-id`
* [ ] Ensure scroll position is remembered when returning back via History

This logic is currently available in the `okgrow:router-autoscroll` package, but I think it'd be nice if it were part of the router, if that were to fit with the minimal philosophy of flow-router. Personally, I think a UX that is not too surprising is appropriate for implementing in the package.

**Comment by arunoda** [comment]
This is a very important feature. But, this needs to deal with the data layer, for back button. 

May be it needs to wait for the data.  So, that's why this should live outside the router.
