### ISSUE TITLE
Flow Router ssr needs fast-render?

### ISSUE THREAD

**Issue by VladShcherbin** [kadirahq/flow-router#350]
Hey, when using flow-router-ssr and react, do we need fast-render to inject into html, will ssr work without it? What is the benefit? (populate the mini-mongo collection before the ddp connection established?)

**Comment by arunoda** [comment]
Actually, you don't need to use fast-render.  flow-router-ssr  will do it automatically. That's something required when doing React SSR. (We need to have the same data as on the server, when rendering components on the client)

**Comment by VladShcherbin** [comment]
I mean, when we use flow-router-ssr and react in *both* folder and view the page source - the components data is already there and the fast-render injected code is below. So the components have the data because of fast-render and this injected code?

**Comment by VladShcherbin** [comment]
Even when disabling javascript, we already get the html with the data, so it is rendered on server and sent with data? 

I may sound stupid, but I am trying the flow-router-ssr and react combo and want to understand, why we need fast-render (and injected data in `<script type="text/inject-data">`) if the components already come with data.

@arunoda maybe you can drop a line or two to make it more clear? I will be very grateful.

**Comment by arunoda** [comment]
Okay. let me add more :)

So with SSR, we have HTML coming from the server. Then there is a set of components rendered on the client, once React is booting on the client.

So, React needs to merge both the components in the HTML and generated on the client side. It use a checksum for that. If that checksums are different, it will clean the components comes with HTML and replace with client generated components.

That's why we need to have the fast-render powered data on the client. 

This is due to how to React works. But I hope this can be improved in the React framework level.

**Comment by VladShcherbin** [comment]
@arunoda oh, that definitely made everything clear.

The last question - the checksum of the components includes data and we need the fast-render data in `<script type="text/inject-data">` to compare checksums immediately and not wait until the data will come from ddp connection to compare with it. Am I right?

**Comment by arunoda** [comment]
Nope. Checksum is on each react component.
See: view-source:https://kadira.io/

**Comment by VladShcherbin** [comment]
@arunoda yes, I understood the same. 

So, basically to get rid of `inject-data` we could wait for all subs ready, grab the data, only then start React and then compare checksum. But it will be very long so we need fast-render to have the data immediately. And since the data will be the same (as html and injected data both come from the server at the same time), we actually compare, if the components code has changed.

**Comment by VladShcherbin** [comment]
@arunoda Thank you, I think I understood, why we need the fast-render and injected data.

I was a bit scared of all the data, injected to the bottom of html. But is seems, we can't get rid of it. At least for now.
