### ISSUE TITLE
When is action() actually called?

### ISSUE THREAD

**Issue by steph643** [kadirahq/flow-router#353]
The doc says:
> For a single interaction, the router only runs once. That means, after you've visit a route, first it will call triggers, then subscriptions and finally action. After that happens, none of those methods will be called again for that route visit.

This isn't quite true. For a same route (same route name), calling `setQueryParams()` will call `action` again.

**Comment by arunoda** [comment]
It's true.
Calling `setQueryParams()` changes the URL. Actually, it's a way to change the URL. That's a change in route.

**Comment by steph643** [comment]
What is a route? Is it a URL? Or is it what you define by calling `FlowRouter.route()`? 

Those are two very different things and your doc is unclear because it uses the first definition in some cases and the other definition in other cases.

Consider this route declaration:
```javascript
FlowRouter.route("/blog/:nb", {
    name: "myRoute",
    action: function(params) {
        //...
    }
});
```
Now consider these two URLs: `https://www.abc.com/blog/333`, `https://www.abc.com/blog/666`. They have the same route name "myRoute". But to you, do they refer to the same route or not?

If you clarify your vocabulary, I can issue a PR to update your doc.
