### ISSUE TITLE
Resource routes

### ISSUE THREAD

**Issue by VladShcherbin** [kadirahq/flow-router#363]
Hey, I've used resourceful routes previously and liked it. They are great for building CRUD things, like admin parts. So, basically, you can have 4 actions, but can use any number you specify (1-4). So you do something like this: 

```js
FlowRouter.resourse('permissions', {
  name: 'admin.permissions',
  actions: {
    index() {
      ReactLayout.render(Layout, {content: <PermissionsIndex />});
    },
    create() {
      // ...
    },
    show() {
      // ...
    },
    edit() {
      // ...
    }
  }
});
```

And you have the routes for specified actions:

| url | route name  |
|---|---|
| permissions | admin.permissions.index |
| permissions/create  | admin.permissions.create |
| permissions/{title} | admin.permissions.show |
| permissions/title/edit | admin.permissions.edit |

What do think about it?

**Comment by arunoda** [comment]
This could be build on top of the FlowRouter, but not into flow-router. We won't add more functionalities to routing (at least for 4.x)

**Comment by arunoda** [comment]
BTW: Thanks for bringing this :+1: 
But, I again think it's good to stay this outside of FR.

**Comment by VladShcherbin** [comment]
@arunoda sure, I'll try to create it on top of FlowRouter.

Maybe you'll like the idea after some time, I liked using it a lot before ;)
