### ISSUE TITLE
Use object or function as data does not work

### ISSUE THREAD

**Issue by TomFreudenberg** [kadirahq/flow-router#364]
Hi, I would like to send an anonymous function as template creator to my layout instead of invoking via string:

This what I wish to do:

````
FlowRouter.route('/demo/', {
  action: function(params) {
    BlazeLayout.render('appLayout', { component: function() { return pageDemo } });
  }
});
````

and inside my layout.html:

````
<template name="layout">
 {{> React component=component }}
</template>
````

But this won't work, also I added to the layout.js:

````
Template.layout.helpers({
  component: function() {
    return Template.instance().component()();
  }
});
````

Either no success. Now I solved with custom field to FlowRouter object

````
FlowRouter.route('/demo/', {
  reactComponent: function() { return pageDemo } },
  action: function(params) {
    BlazeLayout.render('appLayout', { } );
  }
});
````

````
<template name="layout">
 {{> React component=component }}
</template>
````

````
Template.layout.helpers({
  component: function() {
    return FlowRouter.current().route.options.reactComponent();
  }
});
````

Is this what you expect?

Thanks for short note
Tom

**Comment by TomFreudenberg** [comment]
Hi @arunoda 

May you be able to give me a short feedback if I do right with the second approach?

Thanks in advance for your statement
Tom

**Comment by arunoda** [comment]
Hmm. I've never tested passing callbacks. But I think that's because of our use of ReactiveDict inside the layout. Which does not support functions. 

I think the way is to pass as an options. You can pass features like that and it's supported.

**Comment by TomFreudenberg** [comment]
Hi @arunoda , thanks for your feedback and the positive answer to support it :-)

Cheers
Tom
