### ISSUE TITLE
Set global layout 

### ISSUE THREAD

**Issue by almogdesign** [kadirahq/flow-router#366]
Is it possible to set layouts for all routes I'm using blaze and have the following. It feels wrong to have to set the layout for each route? 

FlowRouter.route('/dashboard', {
    action: function() {
        BlazeLayout.render("layoutApp", {header: "appHeader", main: "appMain" });
    }
});

**Comment by arunoda** [comment]
Nope. We don't have features for that. You can simply create simple wrapper to do what you wanted.
