### ISSUE TITLE
Server is not aware of any routes

### ISSUE THREAD

**Issue by johanbrook** [kadirahq/flow-router#368]
Thanks for a great package!

I get that FlowRouter is a client side router. But sometimes, it's nice that the server is *aware* of just the routes, but lets the client do everything else.

One scenario is when you have a route structure

```
/about
/api
/:slug
```

where you want to prevent `slug` to take any value of an existing route (`about` or `api`). This validation should be made on the server, and currently, I either have to duplicate the path names in the server validation, or do some haxxery where I define the routes in one place and register them to some global array on the server.

Would be interesting to hear thoughts on this. Since Meteor uses isomorphism, in all its glory, I think it would be valuable to use that :)

**Comment by arunoda** [comment]
Yep. Basically, that's what we will have in the next version. 
I will close this since we will track it in different issues. Mainly with the combination of 

* SSR
* Server Side redirects and 404s

**Comment by johanbrook** [comment]
Gotcha, thanks :boom:
