### ISSUE TITLE
FlowRouter.path lookup by route name returns route name instead of path

### ISSUE THREAD

**Issue by satyavh** [kadirahq/flow-router#371]
on the server, this:
`FlowRouter.path("blogPostRoute", params, queryParams);`

conveniently returns this:
`"blogPostRoute"`

haven't tested on client.

**Comment by arunoda** [comment]
Is this on the server? Would love to have some sample code.

**Comment by satyavh** [comment]
Yes, on the server. But I tested on client and it's also not correct. 
Sample code is nothing special:

on client, route definition
```
FlowRouter.route '/password/reset/:token',
  name: 'resetPassword'
  action: ->
    BlazeLayout.render "resetPassword"
```

on server
```
FlowRouter.path('resetPassword', { token: '1234' });
```
returns `"resetPassword"` instead of `/password/reset/1234`

on client
```
FlowRouter.path('resetPassword', { token: '1234' });
```
returns `/password/reset` instead of `/password/reset/1234`

**Comment by arunoda** [comment]
It's working pretty well here: https://github.com/arunoda/hello-react-meteor/blob/master/both/router.jsx
I don't write coffeescript. I suspect this is a syntax issue.
May be someone could help.

**Comment by satyavh** [comment]
Na, I don't think so, it compiles to:
```
FlowRouter.route( '/password/reset/:token',  {  
  name: 'resetPassword',                                             
  action: function() {                                             
    return BlazeLayout.render("resetPassword");         
  }                                                               
}); 
```
But I'll make a repro in javascript for testing. Maybe another package is interfering or something. I'm on `v2.7.0` by the way.

(FYI, kind of another topic, but how I found out is because I'm helping `lookback:emails` to support FR as well as IR. It will use Picker on server side instead of IR, but it has some template helpers that will use either IR or FR. Perhaps it would be interesting to keep a list of packages that support FlowRouter. I'm sure more packages will be migrating).

**Comment by arunoda** [comment]
Hmm. Give me a repo. I'll digg into it.

**Comment by satyavh** [comment]
Here it is: https://github.com/satyavh/Flowrouter-test
It works correct on client, not on server. Check console in browser and terminal for logout

**Comment by arunoda** [comment]
It will have a look at this.

**Comment by arunoda** [comment]
This is because, you've only created routes in the client. You need to create routes in a place where it can be seen by both the client and the server.

Here's the fixed app: https://gist.github.com/arunoda/d1247f829f701babf597

**Comment by satyavh** [comment]
Well, that explains! As Flow Router is client only, I never thought about putting routes somewhere where the server can see them as well. But makes sense. Thanks for checking!
