### ISSUE TITLE
FlowRouter.go => How: getInitialState ?

### ISSUE THREAD

**Issue by Mindgames** [kadirahq/flow-router#372]
Pretty new on both Meteor and React so would like to know how to do **getInitialState** correctly after using **FlowRouter.go** the correct way. 

## My current setup is something like this 

    // Initial State

    getInitialState: function () {
      if (_.include(this.props.video.upvoters, this.props.userId)) {
        return {like: true}
      } else {
        return {like: false};
      }
    },

    // dissLike

    handleDissLike: function (event) {
      this.setState({dissLike: !this.state.dissLike});
      Videos.update({_id: this.props.video._id}, {
        $pull: {upvoters:this.props.userId
        },
        $inc: { votes: -1} });
        setTimeout(() => {
          FlowRouter.go('/video/' + this.props.next);
        }, 2500)	;
        
      },

So when accessing url directly or by href is will trigger **getInitialState** but when using **FlowRouter.go** it don't seem to work.  

If anyone would be kind to explain the correct way to do this is would be to huge help to get me on the right track. 

using FR SSR 

### This is my route

     FlowRouter.route('/video/:_id', {
        name: 'video',
        action: function(params, require) {
          ReactLayout.render(VideoLayout, {
           content: <VideoPage _id={params._id} />
        });
      }
    });

**Comment by arunoda** [comment]
Could you ask this question on Meteor Forums? I hope this suits there.

**Comment by Mindgames** [comment]
@arunoda sure. thing is just that i ended up without answers on question when asking on Meteor forum and also Stackoverflow before when asking some questions about correct solutions, that's why i did go directly to creators when i did have this question, But now am not getting answer here either. 

I have put it on Meteor forum [here](https://forums.meteor.com/t/flowrouter-go-how-getinitialstate/12427) and it would be nice if you could just write a sort answer on it.

**Comment by arunoda** [comment]
Okay. Sure.

**Comment by Mindgames** [comment]
Thank you !

**Comment by Mindgames** [comment]
@arunoda Guess this is one of the biggest issues that none of the people that have the answers about React + Meteor + Flowrouter questions will answer them. Have seen the same both on Meteor forum and Stackoverflow, People ask questions but there is no one there to answer them. 

If enough people would know the answer the would be people there to answering this questions also.  You can build the world's greatest product and put your heart into that but for it to really fly it's as important to educate people how to use it.   

Put all your team's focus over just one week to mass produce tutorials and examples, as many as possible and put em out there, and i promise you that there will be a significant change in the growth curve. Now people get stuck in something, there is none information about this to find and on top of that while searching for this information they will end up on articles and posts where people doubt the future of Meteor.  I would say that most people starting with Meteor now will go straight to Meteor + React. 

Some frustration over now getting any answer on my question and also some very important facts that can be hard to see while putting all the focus on developing the product.  

Otherwise great products! Keep that up !

**Comment by arunoda** [comment]
@Mindgames thanks for the ideas.
We know how to educate and do [documentation](https://github.com/kadirahq/flow-router). 
But, we assume users have sound React knowledge before using FlowRouter + React Layout. We don't have resources to answer all those questions.

There are plenty of people building Meteor apps with React and FlowRouter. And there are a lot of people building apps with Meteor and React. They hangout on Stackoverflow and Meteor Forums a lot helping others.

And it seems like your question didn't get answered. That means, you **haven't done a good job** asking your question. Basically, when asking a question you should provide enough materials to reproduce your bug. 

Most of these people are work on volunteer basis and they don't loose their job if they don't answer your question.

**Comment by Mindgames** [comment]
@arunoda think the question was kinda straight forward.  Why does getInitialState not work when using FlowRouter.go.

Will not argue about it anymore, it was just my point of view.
