### ISSUE TITLE
No `FlowRouter.url()` function

### ISSUE THREAD

**Issue by johanbrook** [kadirahq/flow-router#373]
While migrating from Iron Router, I discovered that there is not `FlowRouter.url()` function, which in contrast to `FlowRouter.path()` returns the absolute URL, and not just the path. Currently, we have to resort to an in-app helper. Personally, I think this is something a router should take care of.

Is this a deliberate decision? If not, I'd be happy to provide PR + tests.

Thanks!

**Comment by arunoda** [comment]
Okay. There was no reason not to include that. Yeah go for it.

**Comment by jreinert** [comment]
@johanbrook are you still on this? I added this functionality + tests before I read this issue. I don't want to step on your toes :)

**Comment by johanbrook** [comment]
@jreinert Cool, great! No worries at all – my own fault for being busy the last two days ;) File a PR and we're done :+1:

**Comment by arunoda** [comment]
PR already submitted.
