### ISSUE TITLE
Possible issue with manually changing URL in browser address bar?

### ISSUE THREAD

**Issue by awei01** [kadirahq/flow-router#376]
Hi, I'm using FlowRouter with hashbang support. When I manually type in a hash after the `#` and hit enter, I'm always routed to the `404` handler. Is this by design?

**Comment by arunoda** [comment]
Please send me a sample repo. I'll work on it.

**Comment by awei01** [comment]
Here is repo: https://github.com/awei01/flow-router-issue-376

**Comment by arunoda** [comment]
I got this error something when manually changing. But a hard reset work pretty well and even when I copied into another tab it loads correctly.

So, in practical sense, this won't be an issue. Because of that, I'll close this issue.
But if it's not please re-open this.

**Comment by arunoda** [comment]
Anyway, If you can figure out the issue, just send us a PR.
