### ISSUE TITLE
Tooltip position does not adjust when in modal

### ISSUE THREAD

**Issue by ntoka** [kadirahq/flow-router#380]
Hi, I have a problem with using chartist horizontal bar chart + tooltips on materialize CSS modal. When in modal, the position of the tooltip does not adjust to the position of the modal. What i mean is - when modal is loaded - tooltip appears where it should be, but when i scroll down a bit - the tooltip remains in the old position. How could I fix this?

**Comment by arunoda** [comment]
Please ask this on Meteor Forums.
