### ISSUE TITLE
FlowRouter.getParam() returns undefined in triggersEnter

### ISSUE THREAD

**Issue by francisbyrne** [kadirahq/flow-router#381]
I've noticed that the route params don't appear to be set until after the trigger runs, meaning that any code running within the trigger doesn't have access to the params.

**Comment by arunoda** [comment]
In a trigger you can access it via the first argument passed to it. Use that.
see: https://github.com/kadirahq/flow-router#defining-triggers-for-a-route

This is a known issues and will be fixed in the next major version.

**Comment by francisbyrne** [comment]
Ah awesome, thanks for the speedy response!
