### ISSUE TITLE
Firefox warning is being assigned a //# sourceMappingURL, but already has one

### ISSUE THREAD

**Issue by mishavee** [kadirahq/flow-router#382]
A warning is appearing in the Firefox browser console. The warning does not appear in the Chrome browser.

Versions:
meteor 1.1.10
kadira:flow-router    2.8.0
Windows 8.1
Firefox 42.0

Steps to reproduce:

1. Type into commandline...
> meteor create show-flow-router-issue
> cd show-flow-router-issue
> meteor add kadira:flow-router
> meteor run

2. Open Firefox to http://localhost:3000

3. Open Firefox's console (F12)

4. The warning is shown:
http://localhost:3000/packages/kadira_flow-router.js?a6367e77bad3de124f7b04305e29a8199770a42e is being assigned a //# sourceMappingURL, but already has one kadira_flow-router.js:2462:4

**Comment by mishavee** [comment]
There is a (fixed?) bug in Firefox that is related: [bugzilla 1020846](https://bugzilla.mozilla.org/show_bug.cgi?id=1020846)
Also this bug: [bugzilla 925614](https://bugzilla.mozilla.org/show_bug.cgi?id=925614)
Potentially useful discussion here: [stackoverflow 21759662](http://stackoverflow.com/questions/21759662/file-is-being-assigned-a-sourcemappingurl-but-already-has-one)

**Comment by arunoda** [comment]
So, seems like we don't need to do anything?

We are not doing anything related to source maps other than using Meteor's build system.
I'm closing this. But if we need to do anything else, just reopen.

**Comment by mishavee** [comment]
Thanks for looking into it.  Does this mean there is a bug in either the build system, or in Mozilla?

**Comment by arunoda** [comment]
Could be one over another. This is what I tell you.
Try to create a sample repo with the bug and submit an issue to the meteor github repo.
I assume, they'll know how to take a better look at this.
