### ISSUE TITLE
Docs fo alternative layouts

### ISSUE THREAD

**Issue by niallobrien** [kadirahq/flow-router#385]
Hi, I'm wondering if you could document what is required exactly to support an alternative to BlazeLayout and ReactLayout. I'm specifically interested in supporting Vue.js whose custom components are somewhat similar to React, but with a much lower learning curve. Thanks.

**Comment by arunoda** [comment]
We should.
Actually, there is nothing related to FlowRouter you need to aware. 
You need to provide an API, where users can call inside the `.action` method.

This is not a rule. But it's better it will manage how to render components to the DOM. User does not need to provide that. But possible to do, if he needed.

Here's the one I wrote for React. It's less than 100 lines. 
See: https://github.com/kadirahq/meteor-react-layout/blob/master/lib/react_layout.js

**Comment by niallobrien** [comment]
Thanks @arunoda - and ReactLayout handles nested components with no problems?

**Comment by arunoda** [comment]
Actually, React Layout does not do it. But there are some patterns to use it. I should link them on the README.

See: https://forums.meteor.com/t/how-to-pass-reactive-data-to-children-using-flow-router-and-react-layout/11888/4?u=arunoda

**Comment by niallobrien** [comment]
Do you think it'd be relatively easy to write a layout renderer for Vue.js?

**Comment by arunoda** [comment]
Sorry for the delay. Yes it should be easy. Although, I haven't tried it out.

**Comment by arunoda** [comment]
I'm going to close this, but let's discuss.
