### ISSUE TITLE
FlowRouter.reload() not reloading the same page

### ISSUE THREAD

**Issue by chintaladheeraj** [kadirahq/flow-router#386]
Hello,

I am trying to reload a page after using FlowRouter.reload(). But it is not working when I am trying to reload the same page on which I am in. I checked the FlowRouter documentation. But it says it will reload (different from go and redirect). Am I missing something here?

**Comment by arunoda** [comment]
Reload simply runs the action again in the route definition. It's not reloading the page.
If you've anything just let me know with a sample repo.
