### ISSUE TITLE
Router for serving static files

### ISSUE THREAD

**Issue by mitar** [kadirahq/flow-router#387]
A followup to #235, because it is locked.

I think the current approaches to make links to server-side files is very limited. It is really hard to dynamically make sure that links have `ref` or some other attribute when links are supplied by the user. In our case, we have a rich-text editor where user can supply a link. Now, that link can be to an external page, to internal page, or to server-side file. Now with current approach we would have to parse all links and change how they are rendered just so that we can add necessary attribute. It would be much easier if we could say that for example, everything under `/uploads/` should not be processed by flow-router/page.js. This is then configured in one place, near routes, instead of having this all around the place.

It would be also cool if this could be enabled automatically for all client-side assets and files in app's `/public/` directory.

**Comment by mitar** [comment]
I made a #389 pull request.

**Comment by arunoda** [comment]
I started a discussion on the PR.
