### ISSUE TITLE
Compress html

### ISSUE THREAD

**Issue by vanoorschot** [kadirahq/flow-router#391]
Enable html compression for every page that is served.
Maybe combine this with the default caching?

In my current project this would reduce the transfer size by 91%.

**Comment by arunoda** [comment]
This needs to be done outside of the FR. May be with a proxy like nginx.

**Comment by Primigenus** [comment]
@arunoda The app in question is being hosted with Modulus at the moment, which apparently doesn't support nginx. Any thoughts on how to proceed?

**Comment by arunoda** [comment]
Okay. Then the best way is to use CloudFlare: https://blog.cloudflare.com/an-all-new-and-improved-autominify 

You can write a connect middleware(or picker) to do that also.
