### ISSUE TITLE
FlowRouter.current().route.group.name

### ISSUE THREAD

**Issue by ashishapy** [kadirahq/flow-router#394]
I am trying to get group name but it always return 'undefined'.
Codes are as below
*onboardingLayout.js*
```
Template.onboardingLayout.helpers({
	title: function () {
		var groupName = FlowRouter.current().route.group.name;
		console.log(groupName);
	}
})
```
*Route.js*

```
var contributorSection = FlowRouter.group({
    prefix: "/contributor"
});

// Contributor onboarding routes
var contributorOnboarding = contributorSection.group({
  prefix: "/onboarding",
  triggersEnter: [AccountsTemplates.ensureSignedIn]  
});

contributorOnboarding.route("/profile", {
  name : "contributorOnboardProfile",
  action: function(params) {
    BlazeLayout.render("onboardLayout", {navBar:"headerUser", navOnBoard:"contributorOnboardNav", main: "contributorProfile"});
  }
});
```
group name is always undefined. Seems group nam is not working.

**Comment by pahans** [comment]
hi @ashishapy i tried this one. But could not reproduce the issue. may be you are using a older version of flow-router which doesnt include this  (https://github.com/kadirahq/flow-router/pull/290) fix

**Comment by ashishapy** [comment]
Thanks @pahans for your response.
I am using latest FlowRouter also I don't need my help to be reactive.

I just updated my code to use ```FlowRouter.current().route.group.name; ``` still it is not working :(

**Comment by pahans** [comment]
@ashishapy can you build a sample repo with your code? I will look into it. thanks

**Comment by ashishapy** [comment]
I am able to solve by changes code as below.

```
var contributorSection = FlowRouter.group({
    name: "contributor",
    prefix: "/contributor"
});
```
&

```
var groupName = FlowRouter.current().route.group.parent.name;
```

so basically I added "name" property in group 

& instead of getting "group.name", I changed it to "group.parent.name"
