### ISSUE TITLE
FlowRouter.path does not have a slash on server while it has on client

### ISSUE THREAD

**Issue by dbismut** [kadirahq/flow-router#400]
Hi, I've noticed that `FlowRouter.path('dashboard')` will return `/dashboard` with a slash on the client, and `dashboard` with no slash on the server. Is that normal behavior?

**Comment by pahans** [comment]
make sure your routes are defined in a shared directory to server and client. example : `<project_root>/lib/routes.js`

**Comment by dbismut** [comment]
Ok thanks! Indeed, my routes were defined on the client-side only.I'll close the issue. Thanks again.
