### ISSUE TITLE
Option to disable Fast render in flow router SSR ?

### ISSUE THREAD

**Issue by fabien-h** [kadirahq/flow-router#402]
For a particular project, I'd like to disable fast render in flow router. Could we have a way to do that ? I've just commented the following code :

    // process null subscriptions with FR support
    //Picker.middleware(FastRender.handleOnAllRoutes);

        // get the data for null subscriptions and add them to the
        // ssrContext
        // var frData = res.getData("fast-render-data");
        // if(frData) {
        //   ssrContext.addData(frData.collectionData);
        // }

And it works. But if it could be a parameter like deferScriptLoading, it would be great.

**Comment by arunoda** [comment]
Okay. Then remove Fast Render from your project.

**Comment by fabien-h** [comment]
It's a project with flow router SSR.

For reasons I really do not understand, for a logged user, it sends the user data multiple times and it makes the whole servr unstable. The websocket connection for the user resets randomly. When I remove the informations send by fast render, the whole thing is more stable.

**Comment by arunoda** [comment]
I'd love to see a sample repo where I can see what's going on here. I think there is more to this. For SSR, Fast Render is must to have.

**Comment by arunoda** [comment]
Could you ask this on the FlowRouter repo.
