### ISSUE TITLE
Add eslint support

### ISSUE THREAD

**Issue by arunoda** [kadirahq/flow-router#404]
I really like facebook's graphql eslint rules and we use them in couple of projetcs.
See: https://github.com/graphql/graphql-js/blob/master/.eslintrc

But, I'm open to some other set of rules as well. Meteor also seems to  be using their own set of rules as proposed(or will  be) on the [Meteor Guide](https://github.com/meteor/todos).  We can use that as well.

I heard, in Meteor there is a built in linting tooling in the build API. May be we can use that as well.

**Comment by johanbrook** [comment]
We use:

- https://github.com/dferber90/eslint-plugin-meteor
- and the `meteor` environment in ESLint (adds support for a bunch of Meteor globals).

**Comment by arunoda** [comment]
Thanks @johanbrook I like to use the eslint config used in the Meteor Guide: https://github.com/meteor/todos
Would you interest working on this?

**Comment by acemtp** [comment]
I really like the airbnb style guide, (20 000+ star on github) https://github.com/airbnb/javascript

**Comment by johanbrook** [comment]
@arunoda Yeah, I can have a look at this.

**Comment by arunoda** [comment]
Thanks @acemtp. I would use it sure for non-meteor projects.
Since this is a Meteor project, I like to use the one recommended in the Meteor Guide.

**Comment by arunoda** [comment]
@johanbrook Awesome. I'll assign this to you.

**Comment by johanbrook** [comment]
@arunoda :zap: :+1:
