### ISSUE TITLE
Is `triggersEnter` reactive?

### ISSUE THREAD

**Issue by AlexFrazer** [kadirahq/flow-router#405]
Let's say I have this:

```
FlowRouter.triggers.enter([function (context, redirect) {
  if (!Meteor.loggingIn() && !Meteor.userId()) {
    redirect('Auth.login');
  }
}], { except: 'Home' });
```

Would this work _reactively_? I don't know how to tell.

**Comment by arunoda** [comment]
No it's not. Non of the things inside FR is reactive.
For this you need to do, template level redirects.

**Comment by AlexFrazer** [comment]
Alright cool, thanks for the help, Template level worked fine
