### ISSUE TITLE
Packaged versions no "/" warning leads to concerns of no Overwriting of Routes issue

### ISSUE THREAD

**Issue by MasterJames** [kadirahq/flow-router#408]
Pardon me I’m knew to this one.
When running FlowRouter (FR) in a package (to ultimately access the Admin panel for the tool), and the containing app is not using FR, they get the warning essentially saying no “/” route.
Or they have to add flow-router etc. It seems like that would be irritating to some.
The simplest solution would be to remove the warning. [Maybe if it knew it wasn’t in a plugin?]
Maybe there’s a simple way I’m not aware of being new to this?
I ending up doing this…

    if(jQuery.grep(FlowRouter._routes, function(r){ return r.path === "/"; }).length === 0) {
        FlowRouter.route('/');
    }

but it must beat the outer code’s attempt to create the route “/” and then theirs (the user of the package) won’t work even though I thought this code above would detect it if the outer layer called first, and this code cannot overwrite of course.
Possibly Routes should be over-writable if they’re not already, and am I missing something obvious? Or is there a way to do something in an API kind of way?

It’s seems for now the warning will always be there, as "/" route can’t be overwritten (by the parent meteor app of the package). From what it currently appears to me.

Maybe it's a security concern that you can't on purpose?
Is this snippet a good method if overwriting were possible?
Anyway I think it’s maybe possibly easiest to suppress the warning message. I realize it isn’t really a big deal, but used as a package it’s maybe problematic, because of possibly what appears to be a more important overwrite issue, so maybe a simple overwrite ability and/or warning would be better.
Let us know what you think is best here, thanks?

**Comment by arunoda** [comment]
Someone should not FlowRouter and Iron Router or something similar together.
That may be the reason for this. But, I'm not sure.

For me this seems like user does not add a "/" route to the app. 
Am I missing something?

**Comment by MasterJames** [comment]
If I put FlowRouter routes commands into a Package with

    window.addEventListener("load", start);

starting from any path entered in the URL field of the browser FlowRouter will generates this error

    There is no route for the path: /

For all the routes paths even if they are there and working (once it's up).
I do this to grab everything in body but the blaze-root via jQuery "body *:not(#__blaze-root)"
so that needs to happen when loaded.

I think the best solution is to remove the error message completely or be able to suppress it, and again if there's anyway to tell it's running from inside a plugin, or at least just during the initial startup url.

**Comment by methodbox** [comment]
As a general practice, I would avoid Atmosphere or other Meteor packages which themselves use or depend on a specific router.
That's a very strange and likely commonly-breaking dependency.
