### ISSUE TITLE
Query parameters not parsed after hash change

### ISSUE THREAD

**Issue by alethes** [kadirahq/flow-router#409]
**Example**
Route definition: `FlowRouter.route('/');`
Initial URL: `http://hostname/?a=1`
Browser console output:
```
> FlowRouter.getQueryParam('a');
< "1"
> location.hash = 'h'; // or '#h', '#', '#!' etc.
> FlowRouter.getQueryParam('a');
< undefined
> FlowRouter._current.queryParams;
< Object {}
```

If the URL contains a hash during the initial page load (eg. 'http://hostname/?a=1#hash') the query parameters are parsed correctly.

**Comment by alethes** [comment]
In `client/router.js`, `route._actionHandle` passes `context.querystring` to the qs parse function (https://github.com/kadirahq/flow-router/blob/master/client/router.js#L80).

Using `location.search` to get the query string seems to fix the issue (https://github.com/alethes/flow-router/blob/master/client/router.js#L80-L84).

**Comment by arunoda** [comment]
Okay. We will update to the latest version of page.js soon. I hope that'll has a fix. If not, let's see.

**Comment by arunoda** [comment]
This is fixed in the FlowRouter SSR version.
