### ISSUE TITLE
Write tests for SSR Context

### ISSUE THREAD

**Issue by arunoda** [kadirahq/flow-router#416]
Follow this guidelines: https://kadira.hackpad.com/Flow-Router-SSR-Test-Cases-mNISky5l8YE#:h=Guide-to-Writing-Tests

Here are the test cases: https://kadira.hackpad.com/Flow-Router-SSR-Test-Cases-mNISky5l8YE#:h=SSR-Context

Here's the file: https://github.com/kadirahq/flow-router/blob/ssr/server/ssr_context.js

**Comment by thinkholic** [comment]
@arunoda - I'll do this.

**Comment by arunoda** [comment]
Awesome.
