### ISSUE TITLE
Create tests for Server Group

### ISSUE THREAD

**Issue by arunoda** [kadirahq/flow-router#420]
Follow this guidelines: https://kadira.hackpad.com/Flow-Router-SSR-Test-Cases-mNISky5l8YE#:h=Guide-to-Writing-Tests

Here are the test cases: https://kadira.hackpad.com/Flow-Router-SSR-Test-Cases-mNISky5l8YE#:h=Group

Here's the file: https://github.com/kadirahq/flow-router/blob/ssr/server/group.js

**Comment by elie222** [comment]
I don't think anything needs to be done here. Group on the server doesn't do anything on the server that Group on the client doesn't do. The common tests should cover Group on the server.

**Comment by arunoda** [comment]
Okay. If you are moving them, follow the `__tests__` directory format.

**Comment by elie222** [comment]
I'm not moving the tests right now. I'm saying that no extra tests have to written for group on the server. Group.js is basically an empty file.

**Comment by arunoda** [comment]
Okay. We can do it later.

**Comment by tjmonsi** [comment]
Should we still use Tinytest or just use the describe package on this? If the latter, then we all put it on __tests__ folder now? 

How about the tests in the client side?

**Comment by arunoda** [comment]
We need to use `describe` package.
Now we put tests on the `__tests__` directory on each source directory.
See some existing tests: https://github.com/kadirahq/flow-router/blob/ssr/server/__tests__/ssr_context.js

Don't worry about client side tests for now. We'll move them later on.

**Comment by tjmonsi** [comment]
Ok I guess I'll help with the tests as of now. I still am a newbie on the internals of FlowRouter and I easily got overwhelmed on the other issues here in 4.0. I'll do this one and follow the test cases set in the /server/__tests__/ssr_context.js and also look in the /test/group.js for reference

**Comment by arunoda** [comment]
Awesome.

**Comment by tjmonsi** [comment]
I've sent a pull request on adding the Server group SSR test. I can rewrite the whole client test cases in BDD format and then put them inside the client folder if you are down with that :)
