### ISSUE TITLE
FlowRouter.go inside Template.onCreated doesn't change URL

### ISSUE THREAD

**Issue by fabyeah** [kadirahq/flow-router#425]
Example:

    FlowRouter.route('/posts-home', {
      name: 'postsHome',
      action: function() {
        BlazeLayout.render('mainLayout', {
          content: 'postsHome',
        });
      },
    });

    Template.postsHome.onCreated(function() {
      var post = Posts.findOne();
      if (post) {
        FlowRouter.withReplaceState(function() {
          FlowRouter.go("post", {postId: post._id});
        });
    });

When I go to the ```postsHome``` route, it will redirect to the ```post``` route, but the URL won't change. I have to wrap the ```FlowRouter.go()``` inside ```Meteor.setTimeout(function() {...}, 0)``` to make it work. (not sure if this will only work locally or in production with slow network, too)

Is this the expected behavior?

**Comment by arunoda** [comment]
Redirects inside onCreated has some issues and this is something a known issues in the current version. We fixed this in the next major version. 

We'll get this in 4.0.

**Comment by fabyeah** [comment]
Thanks for the info.
Is there a workaround? Will Meter.setTimeout with 0ms delay work?

**Comment by arunoda** [comment]
Yeah. That works.
