### ISSUE TITLE
SSR for SEO only possible?

### ISSUE THREAD

**Issue by timothyarmes** [kadirahq/flow-router#430]
Hi,

I've been experimenting with flow-router-ssr on my project.

Unless I've misunderstood, flow-router-ssr currently renders every requested route on the server and sends that down the HTML on the initial page render. 

I would like to prohibit this behaviour for a few reasons:

1) The SSR rendered image on my site is different to that rendered on the client since I don't wish to render things likes Google Maps on the server. This leads to a warning on every page load:  "Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. "

2) Since the SSR page and the locally rendered page are difference, I don't wish to use up server resources rendering pages unnecessarily for every single initial request made to the server.

However, I **would** like to use SSR to render pages for SEO purposes. In my case the page would be rendered without the Google Map, but I don't care since that won't effect the SEO. So I only what the FlowRouter to render when it sees the ?_escaped_fragment_ parameter.

Is that possible now?

Tim

**Comment by arunoda** [comment]
There is no way to handle it for `escaped_fragment` and it's also not supported now.

What you can do it, handle your map related content on `componentDidMount` is react. That's not called on the server.

We'll have more control over SSR usage with the 4.0 release.
