### ISSUE TITLE
SSR not waiting for data

### ISSUE THREAD

**Issue by timothyarmes** [kadirahq/flow-router#431]
Hi,

My  `getMeteorData()` looks something like this:

```javascript
getMeteorData() {

   const sub = Meteor.subscribe('mySub')
   console.log('subscribed');   

   const result = Meteor.find().fetch()
   console.log(result);   

   return { result }
}
```

Rendering on the client works correctly, however on the server the result is always empty, so the SSR rendered data is null.

The publish code is slightly unusual in that I'm using an aggregation and pushinh the results to the collection manually:

```javascript
   const result = OKKs.aggregate(options);

   if (result != null) {
      for (let item of result) {

         // Add the result to the subscription.
         console.log(item);
         sub.added('okks', item._id, item);
      }
   }
```

Here I can see that the items are successfully added to the subscription **before** the call to subscribe returns, so the console looks like this:

    { item 1 }
    { item 2 }
    { item ... } 
    subscribed
    []

Why is the result of the find still empty?

I've noticed when doing SSR that components aren't rerendered with the results of async callbacks, so I assume that FlowRouter is waiting for data from any subscriptions before allowing the rendered to happen. Is my unusual subscription causing an issue?

Tim

**Comment by arunoda** [comment]
This is a custom publication. So, you need to call sub.ready() after initial set of data has been added. 

If that doesn't worked out, try to create a sample repo and send it. You can fork and use my hello-meteor-react project.

**Comment by timothyarmes** [comment]
Sorry, I didn't show all the code. I am calling sub.ready(). I'll see if I can create the repo.

**Comment by timothyarmes** [comment]
Hi,

As requested, here's a repo:

https://github.com/timothyarmes/hello-react-meteor

With JS turned on it works as before. With it turned off there's no published data.

Regards,

Tim

**Comment by arunoda** [comment]
I'll check this.

**Comment by arunoda** [comment]
Yep. I think there is an issue here. 
I'll check the issue.

**Comment by arunoda** [comment]
Had a bug in FastRender and fixed it. Try updating to the latest version of flow-router-ssr (v3.7.0)

**Comment by timothyarmes** [comment]
Thanks, that's fixed it.
