### ISSUE TITLE
Wildcard support

### ISSUE THREAD

**Issue by TimoRuetten** [kadirahq/flow-router#432]
Will there be a stable Wildcard support ? The wildcard support in iron:router was buggy.

Something like:

route('/myRoute/:wildParams(.*)') and wildParams will return an array of params or smth like that.

**Comment by arunoda** [comment]
We use path-to-regexp behind the scenes. You can write regular expressions in path.
See: https://github.com/pillarjs/path-to-regexp/blob/master/test.js#L754

See more info:  https://github.com/pillarjs/path-to-regexp

**Comment by TimoRuetten** [comment]
@arunoda Excellent! Now it works ... maybe I've done a mistake before so I thought the FlowRouter does not support RegEx. Thanks :) Works Fine :+1:
