### ISSUE TITLE
Internationalization ?

### ISSUE THREAD

**Issue by laurentpayot** [kadirahq/flow-router#441]
Here in Europe internationalization (i18n) is a real need. I can't switch to flow-router if I can't have language-customized routes, because URLs matter (SEO, bookmarks etc.).
Unfortunately it looks like people from iron-router-i18n won't help for flow-router i18n as once hoped in #45 a long time ago.
Is there any plan for i18n in flow-router  in the near future ?

**Comment by arunoda** [comment]
I get it. But that's not something I can help with at the moment.
I'm pretty busy. I hope someone from the community can chime in.

**Comment by arunoda** [comment]
Anyway, why i18n needs to go through with the router. I hope it's sits on the UI layer. Try to find a package like that.

**Comment by laurentpayot** [comment]
Well for instance <i>for the same page</i> to be directed to `/en/record` for English-language browsers and to `/fr/enregistrement` for French-language browsers.  Isn't it the very role of the router layer to do so?
For the page content itself of course there are lots of i18n packages.

I also hope someone from the community can chime in. I will try a few dirty tricks myself.

**Comment by elie222** [comment]
You can create a new flow router group for each language you want to
support.

**Comment by laurentpayot** [comment]
Thanks @elie222 , I will definitively try something like that.

**Comment by mwarren2** [comment]
+1 I too have had to give up on flow-router, and it's my guess that many other developers in europe have had to do the same - here multi-language sites are very common for obvious reasons. We need **/en/record** vs **/fr/enregistrement** for SEO, there's no getting round it. We can of course create different groups for different languages, but it's not DRY.

**Comment by marktomm** [comment]
@elie222 could you please post a small example of using groups as a workaround for the current topic. ATM I would be glad if there was an example when only locale part would change in the url, f.ex
/en/record
/fr/record

**Comment by slissner** [comment]
+1 painfully needed as meteor 1.3 crashed my app running on iron:router.

**Comment by krishaamer** [comment]
Any update on this? I've a site with 12 languages and this is badly needed for SEO and usability reasons.
