### ISSUE TITLE
Triggers not called on `FlowRouter.notFound`

### ISSUE THREAD

**Issue by dr-dimitru** [kadirahq/flow-router#444]
Hi @arunoda ,

Is it expected behaviour what `FlowRouter.triggers.enter` and `FlowRouter.triggers.exit` is not triggered on route defined via `FlowRouter.notFound`?

**Comment by dr-dimitru** [comment]
To be more accurate - not triggered on direct page hit. But triggered during navigation

**Comment by arunoda** [comment]
Now you could do this with the FlowRouter SSR version.
