### ISSUE TITLE
user Agent on Server rendering when using Material UI

### ISSUE THREAD

**Issue by TimoRuetten** [kadirahq/flow-router#446]
Hey guys,

I am new to React and using this in combination with meteor and your SSR-Router. Its important for me to get the page rendered on Server too, so I choosed your package.

Additional I am using Material-Ui. In combination with your SSR-Router I got an error. When not using the SSR and instead using the default FlowRouter it works fine!

The error says the following:

Material-UI expects the global navigator.userAgent to be defined for server-side rendering. Set this property when receiving the request headers.

So why I am opering an issue in your package ? The errors says that something has to be set when the request header is received. Because your SSR-FlowRouter is handling all the Requests stuff I think it an issue with has something to do with your Router.

My question is: Is there a easy and recommended way to add a global variable like this after the header was received ?

Edit:
I just saw this Issue which is referenced to this problem:
https://github.com/kadirahq/flow-router/pull/414

**Comment by arunoda** [comment]
Yeah. I'll take #414 in.
