### ISSUE TITLE
FlowRouter.current() is undefined on the server.

### ISSUE THREAD

**Issue by MHerszak** [kadirahq/flow-router#447]
I am simply trying to redirect on the server and I am getting can't read property 'route' of undefined. I am trying to distinguish between public an private routes like so:

```javascript
Accounts.onLogin(function () {
    if (FlowRouter.current().route.group.name === 'public') {
        FlowRouter.go('/somewhere');
    }
});
```
I was trying to figure out if FlowRouter might be unavailable on the server?

**Comment by arunoda** [comment]
This is not available on the server. It's kind a hard to do this for this use case.
