### ISSUE TITLE
Request: get all routes that are a child of a group.

### ISSUE THREAD

**Issue by AlexFrazer** [kadirahq/flow-router#448]
I can make a PR if need be. If I have a group, I see it as having a series of children. That is,

```
CheckoutRoutes = FlowRouter.group({
  prefix: '/checkout/:orderId',
  subscriptions: function (params) {
    this.register('order', Meteor.subscribe('order', params.orderId));
  }
});

CheckoutRoutes.route('/shipping', {
  step: 0
  // ...
});

CheckoutRoutes.route('/payment', {
  step: 1
  // ...
});
```

The way I see this is that it has a heirarchical structure like this

```
/  (FlowRouter)
└── /checkout/:orderId  (CheckoutRoutes)
    ├── /shipping
    └── /payment
```

I want to get the 'children' of the `CheckoutRoutes`. I am not sure if this is currently possible without utilizing private methods.

```
FlowRouter._routes.filter(route => route.group === CheckoutRoutes);
```

**Comment by krevativ** [comment]
+1

**Comment by ShockiTV** [comment]
Current solution would be to use `FlowRouter.onRouteRegister` to construct representing tree yourself, as I am doing now to generate navigation dynamically.
So I would also vote for API call which return JSON representation of whole route tree. Than any1 can crawl it as he wants and get information.

**Comment by ShockiTV** [comment]
To provide example what i was talking about, my dynamically generated navigation menu.
Fill the ROUTE_LIST automatically.
```
LocalState.set("ROUTE_LIST",[]);

  FlowRouter.onRouteRegister( (route) => {
       LocalState.set("ROUTE_LIST", [ ...LocalState.get("ROUTE_LIST"), route]);
    }
  )

  FlowRouter.route('/', {
    name: 'posts.list',
    action() {
      mount(MainLayoutCtx, {
        content: () => (<PostList />)
      });
    },
    navigation: {
      label: "Home",
      position: 0
    }
  });
```
And than I can iterate/filter/sort how I need.
```
const routeList = _.chain(LocalState.get("ROUTE_LIST"))
    .filter( route => (!! route.options.navigation))
    .sortBy( route => route.options.navigation.position)
    .value();
  console.log("route list: ", routeList);
```
I did not tested it, but I would expect your route names to be available as `route.group.name` or `route.group.parent.name` .
If not I would try if the group itself does not have similar hook function of adding new route to it.
Did not checked sources.

Good luck

**Comment by arunoda** [comment]
I hope this is well answered.
Thanks @ShockiTV
