### ISSUE TITLE
How to call Meteor.user() in a trigger?

### ISSUE THREAD

**Issue by trusktr** [kadirahq/flow-router#452]
I've got a trigger that needs the current user's data: 

```js
triggersEnter: [function() {
    const user = await Meteor.user() // race condition. Sometimes Meteor.user() isn't ready, even if the user is logged in.
    // ...
}]
```

Allowing [async code](https://github.com/kadirahq/flow-router/issues/451) would make it easier to solve this problem.

**Comment by trusktr** [comment]
For now, I'm doing this:

```js
async function gotoFirstOrg(context, redirect, stop) {
    const user = await Users.current() // wait for async result
    const orgs = user.organizations().fetch()
    const lastOrg = orgs[0].slug

    FlowRouter.go(
        'organization',
        {organization: lastOrg},
        {}
    )
}

FlowRouter.route('/', {
    name: 'home',
    triggersEnter: [
        checkLogin,
        gotoFirstOrg,
    ],
    action: function (params) {}
})
```

gotoFirstOrg is the last trigger function, and the action is empty, so even though it is currently impossible to prevent the action with `redirect` or `stop`, it doesn't really matter in this case.

Async would be nice!

**Comment by arunoda** [comment]
As I said earlier, you need to get  do this on the client side.
Implement the redirect logic in the client side, if you need to get the userInfo for the redirect.

Just show a message to the user saying **waiting**, then do the redirect.
