### ISSUE TITLE
[question] How to redirect in an action (with FlowRouter.go)?

### ISSUE THREAD

**Issue by trusktr** [kadirahq/flow-router#453]
Is it possible to redirect in an action? I know I can use FlowRouter.go, but by default it doesn't remove the previous location from the history, like a "redirect" does. Is there an option to pass to the `go` function to treat it like a redirect so it erases the previous history item?

**Comment by trusktr** [comment]
The reason I'm redirecting in the `action` is because I'm using async/await in there, and I might need to redirect a few ticks later.

**Comment by trusktr** [comment]
By the way, the `action` function itself is not `async`, it just calls `async` functions inside, so the router itself is never blocked.

**Comment by arunoda** [comment]
You could use this I think: https://github.com/kadirahq/flow-router#flowrouterwithreplacestatefn

**Comment by trusktr** [comment]
:+1:
