### ISSUE TITLE
Custom Publish/Subscribe with Flow Router SSR

### ISSUE THREAD

**Issue by maddijoyce** [kadirahq/flow-router#454]
Hi,
I think I might have a similar issue to #431.

My publish basically looks like:
```javascript
Meteor.publish("data", function(query) {
  ExternalService.find(query, (err, result) => {
    this.added("data", result.id, result);
    this.ready();
  });
});
```

And then in my React class I use:
```javascript
getMeteorData() {
  var dataLoaded = Meteor.subscribe("data", { name: name });
  var data = Data.findOne({ name: name });

  return {
    user: Meteor.user(),
    dataLoaded: dataLoaded.ready(),
    data: data
  };
}
```

However, when performing an initial render on the server, I get this error:
```
Publish handler for { name: 'data', params: [ { name: 'Test' } ] } sent no ready signal
```

I double checked, and I'm on version 3.7.3 of flow-router-ssr, but the issue is still occurring.

Thanks,
Maddi

**Comment by rozzzly** [comment]
Put a console.log in your arrow function. Does it fire before, or after error? Or not at all

**Comment by maddijoyce** [comment]
It's firing after the error.

**Comment by rozzzly** [comment]
So thinking that it expecte ready to be called in an async. Ill send you a link when I get off work

**Comment by maddijoyce** [comment]
So, it looks like I wasn't quite looking in the right place:
I've found the error message- https://github.com/kadirahq/fast-render/blob/master/lib/server/context.js#L105

So apparently, my external service is taking more than 500ms. I guess I'll need to configure that value?

**Comment by arunoda** [comment]
But if it takes more the 500ms, you should not use that publication in SSR.
Do it after page loads.

**Comment by maddijoyce** [comment]
Ok, that makes sense.
Thanks for your help.

Cheers,
Maddi
