### ISSUE TITLE
`FlowRouter.go` not working with Params object.

### ISSUE THREAD

**Issue by shwaydogg** [kadirahq/flow-router#459]
The Following two examples work as expected:

`FlowRouter.go('/manage-team/' + id);`

```
FlowRouter.go('/manage-team');
FlowRouter.setParams({teamId: id});
```

`FlowRouter.go('/manage-team', {teamId: id});` however does not work and has now warnings, errors or exceptions.

Of course, I'm continuing by just using what does work, but I'd thought I'd report.  I'm on v2.10.0.

**Comment by arunoda** [comment]
For this one, you need give it like this:

```
FlowRouter.go('/manage-team/:teamId', {teamId: id});
```
