### ISSUE TITLE
Browser's location.pathname gets overwritten when clicking on a URL

### ISSUE THREAD

**Issue by billyvg** [kadirahq/flow-router#460]
If you click on an link inside of your application, the browser's URL doesn't get updated until the route is finished rendering, it seems.

Example:
* you are at the URL `http://localhost/` 
* you click a link on your app to `http://localhost/route`
* Inside of your template you update the route:
 `FlowRouter.setParams({ id: 123 })`

What happens in your browser's address bar is:
* `http://localhost/` (initial location)
* `http://localhost/route` (click)
* `http://localhost/route/123` (template updates parameter)
* `http://localhost/route` (??)

**Comment by arunoda** [comment]
This is a known issues and fixed in the next major version 4.0, which is scheduled for end of this month.
