### ISSUE TITLE
Client Side Collections (a "null" collection) for SSR

### ISSUE THREAD

**Issue by voidale** [kadirahq/flow-router#462]
Hi

What should be the best practice with null collections? I'm subscribing to it through `getMeteorData()` and the subscriptions fetches an API and uses `self.added` api to add the documents. The problem there is no data in the server collection only client side I keep getting errors (workable) but still would love to know maybe there is a way to do this in a better way? `componentWillMount` seems to be a performance problem if we fetch it from external API (slight delay).

Thanks!

**Comment by arunoda** [comment]
You need to get these in `componentDidMount` since there is no data related in the server.
