### ISSUE TITLE
Page.js breaks mobile support

### ISSUE THREAD

**Issue by Dyscrete** [kadirahq/flow-router#469]
The fork of page.js used for Flow Router breaks mobile support on nearly every device I've tried, could not figure out why but using the original page.js source works. IE8+ support can be accomplished with a [HTML5 history API polyfill](https://atmospherejs.com/tmeasday/html5-history-api).

**Comment by arunoda** [comment]
That's weird. We are using the latest version of FlowRouter with many apps (incl. Kadira UI) and it works pretty well.

BTW: Now it's a good time to update our fork.

**Comment by Dyscrete** [comment]
https://github.com/kadirahq/page.js#support-in-ie8

**Comment by Dyscrete** [comment]
Still seems to be an issue on iOS.

**Comment by Dyscrete** [comment]
This does not seem to be the issue.
