### ISSUE TITLE
is that any function can replace pathFor function in iron:router?

### ISSUE THREAD

**Issue by thinksource** [kadirahq/flow-router#472]
The full question is on stackoverflow:

http://stackoverflow.com/questions/34647098/which-function-is-the-replacement-function-of-pathfor-function-of-iron-routing

just ask if there is any function like iron:router pathFor function in flow-router?

**Comment by TimFletcher** [comment]
https://github.com/zimme/meteor-active-route

**Comment by 416serg** [comment]
https://github.com/arillo/meteor-flow-router-helpers

**Comment by TechplexEngineer** [comment]
https://gist.github.com/TechplexEngineer/684b7ffd142ce5170467e868138f32f3
