### ISSUE TITLE
FlowRouter.go() vs FlowRouter.redirect()

### ISSUE THREAD

**Issue by avalanche1** [kadirahq/flow-router#473]
Hi, @arunoda !
I have these routes:
```
FlowRouter.route("/", {
  name: 'home',
  action: function() {
    return FlowRouter.go("/postList/" + getUserCityId());
  }
});

FlowRouter.route("/postList/:cityId", {
    name: 'postList',
    action: function() {
      return BlazeLayout.render('mainLayout', {
        top: 'header',
        body: 'body'
      });
  }
});
```
If I click a `home` link in any other route, browser will render 'postList' route correctly, but the url will flash `/postList/someCityId` and then become only `/` (or localhost:3000). 

But if I use undocumented FlowRouter.redirect("/postList/" + getUserCityId()) instead of FlowRouter.go() - everything works as expected, the url is correct: `/postList/someCityId`.

May also be linked to  https://github.com/kadirahq/flow-router/issues/351

**Comment by arunoda** [comment]
Yep. We have some issues while trying to change the route while routing.

Sometimes redirect works. We have a proper fix in version 4.

**Comment by avalanche1** [comment]
When v4 is due?

**Comment by arunoda** [comment]
End of this month.

**Comment by mjgallag** [comment]
@avalanche1 @arunoda I just experienced this exact same problem and was in the middle of logging a detailed issue, but, better late than never to find this exchange. Using undocumented `FlowRouter.redirect` in place of `FlowRouter.go` seems to work for me too.

There were 3 use cases I could distinguish, user gets logged out while viewing a page that requires login, a logged out user visits a page that requires login via their browser's address bar, a logged out user visits a page that requires login via a relative hyperlink (or execute's a `FlowRouter.go`). `FlowRouter.go` worked for the first 2 use cases, but not the last one. `FlowRouter.redirect` worked for all 3 use cases.

@arunoda when version 4 arrives will this all work with `FlowRouter.go` or will `FlowRouter.redirect` be the documented approach for this scenario? Thanks!
