### ISSUE TITLE
FlowRouter.getParam() is not found in server side

### ISSUE THREAD

**Issue by sahanDissanayake** [kadirahq/flow-router#474]

**Comment by arunoda** [comment]
We'll have it in the SSR server.

**Comment by sahanDissanayake** [comment]
@arunoda Thanks, can i know why SSR development has taken priority ? Just curious

**Comment by arunoda** [comment]
Because we needed SSR :)
But now it has a lot of new things and remove some bad code.

**Comment by sahanDissanayake** [comment]
yes we do... thanks for all the work you do on it
