### ISSUE TITLE
FlowRouter.reload() function don't seems to work.

### ISSUE THREAD

**Issue by frank-xue-porch** [kadirahq/flow-router#475]
FlowRouter.reload() function don't seems to work, here is my code, it lives on client side and route.jsx file.
I can see called logged in my browser console but the page is not reloading. Am I doing it correct?

```javascript
Accounts.onLogin(function(){
    console.log("called !!");
    var currentContext = FlowRouter.current();
    console.log(currentContext.path);
    FlowRouter.go(currentContext.path);
    FlowRouter.reload();
});
```

**Comment by frank-xue-porch** [comment]
``` javascript

Accounts.onLogin(function(){
    console.log("called!!");
    var currentContext = FlowRouter.current();
    console.log(currentContext.path);
    window.location.href = currentContext.path;
});

```
this does what I need but it's recall to server, I'm pretty sure FlowRoute can reload it without calling the server, right?

**Comment by arunoda** [comment]
FlowRouter.reload() does not reload your page. It re-run the action of the router.
I think, here you need `location.reload()`
