### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by humbertocruz** [kadirahq/flow-router#477]
Hello, I'm pushing some new url with "window.history.pushState('page', 'title', location.pathname+'?page='+this.page);" to simulating a page change for pagination and it's ok, but when I press the browser back the error "Cannot read property '0' of undefined" on meteorhacks_flow-router.js line 484 appears.

thanks

**Comment by arunoda** [comment]
Hey do not use `pushState` directly. That may cause issues.
