### ISSUE TITLE
Regular expressions does not work with .path

### ISSUE THREAD

**Issue by ericvillemure** [kadirahq/flow-router#479]
Hi, I would like to use the following route to filter what values can be used as an action:

```javascript
FlowRouter.route('/blog/:action(edit|create)/:id?', {
  action: function(params, queryParams) {
    console.log(params);
  }
});

//succeeds
FlowRouter.go('/blog/create');

//returns error : There is no route for the path: /blog/test
FlowRouter.go('/blog/test');

console.log(FlowRouter.path('/blog/:action(edit|create)/:id?', {action: "edit", id: "abc"}));
//This returns : /blog/edit|create)/abc
```

Unfortunately FlowRouter.path doesn't seem to like my '/blog/:action(edit|create)/:id?' route like .go does.

Can you help me with that.

Thanks

**Comment by tomwasd** [comment]
Hi,

Just a +1 on this. I believe other FlowRouter functions like setQueryParams() don't work with your example above either. The regex seems to break it!

**Comment by arunoda** [comment]
This is fixed with the FlowRouter SSR branch. It's on the atmosphere as `kadira:flow-router-ssr`.
We'll merge this soon.
