### ISSUE TITLE
How do i pass the template configs to dynamic Template ?

### ISSUE THREAD

**Issue by sharathbangera6** [kadirahq/flow-router#481]
Hi,

I am using FlowRouter for routing and in the home page i am showing the reactiveTable. Inside the / router i am rendring the reactive Table, but how do i pass the collection (Data i get from backend) and config(Some of the table Settings) of the Reactive Table to the dynamic Template ?

var pages = FlowRouter.group({
prefix: '/students'
});

pages.route('/', {
action: function(){
BlazeLayout.render('HomePage', {mainPage:'reactiveTable'});
}
});

{{> Template.dynamic template=mainPage}}

Thank You

**Comment by arunoda** [comment]
You need to use template level subscriptions for that.
Check this: https://kadira.io/academy/meteor-routing-guide/content/subscriptions-and-data-management/with-blaze
