### ISSUE TITLE
Ghost blog at /blog route

### ISSUE THREAD

**Issue by 416serg** [kadirahq/flow-router#483]
I am not sure if this is possible but there is a way to host a Ghost blog at a subfolder instead of a subdomain https://www.allaboutghost.com/how-to-install-ghost-in-a-subdirectory/

I have set up everything on that end the way it says and now the only thing that is needed is to exclude `/blog` from the `FlowRouter.notFound` function. is there a way to do that or set up the route to listen to nginx?

**Comment by arunoda** [comment]
I think this is a topic you can ask on Meteor Forums.
