### ISSUE TITLE
Redux + FlowRouter

### ISSUE THREAD

**Issue by achtan** [kadirahq/flow-router#484]
Hi, is there any decs on how to use FR with Redux? 
I'm new in Redux world, so i'm not sure how to integrate it with FR
thx

**Comment by arunoda** [comment]
If it's Redux, it's much better to go with redux-simple-router for the moment. You can use Mantra as well. 
But, we need some docs for that. That'll take some time.

**Comment by arunoda** [comment]
Hope this is answered.

**Comment by jonlachlan** [comment]
Same question. It looks like redux-simple-router is pretty straightforward. How much would it take to adapt it to the Flow Router APIs?
