### ISSUE TITLE
SSR, best way to extract subdomain (or access current host) on client and server?

### ISSUE THREAD

**Issue by marbemac** [kadirahq/flow-router#485]
For some of our routes, we have a unique identifier present in the subdomain. For example, 123.example.com. We want to pass that identifier to the component rendered from the route action. How can we extract that id in the action function, on both the client and the server?

For now, we've come up with:

```js
FlowRouter.route('/', {
  name: 'root',
  action(params) {
    let projectId;
    const current = FlowRouter.current();

    if (current._serverRequest) {
      projectId = current._serverRequest.headers.host;
    } else {
      projectId = window.location.host;
    }

    ReactLayout.render(MainLayoutCtx, {
      projectId
    });
  },
});
```

However, that's using a private _serverRequest API, and relying on the host header (which is not ideal, because can't always rely on it). After inspecting _serverRequest, the host header was the only value I could find that included the host.

Thanks for any help!

**Comment by arunoda** [comment]
I think we could make _serverRequest something official. I'm open to remove the _ and make it `current.serverRequest`.
(Looking forward a PR)

But isomorphic host lookup API is out of the scope of FlowRouter. May be it's a good idea to have a it's own package or an utility in your app.

**Comment by arunoda** [comment]
I'm gonna close this and looking forward for the PR.
