### ISSUE TITLE
FlowRouter SSR 3.8.0, BlazeLayout.render() not working in triggersEnter

### ISSUE THREAD

**Issue by scsirdx** [kadirahq/flow-router#488]
````javascript
let adminRoutes = FlowRouter.group({
    prefix: '/dashboard',
    name: 'admin',
    triggersEnter: [function(context, redirect, stop) {
        if (!Meteor.user()) {
            BlazeLayout.render('signIn');
            stop();
        } else if (!Roles.userIsInRole(Meteor.user(), ['full-control'], 'admins')) {
            BlazeLayout.render('accessDenied');
            Meteor.setTimeout(() => {AccountsTemplates.logout();}, 2000);
            stop();
        }
    }]
});
````
After update to 3.8.0 BlazeLayout.render('signIn'); in this example stops working, no errors reported, routes opened as if there no BlazeLayout.render or stop().
Downgrading to 3.7.3 solves problem.

**Comment by scsirdx** [comment]
Hmm. 3.7.3 not working too.
And in strange way: it works in dev environment, but in production Roles.userIsInRole(Meteor.user(), ['full-control'], 'admins') returns false in router (for user that is in role), and in browser console Roles.userIsInRole(Meteor.user(), ['full-control'], 'admins') returns true.
Downgrade to 3.6.0 solves all problems.

**Comment by arunoda** [comment]
This is bad. You should not do these things in triggers. It's not reactive.
Do all the things in the template level.
Read our guide: https://kadira.io/academy/meteor-routing-guide
