### ISSUE TITLE
Bug: PageCacheTimeout not respected (flow-router-ssr)

### ISSUE THREAD

**Issue by dferber90** [kadirahq/flow-router#489]
## Bug

- Caching is not turned off by default (unlike stated in the docs). Uses 30 second cache instead.
- When setting a cache timeout with `FlowRouter.setPageCacheTimeout`, it has no effect. Still uses 30 seconds timeout instead.

*These bugs only concerns flow-router-ssr.*

## Probable cause
I already looked into why the issue may exist, and I think I've found the problem.

I've set the timeout to 0 using `FlowRouter.setPageCacheTimeout(0)` and used the following code to log the context in a route:

```js
FlowRouter.route('/', {
  action () {
    console.log(this)
    //...
  }
})
```

This resulted in:
```js
{ options: { action: [Function] },
  name: undefined,
  pathDef: '/',
  path: '/',
  action: [Function],
  _router:
   { _routes: [ [Circular], [Object] ],
     _routesMap: { listing: [Object] },
     subscriptions: { [Function: Empty] future: [Function], async: [Function], asyncApply: [Function] },
     ssrContext: { slot: 4 },
     inSubscription: { slot: 5 },
     currentRoute: { slot: 6 },
     pageCacheTimeout: 30000,
     _onRouteCallbacks: [],
     Router: [Function],
     Route: [Function],
     basePath: '',
     deferScriptLoading: true,
     _pageCacheTimeout: 0 },
  subscriptions: { [Function: Empty] future: [Function], async: [Function], asyncApply: [Function] },
  _subsMap: {},
  _cache: {} }
```

As you can see, `_router` contains both `pageCacheTimeout` and `_pageCacheTimeout`. The `_pageCacheTimeout` contains the value `0` which I've set through the configuration. However, `pageCacheTimeout` still contains `30000`. But `flow-router-ssr` uses `pageCacheTimeout` to determine the duration of the cache, as can be seen here: https://github.com/kadirahq/flow-router/blob/ssr/server/route.js#L102-L107

So, the value set for the cache duration is ignored. Further, the cache is not disabled by default (as mentioned in the docs, but rather defaults to 30 seconds).

---

Thanks for your hard work to make Meteor a better tool, Arunoda and the rest of the Kadira team :)

**Comment by arunoda** [comment]
I checked this couldn't be an issue.
There is no code where we set for 30000 as the `pageCacheTimeout`.

I think it seems like, you are  setting it somewhere in your code.

**Comment by dferber90** [comment]
Turns out the application in which I noticed the bug was using an outdated version (v3.6.0) of `flow-router-ssr`. The 30000 were coming from https://github.com/kadirahq/flow-router/blob/v3.6.0/server/router.js#L10.

The issue seems to have been fixed since.

Thank you and I'm sorry for causing the noise, should have checked the version numbers.
