### ISSUE TITLE
3.8.0 breaks back button

### ISSUE THREAD

**Issue by timothyarmes** [kadirahq/flow-router#490]
Hi,

Upgrading to version 3.8.0 breaks the browser's back button. Clicking the button does update the URL, but the page isn't re-rendered.

Downgrading to 3.7.3 fixes this.

**Comment by timothyarmes** [comment]
I looked into this. You were no longer checking the history state; I've added PR #492 to solve this.

Moving away from page.js is great, but since it's such a big change I have a suspicion that we'll see a few other little bugs in the near future!

**Comment by arunoda** [comment]
Okay. I know how to fix it.
Actually, it's not a very big change just the routing part. Other parts will get simplified because of that.

**Comment by arunoda** [comment]
I fixed this. 
Thanks for helping to test this.

**Comment by timothyarmes** [comment]
Great thanks.

Can you also please look at https://github.com/kadirahq/flow-router/issues/495 (for which I've also added PR #494)? Then I'll be able go back to the official version rather than my fork :)

**Comment by arunoda** [comment]
I think I already did it :) 
Check version `3.8.2`

**Comment by timothyarmes** [comment]
:)
