### ISSUE TITLE
Optional parameters not working.

### ISSUE THREAD

**Issue by timothyarmes** [kadirahq/flow-router#495]
3.8.0 broke optional parameters. For example, with a route defined as:

```
/:name?
```

`name` would be `"undefined"` (a string) instead of truly `undefined`.

Also, calling `setParams`or `setQueryParams` without setting a parameter would result an invalid path of a similar reason. In the example above, calling:

```
FlowRouter.setQueryParams({});
```

Would result in the router redirecting to `/undefined` instead of `/`

I've made PR #494 and added some unit tests. The tests work on my machine but they fail with no useful information here on Github. Is that to be expected?

**Comment by timothyarmes** [comment]
Fixed.

**Comment by ArthurGerbelot** [comment]
Can this be added to the doc please ? 

It's only suggested here : 

```
var localeGroup = FlowRouter.group({
  prefix: '/:locale?',
  triggersEnter: [localeCheck]
});
```
