### ISSUE TITLE
Move to NPM for Meteor 1.3

### ISSUE THREAD

**Issue by deejross** [kadirahq/flow-router#498]
Any chance FlowRouter could get published to NPM for Meteor 1.3? I would love it if I never had to use Atmosphere again. I'm very happy Meteor will natively support NPM in the next version and really hope Atmosphere goes away shortly after release. 

I don't have anything against Atmosphere personally, but I can't use it at work (corporate firewall that uses signed certs) because "meteor add" won't allow you to override the cert check (opened several issues about this). NPM, however, does let you override that. So I've been manually downloading packages and their dependencies from GitHub. What a pain!

So I'm happy to see the Meteor community start steering towards NPM and away from Atmosphere and FlowRouter should be one of the first popular Meteor packages to make the jump.

**Comment by Goatic** [comment]
+1 could be nice

**Comment by arunoda** [comment]
I'm still think of it. We ported few packages like ReactLayout to `react-mounter` on NPM. But, it's too early for FlowRouter. (since we've some server side stuff).

But, let's see.

**Comment by arunoda** [comment]
This is not possible right now. But, we'll touch this in a later version.
