### ISSUE TITLE
Deep linking issue

### ISSUE THREAD

**Issue by sahanDissanayake** [kadirahq/flow-router#500]
Hi, Let me explain my issue here. 

1. I open a modal. the link change to http://myurl.com?modal=open

2. Inside that modal there are images, click on a image and a new modal open with the link
http://myurl.com?modal=open&photo=12n1j21j22

This is the issue now, 

```javascript
FlowRouter.url(FlowRouter.current().path, {}, {photo: '12n1j21j22'});
// http://myurl.com?modal=open?photo=sadsadasdsd9as8das9d
```

If the current path has any query params the new query params should be appended right ?

**Comment by arunoda** [comment]
This will be fixed with FlowRouter 4.0.
Try our SSR version for a fix.
