### ISSUE TITLE
FlowRouter.go() Only Changes URL

### ISSUE THREAD

**Issue by SylarRuby** [kadirahq/flow-router#501]
I am using `FlowRouter.go('/');` inside of a react component:

```
componentWillMount() { 
 FlowRouter.go('/'); 
}
```

Only the url changes but not the html body. How to properly do this?

**Comment by arunoda** [comment]
This is a bug in the current flow router. Do it inside a `setTimeout()`.
This is fixed in the `kadira:flow-router-ssr`version.

**Comment by SylarRuby** [comment]
Thanks mate!
