### ISSUE TITLE
Question: meteor-react-router vs flow-router+meteor-react-layout

### ISSUE THREAD

**Issue by boustanihani** [kadirahq/flow-router#504]
Just out of curiosity, how would you compare https://github.com/thereactivestack/meteor-react-router to using ```flow-router``` combined with ```meteor-react-layout```? Which one would you recommend if one is going to build a pure react app?

**Comment by arunoda** [comment]
If it's going with Meteor, I suggest you to go with FlowRouter.
But, I don't have anything against with ReactRouter as well :) 
And I'm biased.

**Comment by boustanihani** [comment]
are there any pros or cons... ?

**Comment by arunoda** [comment]
Check this forum post: https://forums.meteor.com/t/react-router-vs-flow-router/6867

**Comment by boustanihani** [comment]
Thanks for the link
