### ISSUE TITLE
Upgrade to Meteor 1.3 beta 5 throws error for FlowRouter-SSR

### ISSUE THREAD

**Issue by jasongrishkoff** [kadirahq/flow-router#505]
Getting this error after upgrading to beta 5.  Using the latest version of FlowRouter-ssr (3.9.0)

packages/kadira:flow-router-ssr/lib/router.js:43:8: /packages/kadira:flow-router-ssr/lib/router.js: Duplicate declaration "path"

Rolling back to beta 4 solved the issue.

**Comment by SylarRuby** [comment]
Clearly the issue is not resolved. Rolling back only avoided the issue.

**Comment by arunoda** [comment]
Here's the line: https://github.com/kadirahq/flow-router/blob/ssr/lib/router.js#L43
And clearly there is no issue. 

I wonder what's the issue here. Could you guys add an issue on meteor repo for this?

**Comment by PEM--** [comment]
I've referenced the issue: https://github.com/meteor/meteor/issues/6138

**Comment by PEM--** [comment]
In the meantime, I've created a small PR: https://github.com/kadirahq/flow-router/pull/515

**Comment by arunoda** [comment]
This is fixed in version `v3.9.1`.

**Comment by PEM--** [comment]
Thanks :+1:
