### ISSUE TITLE
Meteor 1.3 beta 5 flowrouter ssr Duplicate declaration "path"

### ISSUE THREAD

**Issue by SylarRuby** [kadirahq/flow-router#506]
Fresh install of Meteor 1.3 beta 5 with FR SSR:

> While processing files with ecmascript (for target web.browser):
   packages/kadira:flow-router-ssr/lib/router.js:43:8: /packages/kadira:flow-router-ssr/lib/router.js:
   Duplicate declaration "path"
   packages/kadira:flow-router-ssr/client/router.js: /packages/kadira:flow-router-ssr/client/router.js:
   "route" is read-only (This is an error on an internal node. Probably an internal error. Location has been
   estimated.)

**Comment by arunoda** [comment]
Duplicate #506
