### ISSUE TITLE
Is it possible to define one route with a param and without one

### ISSUE THREAD

**Issue by c316** [kadirahq/flow-router#516]
Here is an example of what I mean by my question. 

    authenticatedRoutes.route( '/people/:_id', {
      name: 'people',
      action() {
        BlazeLayout.render( 'main', { yield: 'People' } );
      }
    });

Is there a way to make both of these URLs work with one route?

https://myapp.mydomain.com/people
https://myapp.mydomain.com/people/PKsads3343ss

**Comment by arunoda** [comment]
Check this to learn more about path definition syntax.
See: https://github.com/pillarjs/path-to-regexp#optional

`path-to-regexp` is the project we use internally for path definitions.
