### ISSUE TITLE
use of FlowRouter.current().context.hash

### ISSUE THREAD

**Issue by verdavaine** [kadirahq/flow-router#518]
I am using FlowRouter.current().context.hash to detect reactively hash inside URL (with FlowRouter.watchPathChange())
When some hash is added to URL, it works
But when clicking on back button, FlowRouter.current().context.hash remains unchanged although hash has disappeared from URL

It worked reactively with Iron-Router using Iron.Location.get().href.indexOf('#')

**Comment by arunoda** [comment]
There was a bug and we fixed it in the FlowRouter SSR version. That's the next version we are working on.

You can get the hash like this: `FlowRouter.current().hash`

**Comment by iamparthaonline** [comment]
Now it works like this actually - 
`FlowRouter.current().context.hash`
