### ISSUE TITLE
There is no route for the path: /#Kadira

### ISSUE THREAD

**Issue by MickaelBZH** [kadirahq/flow-router#519]
Was working with version 3.7.3 and with only the route / declared.

**Comment by MickaelBZH** [comment]
Actually, the last working version is 3.8.0
3.8.1 broke it.

**Comment by arunoda** [comment]
Yep there is an issue when we've hash content.
Working on a fix now.

**Comment by arunoda** [comment]
This is fixed in `v3.9.3`.
Re-open this issue if it didn't work.
