### ISSUE TITLE
Does SSR work with Meteor 1.3?

### ISSUE THREAD

**Issue by tonyxiao** [kadirahq/flow-router#521]
And the mantra application architecture?

**Comment by walleXD** [comment]
@tonyxiao as far as I know it does not currently work with mantra but it is in the roadmap and it should be part of the [next mantra spec release in the near future](https://kadirahq.github.io/mantra/#sec-Server-Side-Rendering-SSR-)

**Comment by arunoda** [comment]
Yes. it'll be.
We are tracking this here: https://github.com/kadirahq/react-mounter/issues/3
