### ISSUE TITLE
Tests with FlowRouter

### ISSUE THREAD

**Issue by solace** [kadirahq/flow-router#527]
With testing guides involving Iron Router, there is mention of a file like https://meteor-testing.readme.io/docs/jasmine-integration-tests-with-iron-router so that we can route to a new page and know when it is ready to perform subsequent actions.

Is something like this necessary for FlowRouter, or do we just `FlowRouter.go` and have at it?

If we do need something similar to determine when the client is ready, how would we go about converting that helper for FlowRouter?  The entry and exit triggers available do not seem to account for the additional events covered for Iron Router.

Thanks

**Comment by arunoda** [comment]
Not sure how to do this exactly. This should be best suit to Meteor Forums where you can get more feedback.
