### ISSUE TITLE
SSR - FlowRouter.wait not working on iOS or Safari

### ISSUE THREAD

**Issue by PEM--** [kadirahq/flow-router#536]
I use `FlowRouter.wait();` at the early beginning of my app to block routing on the client. When the router is blocked, I wait for the subscriptions to settle and create routes dynamically using some collections. When every routes are created, I release the router with a `FlowRouter.initialize();` for creating routes.

This pattern works fine on Chrome (OSX & Android), Firefox. It fails on Safari (OSX & iOS).

The 'not-found' route is started despite its declaration has been postponed long after the init.

**Comment by PEM--** [comment]
While investigating, `onpopstate` is triggered before the router is initialized on Safari (OSX & iOS).

**Comment by PEM--** [comment]
Fixed with #538

**Comment by arunoda** [comment]
Thanks.
Merged & Published as `v3.11.1`.

**Comment by PEM--** [comment]
Thanks :+1:
