### ISSUE TITLE
Error when doing SSR. path:/: DefaultLayout is not defined

### ISSUE THREAD

**Issue by onedr0p** [kadirahq/flow-router#537]
```
W20160221-15:52:09.673(-5)? (STDERR) Error when doing SSR. path:/: DefaultLayout is not defined
W20160221-15:52:09.674(-5)? (STDERR) ReferenceError: DefaultLayout is not defined
W20160221-15:52:09.675(-5)? (STDERR)     at Object.action (app/both/routes/authenticated.jsx:48:36)
```

I just updated to FlowRouter-SSR  since the new beta for meteor came out (Beta.11). I could never get this version of FlowRouter to ever work since I would get the error described in #522.

Now on Beta 11, I was hopefully things would run smoothly, but now I get the above error instead.

Please advise... Do I need to start using ES6 classes instead of `DefaultLayout = React.createClass({` or `AccountNotifications = React.createClass({` ?

If that is the case, whenever I try using ES6 classes I can never get my classes imported because they are never found. For example if I wrote `DefaultLayout` in an ES6 class and tried importing it in `authenticated.jsx` like `import DefaultLayout from '../client/components/layouts/default';` it (the file) will never be found, even thou the path is right...

Code snippet for `app/client/components/layouts/default.jsx`

``` js
import React from 'react';

DefaultLayout = React.createClass({
  render() {
    return (
      <div className="app-root">
        <AppHeader />
        <div className="ui container">
          {this.props.yield}
        </div>
      </div>
    );
  }
});
```

Code snippet for `app/both/routes/authenticated.jsx`

``` js
import React from 'react';
import ReactDOM from 'react-dom';

/*
 * Account Route
 */
authenticatedRoutes.route('/account/notifications', {
  name: 'accountNotifications',
  action() {
    var page = React.createElement(DefaultLayout, {
      yield: <AccountNotifications />
    });

    ReactDOM.render(page, document.getElementById('yield'));
  }
});
```

**Comment by novium** [comment]
Could it be as simple as that you forgot to export DefaultLayout?
(You will still need to import it in your router of course)

```javascript
import React from 'react';

DefaultLayout = React.createClass({
  ...
});

export default DefaultLayout;
```

**Comment by onedr0p** [comment]
Hi @novium, I am trying to import DefaultLayout into my component but I can never seem to import it because the file isn't found. I get the following error:

```
W20160221-23:33:58.599(-5)? (STDERR) Error: Cannot find module '../client/components/layouts/default.jsx'
W20160221-23:33:58.599(-5)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:77:1)```

Here is the default layout located at `app/client/components/layouts/default.jsx'
```js
import React from 'react';
DefaultLayout = React.createClass({
  render() {
    return (
      <div className="app-root">
        <AppHeader />
        <div className="ui container">
          {this.props.yield}
        </div>
      </div>
    );
  }
});
export default DefaultLayout;
```

Here is `/app/both/routes/common.jsx' with the following code:
```js
import React from 'react';
import ReactDOM from 'react-dom';
import DefaultLayout from '../client/components/layouts/default';

/*
 * Home Route
 */
FlowRouter.route('/', {
  name: 'home',
  action() {
    var page = React.createElement(DefaultLayout, {
      yield: <Home />
    });
    ReactDOM.render(page, document.getElementById('yield'));
  }
});
```

I am using relative paths here, but even when I try absolute paths Meteor says the file is still not found.

**Comment by onedr0p** [comment]
I'll create a new comment for this because I strongly believe this is an issue with the SSR branch 

@arunoda just to recap, I have these 2 directories: `app/both/routes/` and `app/client/components/`

When I leave the `routes/` folder in the `both/` folder I get an error saying:
```
Error when doing SSR. path:/: DefaultLayout is not defined
W20160222-00:41:40.463(-5)? (STDERR) ReferenceError: DefaultLayout is not defined
```
However the app still functions (I'm assuming with no SSR thou)

When I move the `routes` folder to my `app/client` folder the error goes away and everything appears to be running fine.

Thanks for all you help and the work on FlowRouter, it's great!

**Comment by novium** [comment]
Could you try to append the `.jsx` to the import path?
`import DefaultLayout from '...../layouts/default.jsx';`

**Comment by onedr0p** [comment]
I tried importing using the .jsx extension but no luck.

I guess I need to rearrange my folder structure to allow the server access to the components. But it makes no sense why when I move my routes folder into the client folder I don't get any errors..

**Comment by onedr0p** [comment]
It looks like I will just revert back to FlowRouter v2.10.1 as it works perfectly fine.

In SSR, I am also having issue with `triggersEnter` where the following code block is accessable to a logged in user. e.g. they can access my `/login` route.

```js
const publicRoutes = FlowRouter.group({
  name: 'public',
  triggersEnter: [function() {
    if (Meteor.userId()) {
      FlowRouter.go('home');
    }
  }]
});

/*
 * Log in Route
 */
publicRoutes.route('/login', {
  name: 'login',
  action() {
    var page = React.createElement(DefaultLayout, {
      yield: <Login />
    });

    ReactDOM.render(page, document.getElementById('yield'));
  }
});
```

**Comment by arunoda** [comment]
@onedr0p the issue in here is pretty interesting. (I think)
Even your app directory in available to the server, I don't think anything your client directory does.

Try to rename the client directory into something else or just rename the `client` to `app`.

Also, we don't support triggers in the SSR yet.
