### ISSUE TITLE
Meteor Role Auth?

### ISSUE THREAD

**Issue by fallenpeace** [kadirahq/flow-router#540]
Is checking for auth & role auth, at the template level still recommended?

Eg, been looking at some examples on the mantra project, and some of them do  auth in the action of flow router

```
action() {
 if(!Meteor.userId()) {
    FlowRouter.go('/login');
 }
}
```

Could this be used to check roles too? Or should we just opt for template level checks of auth?

**Comment by arunoda** [comment]
Use template level auth.

**Comment by uiii** [comment]
Hi, I've made related issue here: https://github.com/kadirahq/mantra/issues/153
