### ISSUE TITLE
client.browserify issue with meteor 1.3 beta.16

### ISSUE THREAD

**Issue by danielbh** [kadirahq/flow-router#552]
I was trying to add flowrouter to the new beta 16 that just came out: https://github.com/meteor/meteor/releases/tag/release%2FMETEOR%401.3-beta.16

I received the following error just for installing the package and without any coding whatsoever...

=> Errors prevented startup:                  
   
   While processing files with cosmos:browserify (for target web.browser):
   packages/kadira:flow-router/client.browserify.js: Arguments to path.resolve must be strings
   
   Browserify options:
   >  undefined

I have no idea what is causing this. I looked at: https://github.com/kadirahq/flow-router/blob/master/client.browserify.js

and I don't see any issue with it. What are your thoughts? Thanks.

**Comment by suhail-ansari-apconic** [comment]
There is already an issue created on meteor git repository and here is answer from benjamin. Basically flowrouter has to remove dependency from browserify and use modules.

https://github.com/meteor/meteor/issues/6449

**Comment by mcbain** [comment]
+1

**Comment by huttonr** [comment]
:+1:

**Comment by suhail-ansari-apconic** [comment]
Are we going to see this fixed any time soon. I already see a PR related to this. Beta 16 solves a lot of issues we were facing due to node defaults being not available but cannot use it because of this problem.

**Comment by patrickml** [comment]
:+1:

**Comment by patrickml** [comment]
UPDATE : issue still persists on 1.3-rc.1

**Comment by arunoda** [comment]
For what ever the reason, I can't publish a new version to some dependency issues. I assume, that's because of we are using a RC version. I think meteor packaging system has some special meaning for tagged releases like above.

So, I suggest you to use this branch directly.
See: [`use-meteor-modules-support`](https://github.com/kadirahq/flow-router/tree/use-meteor-modules-support)

I'll publish a new version, when Meteor 1.3 released. (I hope it'll happen soon)

**Comment by sgasser** [comment]
@arunoda thx
How we can use this branch directly?

**Comment by suhail-ansari-apconic** [comment]
Just clone or download this branch code to your local packages folder until kadira fixes it. By the way the release date for meteor is March 21.

**Comment by redwards1966** [comment]
I created a packages folder under my application root and cd' to the packages folder, cloned the repo and ran meteor run and same error for me. Meteor newb here so maybe I'm misunderstanding what to do. The module I'm using is kadira:flow-router-ssr, and the package I cloned that was created in packages was flow-router, does that have any bearing?

**Comment by suhail-ansari-apconic** [comment]
Just remove kadirahq:flow-router-ssr from your packages. Clone this repo with this branch to your packages then run

**Comment by tmeasday** [comment]
@arunoda can we figure out what the problem with publishing is? It'd be super useful to get this out *before* 1.3 to ensure there aren't any issues with 1.3 we need to fix!

**Comment by macrozone** [comment]
Same issue as @redwards1966, I did also clone the repo in my packages folder, checked out use-meteor-modules-support and still got the same error.

What i found out is, that if you downgrade meteor, run it and upgrade again, the error no longer occures until you do a meteor reset or similar.

**Comment by patrickml** [comment]
Is there anyway you can just create an Npm package?

**Comment by arunoda** [comment]
Okay. I managed to publish a version of Flow Router SSR to the packaging server.
Use this version: `v3.12.1`

This version has some minor test failures. (comes with porting to RC).
I'll fix them in coming days. But I publish this because otherwise, it's hard to test the RC.

**Comment by tmeasday** [comment]
Thanks so much @arunoda!

**Comment by arunoda** [comment]
@tmeasday I had to use `meteor publish --release METEOR@1.3-rc.1`.

So, if there's a new RC, do I need to publish again?

**Comment by tmeasday** [comment]
@arunoda, nope. You just need to use `--release` when publishing packages that use features from new releases.

**Comment by arunoda** [comment]
@tmeasday That's great.
So, `METEOR@1.3-rc.1` comes out, it'll work properly.

**Comment by tmeasday** [comment]
@arunoda and what about a version of `flow-router` vanilla?

**Comment by arunoda** [comment]
Yeah. I can do that too. Will do it, I think that'll be pretty useful.

**Comment by merlinpatt** [comment]
That would be much appreciated! I was just about to start using Mantra, but since Mantra relies on on flow-router, I can't get my project started

**Comment by arunoda** [comment]
@merlinpatt just checkout the sample repo again. I've updated to use this version.

**Comment by merlinpatt** [comment]
I'm using the `mantra-cli` to create my starting repo, which uses the vanilla `kadira:flow-router` package in the [create command](https://github.com/mantrajs/mantra-cli/blob/master/lib/commands/create.js).

**Comment by arunoda** [comment]
@tmeasday @merlinpatt done.
try updating the vanilla FlowRouter.

**Comment by merlinpatt** [comment]
Thanks @arunoda. You're amazing with your super quick fixes!

**Comment by tmeasday** [comment]
Awesome: https://github.com/meteor/todos/commit/91fce29f3aec56caab921216cf2e227512ca1ef9

**Comment by arunoda** [comment]
We fixed some issues we had with Meteor 1.3 RC-1 and now you can use the SSR version with the confidence :) Thanks all for the help.

**Comment by Dev1an** [comment]
@suhail-ansari-apconic How do you now the meteor 1.3 release date?
