### ISSUE TITLE
Can routes be extended?

### ISSUE THREAD

**Issue by JulianKingman** [kadirahq/flow-router#558]
For example, this route from telescope:
````javascript
FlowRouter.route('/submit', {
  name: "postSubmit",
  action: function(params, queryParams) {
    BlazeLayout.render("layout", {main: "post_submit"});
  }
});
````
Can I add more actions to the route? Something like this would be ideal:
````javascript
FlowRouter.routes.postSubmit.action.extend = function(params, queryParams){
    console.log('Hey, a new action!');
}
````

**Comment by JulianKingman** [comment]
For further context, the main reason I want this is for package architecture, where the routes are already declared, and there are certain things I want to do (like render new elements) that should clearly be handled by the router, but for which I'm using really hacky things (like checking the route and rendering different things conditionally, basically making my own router).

**Comment by Dev1an** [comment]
I think you can use [triggers](https://github.com/kadirahq/flow-router#defining-triggers-globally) for this. Instead of extending the action, like you propose, add a trigger for that route.

**Comment by JulianKingman** [comment]
That seems like a pretty good solution. I'll give that a shot and post back my results.

**Comment by JulianKingman** [comment]
For reference, here's the way to do it:
````javascript
FlowRouter.triggers.enter([
  function () {
  //If you choose to render, also render the things that were already rendered in the original route
    BlazeLayout.render('layout', {
      main: "example_template",
      newZone: 'another_template'
    });
    console.log('on extended route');
  }
], {
  only: ["RouteNameGoesHere"]
});
````
