### ISSUE TITLE
Importing modules fails

### ISSUE THREAD

**Issue by Dev1an** [kadirahq/flow-router#559]
The import statements on the following lines throw an error:
https://github.com/kadirahq/flow-router/commit/dcdee9e10b46132bbd7dac9916b53fc842def331#diff-3dd91952b25589a53f18280a382b9567R2

I think it should be changed to `import Qs from 'qs';`

**Comment by Dev1an** [comment]
This is resolved in 86355da

**Comment by arunoda** [comment]
Thanks.
