### ISSUE TITLE
After adding kadira:flow-router-ssr it says gives errors While processing files with cosmos:browserify

### ISSUE THREAD

**Issue by THPubs** [kadirahq/flow-router#566]
I just added Flow Router SSR to my app and it gave me this error :

    => Errors prevented startup:                  
       
       While processing files with cosmos:browserify (for target web.browser):
       packages/kadira:flow-router-ssr/client.browserify.js: Arguments to path.resolve must be strings
       
       Browserify options:
       >  undefined
       
    => Your application has errors. Waiting for file change.

Any idea why?

**Comment by cstrat** [comment]
Same issue as people have been reporting here:

https://github.com/meteor/meteor/issues/6449

**Comment by arunoda** [comment]
We've fixed this with the latest versions of Flow Router (and in the SSR) verision. Make sure you are using the latest version of FR-SSR.

**Comment by THPubs** [comment]
Cool now it works!

**Comment by enricofoschi** [comment]
Well done @arunoda - thanks a million!
