### ISSUE TITLE
Meteor 1.3-rc.2 + kadira:flow-router@2.11.0 There is no route for the path: /

### ISSUE THREAD

**Issue by ccuilla** [kadirahq/flow-router#568]
I'm trying to test my app with Meteor 1.3-rc.2.

The first issue I'm encountering is the following error:

`There is no route for the path: /`

Any hints on where to look first on this?

**Comment by thewolf** [comment]
I have the same error after upgrading to 1.3, would you please share how you fixed it?

**Comment by bevinhex** [comment]
Same issue here, after upgrading 1.3, everything became messy.

**Comment by wesleyfsmith** [comment]
Any solution on this? I'm having the same problem.

**Comment by thewolf** [comment]
I found that some errors are not reported in the server or client consoles. and that any missing object or import could lead to the error  "There is no route for the path: /" 
to fix that error, I have upgraded to the lated 1.3 and fixed all the missing imports.

**Comment by wesleyfsmith** [comment]
@thewolf would you mind elaborating how you fixed the missing imports?

**Comment by joyacv2** [comment]
Why this is closed? Many people having the same problem, any idea?

**Comment by leandronsp** [comment]
Had same issue here, but fyi I just added the `/` route to the FlowRouter which simply does nothing
#weird, yes...

**Comment by ayushchd** [comment]
Having the same issue - just update to 1.3 and suddenly I get this error. How do I know which imports are not working?
