### ISSUE TITLE
Routes don't load in production

### ISSUE THREAD

**Issue by fayadh** [kadirahq/flow-router#573]
FlowRouter doesn't work when deploying with either mup or mupx. None of the routes are appearing/loading on the app. The app works perfectly well in development. 

Running Meteor 1.2.1 on Ubuntu 14.04, Digital Ocean. 

This is the message I get: 

There is no route for the path: /

mupx logs -f gives me:

[xxx.xxx.xxx.164] npm WARN deprecated This version of npm lacks support for important features,
npm WARN deprecated such as scoped packages, offered by the primary npm
npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
npm WARN deprecated latest stable version. To upgrade to npm@2, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest-2
[xxx.xxx.xxx.164] npm WARN deprecated
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated
[xxx.xxx.xxx.164] npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated
[xxx.xxx.xxx.164] npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
[xxx.xxx.xxx.164] npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated
[xxx.xxx.xxx.164] npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
[xxx.xxx.xxx.164] npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
[xxx.xxx.xxx.164] npm WARN package.json meteor-dev-bundle@0.0.0 No description
[xxx.xxx.xxx.164] npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
[xxx.xxx.xxx.164]
> fibers@1.0.5 install /bundle/bundle/programs/server/node_modules/fibers
[xxx.xxx.xxx.164] > node ./build.js

[xxx.xxx.xxx.164] `linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
[xxx.xxx.xxx.164] ansi-regex@0.2.1 node_modules/ansi-regex
[xxx.xxx.xxx.164]
[xxx.xxx.xxx.164] ansi-styles@1.1.0 node_modules/ansi-styles
[xxx.xxx.xxx.164]
[xxx.xxx.xxx.164] escape-string-regexp@1.0.3 node_modules/escape-string-regexp
[xxx.xxx.xxx.164]
[xxx.xxx.xxx.164] chalk@0.5.1 node_modules/chalk
[xxx.xxx.xxx.164]
[xxx.xxx.xxx.164] has-ansi@0.1.0 node_modules/has-ansi
[xxx.xxx.xxx.164]
[xxx.xxx.xxx.164] supports-color@0.2.0 node_modules/supports-color
[xxx.xxx.xxx.164]
[xxx.xxx.xxx.164] strip-ansi@0.3.0 node_modules/strip-ansi
[xxx.xxx.xxx.164]
[xxx.xxx.xxx.164] eachline@2.3.3 node_modules/eachline
[xxx.xxx.xxx.164]
[xxx.xxx.xxx.164] type-of@2.0.1 node_modules/type-of
[xxx.xxx.xxx.164]
[xxx.xxx.xxx.164] amdefine@1.0.0 node_modules/amdefine
[xxx.xxx.xxx.164]
[xxx.xxx.xxx.164] asap@2.0.3 node_modules/asap
[xxx.xxx.xxx.164]
[xxx.xxx.xxx.164] underscore@1.5.2 node_modules/underscore
[xxx.xxx.xxx.164]
[xxx.xxx.xxx.164] meteor-promise@0.5.0 node_modules/meteor-promise
[xxx.xxx.xxx.164]
[xxx.xxx.xxx.164] promise@7.0.4 node_modules/promise
[xxx.xxx.xxx.164]
[xxx.xxx.xxx.164] source-map-support@0.3.2 node_modules/source-map-support
[xxx.xxx.xxx.164]
[xxx.xxx.xxx.164] semver@4.1.0 node_modules/semver
[xxx.xxx.xxx.164]
[xxx.xxx.xxx.164] source-map@0.1.32 node_modules/source-map
[xxx.xxx.xxx.164]
[xxx.xxx.xxx.164] fibers@1.0.5 node_modules/fibers
[xxx.xxx.xxx.164] => Starting meteor app on port:80
[xxx.xxx.xxx.164] WARNING:
[xxx.xxx.xxx.164] cfs:graphicsmagick could not find "graphicsMagic" or "imageMagic" on the
[xxx.xxx.xxx.164] system.
[xxx.xxx.xxx.164]
[xxx.xxx.xxx.164] I just checked PATH to see if I could find the GraphicsMagick or ImageMagic
[xxx.xxx.xxx.164] unix/mac os/windows binaries on your system, I failed.
[xxx.xxx.xxx.164]
[xxx.xxx.xxx.164] Why:
[xxx.xxx.xxx.164] 1. I may be blind or naive, help making me smarter
[xxx.xxx.xxx.164] 2. You havent added the path to the binaries
[xxx.xxx.xxx.164] 3. You havent actually installed GraphicsMagick or ImageMagick
[xxx.xxx.xxx.164]
[xxx.xxx.xxx.164] *** Make sure "$PATH" environment is configured "PATH:/path/to/binaries" ***
[xxx.xxx.xxx.164]
[xxx.xxx.xxx.164] Installation hints:
[xxx.xxx.xxx.164] * Mac OS X "brew install graphicsmagick" or "brew install imagemagick"
[xxx.xxx.xxx.164] * Linux download rpm or use packagemanager
[xxx.xxx.xxx.164] * Centos "yum install GraphicsMagick"* Windows download the installer and run

Any suggestions for this problem?

**Comment by DylanRichardPearson** [comment]
Did you find a solution?

**Comment by grinono** [comment]
having the same issue.. any solution yet?

**Comment by erperejildo** [comment]
Can you post your solution pls?
