### ISSUE TITLE
Subscripion error after upgrade to Meteor 1.3.2.2

### ISSUE THREAD

**Issue by humbertocruz** [kadirahq/flow-router#597]
Hello, 

Shows the message "You can't use reactive data sources like Session inside the `.subscriptions` method!" on first loading. And there is no reactive data variables on my routes.js files.

Thx
Humberto

**Comment by abecks** [comment]
See https://github.com/kadirahq/fast-render/issues/166

**Comment by abernix** [comment]
@humbertocruz Are you using `fast-render` as well, or just `flow-router`?
