### ISSUE TITLE
[2.12.0] Problem in router.js: Uncaught ReferenceError: page is not defined

### ISSUE THREAD

**Issue by juliancwirko** [kadirahq/flow-router#602]
Hi, there is a problem in 2.12.0 In router.js, I get:

```
Uncaught ReferenceError: page is not defined
```

**Comment by cormip** [comment]
Also started getting the same problem after upgrading from 2.11.0 to 2.12.0

**Comment by Jeger** [comment]
This line:

`-  api.addFiles('client-modules.js', 'client');`

In [this commit](https://github.com/kadirahq/flow-router/commit/7b549d5706525ae1e89814b53a193fc5931d02d8) seems to be what is causing the problem.

**Comment by mikeifomin** [comment]
I have the same error. Meteor  1.3.2.4

versions
```
kadira:flow-router@2.12.0
meteorhacks:fast-render@2.14.0
```

**Comment by agentirons** [comment]
Yep, same error from upgrading to Meteor 1.3.2.4 and Flow-Router 2.12.0 -

`router.js:586 Uncaught ReferenceError: page is not defined`

`586 Router.prototype._page = page;`

**Comment by mikeifomin** [comment]
Downgrade to kadira:flow-router @2.11.0 helped!

**Comment by spiral2k** [comment]
hi, @mikeifomin how to downgrade?

**Comment by GraniteGames** [comment]
Also getting this issue

**Comment by spiral2k** [comment]
@mikeifomin it didnt helped :(

**Comment by spiral2k** [comment]
Does anybody has a solution for this problem,?

**Comment by yubozhao** [comment]
@spiral2k with downgrade, it works for me.   Good luck on your app

**Comment by michaeljberry** [comment]
Removing the 2.12.0 version and adding the 2.11.0 version worked for me. 

`meteor` add kadira:flow-router@=2.11.0`

**Comment by spiral2k** [comment]
@yubozhao @michaeljberry thanks a lot!.

**Comment by GraniteGames** [comment]
Version downgrade also worked for me

**Comment by arunoda** [comment]
Sorry about the issue. Will be working on a quick fix.

**Comment by arunoda** [comment]
Check version: `v2.12.1`. It has a fix for this.

**Comment by agentirons** [comment]
Works great, thanks!

**Comment by ujwal-setlur** [comment]
thanks, that works. thanks for the quick fix.

**Comment by arunoda** [comment]
Okay. Cool.

**Comment by anormore** [comment]
Just wanted to let you know that I did an meteor add kadira:flow-router and followed the doc.

Doesn't work. Found this thread on Google.

I had to put kadira:flow-router@2.11.0 in my packages list and it works.

I'm replacing Iron Router.
