### ISSUE TITLE
Newest Meteor Release (1.3.2.4) not working with FlowRouter 2.12.0

### ISSUE THREAD

**Issue by jebarjonet** [kadirahq/flow-router#603]
Source : https://forums.meteor.com/t/newest-meteor-release-not-working-with-flowrouter-2-12-0/21873

I just updated **meteor** to 1.3.2.4. Updated **flow-router** to 2.12.0

![errors](https://cloud.githubusercontent.com/assets/4401230/14726631/ec23c058-0823-11e6-8137-5e88d38e8a5b.PNG)

Worked perfectly fine until I update meteor and flow-router to those versions (last previous update was yesterday)

**Comment by jkhoffman** [comment]
Same exact problem, here.

**Comment by Falieson** [comment]
same
