### ISSUE TITLE
"There is no route for the path" error for images.

### ISSUE THREAD

**Issue by MeDBejoHok** [kadirahq/flow-router#645]
Guys I have this, when upload image
`-rwxr-xr-x 1 meteoruser meteoruser  330908 Jun  7 08:41 KJFvAWDPNxujbgEoJ.png`
In addition to newly created files in this folder there are old files.
`-r-xr-xr-x 1 meteoruser root        219910 Jun  7 08:38 LiqrLtSG2wsiPJhDr.png`
That were created earlier and they have other rights and another user (root against meteoruser). It seems to me, the rights is changing after deploy(via MUP). The problem is when I try to view the newly created images from the browser I get the error.
`There is no route for the path: – "/photos/KJFvAWDPNxujbgEoJ.png"`
Old files are displayed normally. I tried assign rights manually, it didn't helps. So any could help with this? Why I have this error?

**Comment by sejbr** [comment]
I have the same problem. Just started working with meteor and flow-router. Opening image url in webpage gives me no route path error and using the image as background-image in my scss just doesn't work at all no matter what path i supply.
Hopefully someone would be able to help us.

**Comment by MeDBejoHok** [comment]
@sejbr Try place background images to public folder. It should help.
