### ISSUE TITLE
When one redirect, redirects to another redirect, the URL is not the final URL, but intermediate.

### ISSUE THREAD

**Issue by lope** [kadirahq/flow-router#649]
When redirecting to a route that redirects to a second route, the URL shows the path used in the first call to FlowRouter.go()

This bug exists in FF and Chrome.

**Comment by s-devaney** [comment]
+1

**Comment by lope** [comment]
I've just noticed this, maybe it's new: the redirect() function.
It seems we should be using redirect() instead of FlowRouter.go() inside our FlowRouter functions.
https://github.com/kadirahq/flow-router#redirecting-with-triggers

**Comment by lope** [comment]
Seems to work fine.
