### ISSUE TITLE
Images + Favicon Not Rendering On Routes With a Nested '/'

### ISSUE THREAD

**Issue by boblikesoup** [kadirahq/flow-router#666]
For example: 

FlowRouter.route '/1/2' does not render some images or the favicon.
FlowRouter.route '/1' renders everything.

Using Blaze.

**Comment by tcguy** [comment]
Make sure you use leading slashes in referencing assets located in the public folder to eliminate problems displaying in nested routes:
<img src="/images/kitten.png"> instead of <img src="images/kitten.png">
