### ISSUE TITLE
Using a redux Provider with FlowRouter and Layouts

### ISSUE THREAD

**Issue by Spiralis** [kadirahq/flow-router#671]
I am developing a project that is using this kadira:flow-router package for React components. I am now setting up Redux, and thought it would be a good idea to use the Provider approach, as directed when using the [react-redux](https://github.com/reactjs/react-redux) package.

But, where do I put the `<Provider/>` wrapper?

```
FlowRouter.route('/', {
    action() {
        mount(MainLayout, {
            content: <AppContent/> />
        })
    }
});

FlowRouter.route('/test', {
    action() {
        mount(TestLayout, {
            content: <TestContent/> />
        })
    }
});
```

Should the Provider somehow wrap the pure layouts `MainLayout` and `TestLayout`, or should they somehow wrap inside the `mount()` command?

**Comment by Spiralis** [comment]
BTW, I am also using [react-mounter](https://github.com/kadirahq/react-mounter), as you can see from the examples above.

**Comment by Spiralis** [comment]
Not sure if I am doing this right, but I have ended up adding the store code in the respective layout files.

```
import store from '/.store.js'

export const MainLayout = ({content}) => (
    <Provider store={store}>
        ...
    </Provider>
)
```

**Comment by zhe1ka** [comment]
@Spiralis are you staying on this variant? 
I have the same question.

**Comment by Spiralis** [comment]
For now, yes. 
But, I am considering changing to [this model](https://github.com/kadirahq/meteor-react-layout/issues/52) to avoid having to add them to each Layout. Since I am yet only using just one layout it hasn't become the priority to change this. As soon as more layouts are added I am guessing that I will consider it. But, it is a small wrapper to add to the layouts so... Not sure...
