### ISSUE TITLE
Changing route via address bar reloads page

### ISSUE THREAD

**Issue by Orbyt** [kadirahq/flow-router#672]
Just wondering why this is. Navigating to a new route via an `<a href="">` attribute will swap out the templates without reloading the page. But if I manually change the route via the address bar, the entire page will reload.

Why is this?

**Comment by cesarve77** [comment]
+1

**Comment by zhaoyao91** [comment]
+1

**Comment by Orbyt** [comment]
This is, AFAIK, default behavior of the browser, where navigating via the address bar will trigger a reload. I'll close this but others can feel free to chime in with more info.
