### ISSUE TITLE
onClick={()=>FlowRouter.go('/foo')} OR <a href='/foo'> ??

### ISSUE THREAD

**Issue by lope** [kadirahq/flow-router#676]
Hi, I've asked on #meteor (freenode) many times but not gotten an answer yet.

What is best for fast performance and UX?

`<span onClick={()=>FlowRouter.go('/foo')}>foo</span>` OR `<a href='/foo'>foo</a>` ?

I've searched the FlowRouter github code and can't find any of the following
"link"
"A"
"href" (only in `tests/`, but irrelevant)

So that means (as far as I can see) FlowRouter does not currently hijack hyperlinks.
So it would seem that when you click a link, it makes a new GET request.
However, when I watch the "Network" tab in Firefox, and click links, there are no new requests.
So it seems hyperlinks are hijacked by something in the stack... Which would mean that there is no performance benefit in using onClick...FlowRouter.go() vs <a href... 

?
Thanks in advance for clarifying

**Comment by rogchap** [comment]
Have a look at #215. ```<a href='/foo'>foo</a>``` will do the job.

**Comment by lope** [comment]
Thanks @rogchap
