### ISSUE TITLE
How go back to previous website when clicking on browser back button?

### ISSUE THREAD

**Issue by lnmunhoz** [kadirahq/flow-router#693]
When users arrives to my website, I need to make them be able to go back to previous website (referral website) by clicking in the back button of the browser. Is that possible?

**Comment by NitroBAY** [comment]
This doesn't seems related to flow router. I'm not an expert but I know that with JS you can `window.history.back();` to go back to previous page navigated by the browser.

**Comment by lnmunhoz** [comment]
We accomplished by changing pushState function to empty function.

```js
FlowRouter._page.Context.prototype.pushState = () => {};
```
