### ISSUE TITLE
Redirect doesn't change the path

### ISSUE THREAD

**Issue by gaillota** [kadirahq/flow-router#698]
Hey guys,

I have a redirection like this 
``` 
FlowRouter.route('/', {
    name: 'public.index',
    action() {
        FlowRouter.go('somewhere-else');
    }
});
```
When my application starts, the redirection works perfectly fine and I land on `/somewhere-else`.
But when I click on a link with the `{{pathFor 'public.index'}}`, the redirection happens but the URL doesn't change and stays `/`.

Any idea why ?

**Comment by HenriBeck** [comment]
Maybe try redirecting with triggers

https://github.com/kadirahq/flow-router#redirecting-with-triggers

**Comment by gaillota** [comment]
Yes, sorry, I tried to use triggers and it worked.
If forgot about this issue, my bad.
Thanks for the help anyway.
