### ISSUE TITLE
FlowRouter.go not going

### ISSUE THREAD

**Issue by frankapimenta** [kadirahq/flow-router#699]
I have a qrcode reader that on scan executes either of two code lines.

```javascript
qrCodeScanner.on("scan", function(err, mes) {
  if(mes) {
    FlowRouter.go("there");
  } else {
    FlowRouter.go("overthere");
  }
});
```
none of the FlowRouter.go are working.

Any ideas about what might be wrong? I think that .go only considers first call right?

**Comment by jhuenges** [comment]
Have you tried it with an actual route like:
```js
FlowRouter.go('/home');
```
?

**Comment by frankapimenta** [comment]
Yes. Of course. 

FlowRouter.go("showArticle", {_id: "<id>"});

**Comment by jhuenges** [comment]
No, not the name, the path:
`FlowRouter.go('/showarticle/2`);`

**Comment by frankapimenta** [comment]
Coming back to the problem after a long break made me realise that it was my mistake. It works fine. I'm sorry about it.
Thank you for your time!
