### ISSUE TITLE
`:` symbol in URL not handled well - from timestamp in URL

### ISSUE THREAD

**Issue by jononomo** [kadirahq/flow-router#79]
So I have a route defined like this:

```
    FlowRouter.route('/audit/:id/', {
        name: 'audit',
        action: function(params, queryParams) {
            FlowLayout.render('layout', {
                left_nav: 'audit_nav',
                main: 'audit',
            });
        },
    });
```

I would like my URL to contain a timestamp -- the :id portion of the route should contain a timestamp in my app.

My event that invokes the route is defined like this:

```
    'click .audit-radio': function(event) {
        console.log('audit-radio clicked: '+this._id)
        Session.set('audit-displayed', this._id);
        FlowRouter.go('/audit/'+this._id+'/')
    }
```

console shows:

    audit-radio clicked: Jon-Apr13-15:43:19

But FlowRouter creates the URL as `/audit/Jon-Apr13-15`   -- notice that it drops from the `:` onward.

**Comment by arunoda** [comment]
I can see the reason.
Let me check this.

**Comment by jononomo** [comment]
May be relevant: http://stackoverflow.com/questions/2053132/is-a-colon-safe-for-friendly-url-use
